local streets = {}

streets.brazil = {
    "Alameda Campinas",
    "Alameda das Acácias",
    "Alameda das Flores",
    "Alameda dos Anjos",
    "Alameda dos Jasmins",
    "Alameda Santos",
    "Avenida Afonso Pena",
    "Avenida Beira-Mar",
    "Avenida Beira-Rio",
    "Avenida Brasil",
    "Avenida Castelo Branco",
    "Avenida Presidente Kennedy",
    "Avenida das Américas",
    "Avenida das Nações",
    "Avenida dos Estados",
    "Avenida dos Bandeirantes",
    "Avenida dos Imigrantes",
    "Avenida Duque de Caxias",
    "Avenida Floriano Peixoto",
    "Avenida Getúlio Vargas",
    "Avenida Independência",
    "Avenida Ipiranga",
    "Avenida João Pessoa",
    "Avenida Juscelino Kubitschek",
    "Avenida Marechal Rondon",
    "Avenida Nossa Senhora de Fátima",
    "Avenida Paulista",
    "Avenida Presidente Vargas",
    "Avenida Rio Branco",
    "Avenida Santos Dumont",
    "Avenida São João",
    "Avenida Sete de Setembro",
    "Avenida Tancredo Neves",
    "Avenida Tiradentes",
    "Avenida Ulysses Guimarães",
    "Avenida Washington Luís",
    "Beco da Esperança",
    "Beco do Sossego",
    "Estrada da Serra",
    "Estrada das Cachoeiras",
    "Estrada do Engenho",
    "Estrada do Sertão",
    "Estrada Velha",
    "Ladeira da Misericórdia",
    "Ladeira do Carmo",
    "Largo da Matriz",
    "Largo do Rosário",
    "Largo São Francisco",
    "Praça Central",
    "Praça da Bandeira",
    "Praça da Estação",
    "Praça da Independência",
    "Praça da Liberdade",
    "Praça da Matriz",
    "Praça da República",
    "Praça das Flores",
    "Praça do Cruzeiro",
    "Praça dos Três Poderes",
    "Praça Santos Dumont",
    "Praça Tiradentes",
    "Rodovia BR-101",
    "Rodovia BR-116",
    "Rodovia BR-153",
    "Rodovia BR-364",
    "Rua Abolição",
    "Rua Alberto Santos Dumont",
    "Rua Almirante Barroso",
    "Rua Álvares Cabral",
    "Rua Amazonas",
    "Rua Anchieta",
    "Rua Anita Garibaldi",
    "Rua Bahia",
    "Rua Barão de Mauá",
    "Rua Barão do Rio Branco",
    "Rua Benjamin Constant",
    "Rua Bento Gonçalves",
    "Rua Bom Jesus",
    "Rua Brena Laurindo",
    "Rua Cândido Portinari",
    "Rua Carlos Drummond de Andrade",
    "Rua Carlos Gomes",
    "Rua Castro Alves",
    "Rua Cecília Meireles",
    "Rua Ceará",
    "Rua Chico Mendes",
    "Rua Clarice Lispector",
    "Rua Coronel Fabriciano",
    "Rua da Alegria",
    "Rua da Amizade",
    "Rua da Aurora",
    "Rua da Cidadania",
    "Rua da Conceição",
    "Rua da Consolação",
    "Rua da Cruz",
    "Rua da Escola",
    "Rua da Esperança",
    "Rua da Estação",
    "Rua da Estrela",
    "Rua da Faculdade",
    "Rua da Família",
    "Rua da Harmonia",
    "Rua da Igreja",
    "Rua da Independência",
    "Rua da Justiça",
    "Rua da Lagoa",
    "Rua da Lealdade",
    "Rua da Liberdade",
    "Rua da Mangueira",
    "Rua da Nova Esperança",
    "Rua da Paz",
    "Rua da Ponte",
    "Rua da Praia",
    "Rua da Primavera",
    "Rua da Quitanda",
    "Rua da Saudade",
    "Rua da União",
    "Rua da Usina",
    "Rua da Verdade",
    "Rua das Acácias",
    "Rua das Camélias",
    "Rua das Flores",
    "Rua das Gaivotas",
    "Rua das Hortênsias",
    "Rua das Laranjeiras",
    "Rua das Mangabeiras",
    "Rua das Margaridas",
    "Rua das Orquídeas",
    "Rua das Palmeiras",
    "Rua das Rosas",
    "Rua das Violetas",
    "Rua Direita",
    "Rua do Aeroporto",
    "Rua do Bairro Novo",
    "Rua do Bosque",
    "Rua do Brasil",
    "Rua do Campo",
    "Rua do Catete",
    "Rua do Comércio",
    "Rua do Contorno",
    "Rua do Cruzeiro",
    "Rua do Encanto",
    "Rua do Futuro",
    "Rua do Horizonte",
    "Rua do Hospital",
    "Rua do Jardim",
    "Rua do Mar",
    "Rua do Mercado",
    "Rua do Mirante",
    "Rua do Ouvidor",
    "Rua do Parque",
    "Rua do Porto",
    "Rua do Porto Seguro",
    "Rua do Progresso",
    "Rua do Rosário",
    "Rua do Saber",
    "Rua do Sol",
    "Rua do Trabalhador",
    "Rua do Vale",
    "Rua Dom Pedro I",
    "Rua Dom Pedro II",
    "Rua dos Andradas",
    "Rua dos Cajueiros",
    "Rua dos Coqueiros",
    "Rua dos Eucaliptos",
    "Rua dos Girassóis",
    "Rua dos Ipês",
    "Rua dos Jacarandás",
    "Rua dos Pescadores",
    "Rua dos Pinheiros",
    "Rua dos Pioneiros",
    "Rua dos Sabiás",
    "Rua dos Tropeiros",
    "Rua Duque de Caxias",
    "Rua Eduardo Reinert",
    "Rua Euclides da Cunha",
    "Rua Felipe Camarão",
    "Rua Floriano Peixoto",
    "Rua Frei Caneca",
    "Rua General Osório",
    "Rua Goiás",
    "Rua Gonçalves Dias",
    "Rua Guararapes",
    "Rua Hercílio Luz",
    "Rua Irmã Dulce",
    "Rua Joaquim Nabuco",
    "Rua José Bonifácio",
    "Rua José de Alencar",
    "Rua Machado de Assis",
    "Rua Marechal Deodoro",
    "Rua Maria Quitéria",
    "Rua Mato Grosso",
    "Rua Minas Gerais",
    "Rua Monteiro Lobato",
    "Rua Nossa Senhora Aparecida",
    "Rua Oswaldo Cruz",
    "Rua Padre Anchieta",
    "Rua Paraná",
    "Rua Pernambuco",
    "Rua Princesa Isabel",
    "Rua Quinze de Novembro",
    "Rua Rachel de Queiroz",
    "Rua Rio Grande do Sul",
    "Rua Rui Barbosa",
    "Rua Santa Catarina",
    "Rua Santo Antônio",
    "Rua São Bento",
    "Rua São Jorge",
    "Rua São José",
    "Rua São Paulo",
    "Rua São Pedro",
    "Rua São Sebastião",
    "Rua Sergipe",
    "Rua Sete de Setembro",
    "Rua Tamandaré",
    "Rua Tiradentes",
    "Rua Treze de Maio",
    "Rua Vinte e Um de Abril",
    "Rua Visconde de Mauá",
    "Rua Voluntários da Pátria",
    "Travessa da Paz",
    "Travessa do Comércio",
    "Travessa dos Artistas",
    "Vila Operária",
}

streets.brazil_sul = streets.brazil
streets.brazil_sudeste = streets.brazil
streets.brazil_nordeste = streets.brazil
streets.brazil_norte = streets.brazil
streets.brazil_centro_oeste = streets.brazil

return streets
