-- Source: IBGE (servicodados.ibge.gov.br/api/v1/localidades/municipios)
return {
	"Abadia dos Dourados",
	"Abaeté",
	"Abre Campo",
	"Acaiaca",
	"Açucena",
	"Adamantina",
	"Adolfo",
	"Afonso Cláudio",
	"Água Boa",
	"Água Comprida",
	"Água Doce do Norte",
	"Aguaí",
	"Aguanil",
	"Águas da Prata",
	"Águas de Lindóia",
	"Águas de Santa Bárbara",
	"Águas de São Pedro",
	"Águas Formosas",
	"Águas Vermelhas",
	"Agudos",
	"Águia Branca",
	"Aimorés",
	"Aiuruoca",
	"Alagoa",
	"Alambari",
	"Albertina",
	"Alegre",
	"Além Paraíba",
	"Alfenas",
	"Alfredo Chaves",
	"Alfredo Marcondes",
	"Alfredo Vasconcelos",
	"Almenara",
	"Alpercata",
	"Alpinópolis",
	"Altair",
	"Alterosa",
	"Altinópolis",
	"Alto Alegre",
	"Alto Caparaó",
	"Alto Jequitibá",
	"Alto Rio Doce",
	"Alto Rio Novo",
	"Alumínio",
	"Alvarenga",
	"Álvares Florence",
	"Álvares Machado",
	"Álvaro de Carvalho",
	"Alvinlândia",
	"Alvinópolis",
	"Alvorada de Minas",
	"Americana",
	"Américo Brasiliense",
	"Américo de Campos",
	"Amparo",
	"Amparo do Serra",
	"Analândia",
	"Anchieta",
	"Andradas",
	"Andradina",
	"Andrelândia",
	"Angatuba",
	"Angelândia",
	"Angra dos Reis",
	"Anhembi",
	"Anhumas",
	"Antônio Carlos",
	"Antônio Dias",
	"Antônio Prado de Minas",
	"Aparecida",
	"Aparecida d'Oeste",
	"Aperibé",
	"Apiacá",
	"Apiaí",
	"Araçaí",
	"Araçariguama",
	"Araçatuba",
	"Aracitaba",
	"Araçoiaba da Serra",
	"Aracruz",
	"Araçuaí",
	"Araguari",
	"Aramina",
	"Arandu",
	"Arantina",
	"Arapeí",
	"Araponga",
	"Araporã",
	"Arapuá",
	"Araraquara",
	"Araras",
	"Araruama",
	"Araújos",
	"Araxá",
	"Arceburgo",
	"Arco-Íris",
	"Arcos",
	"Areado",
	"Areal",
	"Arealva",
	"Areias",
	"Areiópolis",
	"Argirita",
	"Aricanduva",
	"Arinos",
	"Ariranha",
	"Armação dos Búzios",
	"Arraial do Cabo",
	"Artur Nogueira",
	"Arujá",
	"Aspásia",
	"Assis",
	"Astolfo Dutra",
	"Ataléia",
	"Atibaia",
	"Atílio Vivácqua",
	"Augusto de Lima",
	"Auriflama",
	"Avaí",
	"Avanhandava",
	"Avaré",
	"Bady Bassitt",
	"Baependi",
	"Baixo Guandu",
	"Balbinos",
	"Baldim",
	"Bálsamo",
	"Bambuí",
	"Bananal",
	"Bandeira",
	"Bandeira do Sul",
	"Barão de Antonina",
	"Barão de Cocais",
	"Barão do Monte Alto",
	"Barbacena",
	"Barbosa",
	"Bariri",
	"Barra Bonita",
	"Barra de São Francisco",
	"Barra do Chapéu",
	"Barra do Piraí",
	"Barra do Turvo",
	"Barra Longa",
	"Barra Mansa",
	"Barretos",
	"Barrinha",
	"Barroso",
	"Barueri",
	"Bastos",
	"Batatais",
	"Bauru",
	"Bebedouro",
	"Bela Vista de Minas",
	"Belford Roxo",
	"Belmiro Braga",
	"Belo Horizonte",
	"Belo Oriente",
	"Belo Vale",
	"Bento de Abreu",
	"Berilo",
	"Berizal",
	"Bernardino de Campos",
	"Bertioga",
	"Bertópolis",
	"Betim",
	"Bias Fortes",
	"Bicas",
	"Bilac",
	"Biquinhas",
	"Birigui",
	"Biritiba Mirim",
	"Boa Esperança",
	"Boa Esperança do Sul",
	"Bocaina",
	"Bocaina de Minas",
	"Bocaiúva",
	"Bofete",
	"Boituva",
	"Bom Despacho",
	"Bom Jardim",
	"Bom Jardim de Minas",
	"Bom Jesus da Penha",
	"Bom Jesus do Amparo",
	"Bom Jesus do Galho",
	"Bom Jesus do Itabapoana",
	"Bom Jesus do Norte",
	"Bom Jesus dos Perdões",
	"Bom Repouso",
	"Bom Sucesso",
	"Bom Sucesso de Itararé",
	"Bonfim",
	"Bonfinópolis de Minas",
	"Bonito de Minas",
	"Borá",
	"Boracéia",
	"Borborema",
	"Borda da Mata",
	"Borebi",
	"Botelhos",
	"Botucatu",
	"Botumirim",
	"Bragança Paulista",
	"Brás Pires",
	"Brasilândia de Minas",
	"Brasília de Minas",
	"Braúna",
	"Braúnas",
	"Brazópolis",
	"Brejetuba",
	"Brejo Alegre",
	"Brodowski",
	"Brotas",
	"Brumadinho",
	"Bueno Brandão",
	"Buenópolis",
	"Bugre",
	"Buri",
	"Buritama",
	"Buritis",
	"Buritizal",
	"Buritizeiro",
	"Cabeceira Grande",
	"Cabo Frio",
	"Cabo Verde",
	"Cabrália Paulista",
	"Cabreúva",
	"Caçapava",
	"Cachoeira da Prata",
	"Cachoeira de Minas",
	"Cachoeira de Pajeú",
	"Cachoeira Dourada",
	"Cachoeira Paulista",
	"Cachoeiras de Macacu",
	"Cachoeiro de Itapemirim",
	"Caconde",
	"Caetanópolis",
	"Caeté",
	"Cafelândia",
	"Caiabu",
	"Caiana",
	"Caieiras",
	"Caiuá",
	"Cajamar",
	"Cajati",
	"Cajobi",
	"Cajuri",
	"Cajuru",
	"Caldas",
	"Camacho",
	"Camanducaia",
	"Cambuci",
	"Cambuí",
	"Cambuquira",
	"Campanário",
	"Campanha",
	"Campestre",
	"Campina do Monte Alegre",
	"Campina Verde",
	"Campinas",
	"Campo Azul",
	"Campo Belo",
	"Campo do Meio",
	"Campo Florido",
	"Campo Limpo Paulista",
	"Campos Altos",
	"Campos do Jordão",
	"Campos dos Goytacazes",
	"Campos Gerais",
	"Campos Novos Paulista",
	"Cana Verde",
	"Canaã",
	"Cananéia",
	"Canápolis",
	"Canas",
	"Candeias",
	"Cândido Mota",
	"Cândido Rodrigues",
	"Canitar",
	"Cantagalo",
	"Capão Bonito",
	"Caparaó",
	"Capela do Alto",
	"Capela Nova",
	"Capelinha",
	"Capetinga",
	"Capim Branco",
	"Capinópolis",
	"Capitão Andrade",
	"Capitão Enéas",
	"Capitólio",
	"Capivari",
	"Caputira",
	"Caraguatatuba",
	"Caraí",
	"Caranaíba",
	"Carandaí",
	"Carangola",
	"Carapebus",
	"Carapicuíba",
	"Caratinga",
	"Carbonita",
	"Cardoso",
	"Cardoso Moreira",
	"Careaçu",
	"Cariacica",
	"Carlos Chagas",
	"Carmésia",
	"Carmo",
	"Carmo da Cachoeira",
	"Carmo da Mata",
	"Carmo de Minas",
	"Carmo do Cajuru",
	"Carmo do Paranaíba",
	"Carmo do Rio Claro",
	"Carmópolis de Minas",
	"Carneirinho",
	"Carrancas",
	"Carvalhópolis",
	"Carvalhos",
	"Casa Branca",
	"Casa Grande",
	"Cascalho Rico",
	"Casimiro de Abreu",
	"Cássia",
	"Cássia dos Coqueiros",
	"Castelo",
	"Castilho",
	"Cataguases",
	"Catanduva",
	"Catas Altas",
	"Catas Altas da Noruega",
	"Catiguá",
	"Catuji",
	"Catuti",
	"Caxambu",
	"Cedral",
	"Cedro do Abaeté",
	"Central de Minas",
	"Centralina",
	"Cerqueira César",
	"Cerquilho",
	"Cesário Lange",
	"Chácara",
	"Chalé",
	"Chapada do Norte",
	"Chapada Gaúcha",
	"Charqueada",
	"Chavantes",
	"Chiador",
	"Cipotânea",
	"Claraval",
	"Claro dos Poções",
	"Cláudio",
	"Clementina",
	"Coimbra",
	"Colatina",
	"Colina",
	"Colômbia",
	"Coluna",
	"Comendador Gomes",
	"Comendador Levy Gasparian",
	"Comercinho",
	"Conceição da Aparecida",
	"Conceição da Barra",
	"Conceição da Barra de Minas",
	"Conceição das Alagoas",
	"Conceição das Pedras",
	"Conceição de Ipanema",
	"Conceição de Macabu",
	"Conceição do Castelo",
	"Conceição do Mato Dentro",
	"Conceição do Pará",
	"Conceição do Rio Verde",
	"Conceição dos Ouros",
	"Conchal",
	"Conchas",
	"Cônego Marinho",
	"Confins",
	"Congonhal",
	"Congonhas",
	"Congonhas do Norte",
	"Conquista",
	"Conselheiro Lafaiete",
	"Conselheiro Pena",
	"Consolação",
	"Contagem",
	"Coqueiral",
	"Coração de Jesus",
	"Cordeiro",
	"Cordeirópolis",
	"Cordisburgo",
	"Cordislândia",
	"Corinto",
	"Coroaci",
	"Coroados",
	"Coromandel",
	"Coronel Fabriciano",
	"Coronel Macedo",
	"Coronel Murta",
	"Coronel Pacheco",
	"Coronel Xavier Chaves",
	"Córrego Danta",
	"Córrego do Bom Jesus",
	"Córrego Fundo",
	"Córrego Novo",
	"Corumbataí",
	"Cosmópolis",
	"Cosmorama",
	"Cotia",
	"Couto de Magalhães de Minas",
	"Cravinhos",
	"Crisólita",
	"Cristais",
	"Cristais Paulista",
	"Cristália",
	"Cristiano Otoni",
	"Cristina",
	"Crucilândia",
	"Cruzália",
	"Cruzeiro",
	"Cruzeiro da Fortaleza",
	"Cruzília",
	"Cubatão",
	"Cunha",
	"Cuparaque",
	"Curral de Dentro",
	"Curvelo",
	"Datas",
	"Delfim Moreira",
	"Delfinópolis",
	"Delta",
	"Descalvado",
	"Descoberto",
	"Desterro de Entre Rios",
	"Desterro do Melo",
	"Diadema",
	"Diamantina",
	"Diogo de Vasconcelos",
	"Dionísio",
	"Dirce Reis",
	"Divinésia",
	"Divino",
	"Divino das Laranjeiras",
	"Divino de São Lourenço",
	"Divinolândia",
	"Divinolândia de Minas",
	"Divinópolis",
	"Divisa Alegre",
	"Divisa Nova",
	"Divisópolis",
	"Dobrada",
	"Dois Córregos",
	"Dolcinópolis",
	"Dom Bosco",
	"Dom Cavati",
	"Dom Joaquim",
	"Dom Silvério",
	"Dom Viçoso",
	"Domingos Martins",
	"Dona Euzébia",
	"Dores de Campos",
	"Dores de Guanhães",
	"Dores do Indaiá",
	"Dores do Rio Preto",
	"Dores do Turvo",
	"Doresópolis",
	"Dourado",
	"Douradoquara",
	"Dracena",
	"Duartina",
	"Duas Barras",
	"Dumont",
	"Duque de Caxias",
	"Durandé",
	"Echaporã",
	"Ecoporanga",
	"Eldorado",
	"Elias Fausto",
	"Elisiário",
	"Elói Mendes",
	"Embaúba",
	"Embu das Artes",
	"Embu-Guaçu",
	"Emilianópolis",
	"Engenheiro Caldas",
	"Engenheiro Coelho",
	"Engenheiro Navarro",
	"Engenheiro Paulo de Frontin",
	"Entre Folhas",
	"Entre Rios de Minas",
	"Ervália",
	"Esmeraldas",
	"Espera Feliz",
	"Espinosa",
	"Espírito Santo do Dourado",
	"Espírito Santo do Pinhal",
	"Espírito Santo do Turvo",
	"Estiva",
	"Estiva Gerbi",
	"Estrela d'Oeste",
	"Estrela Dalva",
	"Estrela do Indaiá",
	"Estrela do Norte",
	"Estrela do Sul",
	"Euclides da Cunha Paulista",
	"Eugenópolis",
	"Ewbank da Câmara",
	"Extrema",
	"Fama",
	"Faria Lemos",
	"Fartura",
	"Felício dos Santos",
	"Felisburgo",
	"Felixlândia",
	"Fernandes Tourinho",
	"Fernando Prestes",
	"Fernandópolis",
	"Fernão",
	"Ferraz de Vasconcelos",
	"Ferros",
	"Fervedouro",
	"Flora Rica",
	"Floreal",
	"Florestal",
	"Flórida Paulista",
	"Florínea",
	"Formiga",
	"Formoso",
	"Fortaleza de Minas",
	"Fortuna de Minas",
	"Franca",
	"Francisco Badaró",
	"Francisco Dumont",
	"Francisco Morato",
	"Francisco Sá",
	"Franciscópolis",
	"Franco da Rocha",
	"Frei Gaspar",
	"Frei Inocêncio",
	"Frei Lagonegro",
	"Fronteira",
	"Fronteira dos Vales",
	"Fruta de Leite",
	"Frutal",
	"Fundão",
	"Funilândia",
	"Gabriel Monteiro",
	"Gália",
	"Galiléia",
	"Gameleiras",
	"Garça",
	"Gastão Vidigal",
	"Gavião Peixoto",
	"General Salgado",
	"Getulina",
	"Glaucilândia",
	"Glicério",
	"Goiabeira",
	"Goianá",
	"Gonçalves",
	"Gonzaga",
	"Gouveia",
	"Governador Lindenberg",
	"Governador Valadares",
	"Grão Mogol",
	"Grupiara",
	"Guaçuí",
	"Guaiçara",
	"Guaimbê",
	"Guaíra",
	"Guanhães",
	"Guapé",
	"Guapiaçu",
	"Guapiara",
	"Guapimirim",
	"Guará",
	"Guaraçaí",
	"Guaraci",
	"Guaraciaba",
	"Guaraciama",
	"Guaranésia",
	"Guarani",
	"Guarani d'Oeste",
	"Guarantã",
	"Guarapari",
	"Guarará",
	"Guararapes",
	"Guararema",
	"Guaratinguetá",
	"Guarda-Mor",
	"Guareí",
	"Guariba",
	"Guarujá",
	"Guarulhos",
	"Guatapará",
	"Guaxupé",
	"Guidoval",
	"Guimarânia",
	"Guiricema",
	"Gurinhatã",
	"Guzolândia",
	"Heliodora",
	"Herculândia",
	"Holambra",
	"Hortolândia",
	"Iacanga",
	"Iacri",
	"Iapu",
	"Iaras",
	"Ibaté",
	"Ibatiba",
	"Ibertioga",
	"Ibiá",
	"Ibiaí",
	"Ibirá",
	"Ibiracatu",
	"Ibiraci",
	"Ibiraçu",
	"Ibirarema",
	"Ibirité",
	"Ibitinga",
	"Ibitirama",
	"Ibitiúra de Minas",
	"Ibituruna",
	"Ibiúna",
	"Icaraí de Minas",
	"Icém",
	"Iconha",
	"Iepê",
	"Igaraçu do Tietê",
	"Igarapava",
	"Igarapé",
	"Igaratá",
	"Igaratinga",
	"Iguaba Grande",
	"Iguape",
	"Iguatama",
	"Ijaci",
	"Ilha Comprida",
	"Ilha Solteira",
	"Ilhabela",
	"Ilicínea",
	"Imbé de Minas",
	"Inconfidentes",
	"Indaiabira",
	"Indaiatuba",
	"Indiana",
	"Indianópolis",
	"Indiaporã",
	"Ingaí",
	"Inhapim",
	"Inhaúma",
	"Inimutaba",
	"Inúbia Paulista",
	"Ipaba",
	"Ipanema",
	"Ipatinga",
	"Ipaussu",
	"Iperó",
	"Ipeúna",
	"Ipiaçu",
	"Ipiguá",
	"Iporanga",
	"Ipuã",
	"Ipuiúna",
	"Iracemápolis",
	"Iraí de Minas",
	"Irapuã",
	"Irapuru",
	"Irupi",
	"Itaberá",
	"Itabira",
	"Itabirinha",
	"Itabirito",
	"Itaboraí",
	"Itacambira",
	"Itacarambi",
	"Itaguaçu",
	"Itaguaí",
	"Itaguara",
	"Itaí",
	"Itaipé",
	"Itajobi",
	"Itaju",
	"Itajubá",
	"Italva",
	"Itamarandiba",
	"Itamarati de Minas",
	"Itambacuri",
	"Itambé do Mato Dentro",
	"Itamogi",
	"Itamonte",
	"Itanhaém",
	"Itanhandu",
	"Itanhomi",
	"Itaobim",
	"Itaoca",
	"Itaocara",
	"Itapagipe",
	"Itapecerica",
	"Itapecerica da Serra",
	"Itapemirim",
	"Itaperuna",
	"Itapetininga",
	"Itapeva",
	"Itapevi",
	"Itapira",
	"Itapirapuã Paulista",
	"Itápolis",
	"Itaporanga",
	"Itapuí",
	"Itapura",
	"Itaquaquecetuba",
	"Itarana",
	"Itararé",
	"Itariri",
	"Itatiaia",
	"Itatiaiuçu",
	"Itatiba",
	"Itatinga",
	"Itaú de Minas",
	"Itaúna",
	"Itaverava",
	"Itinga",
	"Itirapina",
	"Itirapuã",
	"Itobi",
	"Itu",
	"Itueta",
	"Ituiutaba",
	"Itumirim",
	"Itupeva",
	"Iturama",
	"Itutinga",
	"Ituverava",
	"Iúna",
	"Jaborandi",
	"Jaboticabal",
	"Jaboticatubas",
	"Jacareí",
	"Jaci",
	"Jacinto",
	"Jacuí",
	"Jacupiranga",
	"Jacutinga",
	"Jaguaraçu",
	"Jaguaré",
	"Jaguariúna",
	"Jaíba",
	"Jales",
	"Jambeiro",
	"Jampruca",
	"Janaúba",
	"Jandira",
	"Januária",
	"Japaraíba",
	"Japeri",
	"Japonvar",
	"Jardinópolis",
	"Jarinu",
	"Jaú",
	"Jeceaba",
	"Jenipapo de Minas",
	"Jequeri",
	"Jequitaí",
	"Jequitibá",
	"Jequitinhonha",
	"Jeriquara",
	"Jerônimo Monteiro",
	"Jesuânia",
	"Joaíma",
	"Joanésia",
	"Joanópolis",
	"João Monlevade",
	"João Neiva",
	"João Pinheiro",
	"João Ramalho",
	"Joaquim Felício",
	"Jordânia",
	"José Bonifácio",
	"José Gonçalves de Minas",
	"José Raydan",
	"Josenópolis",
	"Juatuba",
	"Juiz de Fora",
	"Júlio Mesquita",
	"Jumirim",
	"Jundiaí",
	"Junqueirópolis",
	"Juquiá",
	"Juquitiba",
	"Juramento",
	"Juruaia",
	"Juvenília",
	"Ladainha",
	"Lagamar",
	"Lagoa da Prata",
	"Lagoa dos Patos",
	"Lagoa Dourada",
	"Lagoa Formosa",
	"Lagoa Grande",
	"Lagoa Santa",
	"Lagoinha",
	"Laje do Muriaé",
	"Lajinha",
	"Lambari",
	"Lamim",
	"Laranja da Terra",
	"Laranjal",
	"Laranjal Paulista",
	"Lassance",
	"Lavínia",
	"Lavras",
	"Lavrinhas",
	"Leandro Ferreira",
	"Leme",
	"Leme do Prado",
	"Lençóis Paulista",
	"Leopoldina",
	"Liberdade",
	"Lima Duarte",
	"Limeira",
	"Limeira do Oeste",
	"Lindóia",
	"Linhares",
	"Lins",
	"Lontra",
	"Lorena",
	"Lourdes",
	"Louveira",
	"Lucélia",
	"Lucianópolis",
	"Luís Antônio",
	"Luisburgo",
	"Luislândia",
	"Luiziânia",
	"Luminárias",
	"Lupércio",
	"Lutécia",
	"Luz",
	"Macaé",
	"Macatuba",
	"Macaubal",
	"Macedônia",
	"Machacalis",
	"Machado",
	"Macuco",
	"Madre de Deus de Minas",
	"Magda",
	"Magé",
	"Mairinque",
	"Mairiporã",
	"Malacacheta",
	"Mamonas",
	"Manduri",
	"Manga",
	"Mangaratiba",
	"Manhuaçu",
	"Manhumirim",
	"Mantena",
	"Mantenópolis",
	"Mar de Espanha",
	"Marabá Paulista",
	"Maracaí",
	"Marapoama",
	"Marataízes",
	"Maravilhas",
	"Marechal Floriano",
	"Maria da Fé",
	"Mariana",
	"Mariápolis",
	"Maricá",
	"Marilac",
	"Marilândia",
	"Marília",
	"Marinópolis",
	"Mário Campos",
	"Maripá de Minas",
	"Marliéria",
	"Marmelópolis",
	"Martinho Campos",
	"Martinópolis",
	"Martins Soares",
	"Mata Verde",
	"Matão",
	"Materlândia",
	"Mateus Leme",
	"Mathias Lobato",
	"Matias Barbosa",
	"Matias Cardoso",
	"Matipó",
	"Mato Verde",
	"Matozinhos",
	"Matutina",
	"Mauá",
	"Medeiros",
	"Medina",
	"Mendes",
	"Mendes Pimentel",
	"Mendonça",
	"Mercês",
	"Meridiano",
	"Mesópolis",
	"Mesquita",
	"Miguel Pereira",
	"Miguelópolis",
	"Mimoso do Sul",
	"Minas Novas",
	"Minduri",
	"Mineiros do Tietê",
	"Mira Estrela",
	"Mirabela",
	"Miracatu",
	"Miracema",
	"Miradouro",
	"Miraí",
	"Mirandópolis",
	"Mirante do Paranapanema",
	"Mirassol",
	"Mirassolândia",
	"Miravânia",
	"Mococa",
	"Moeda",
	"Moema",
	"Mogi das Cruzes",
	"Mogi Guaçu",
	"Mogi Mirim",
	"Mombuca",
	"Monções",
	"Mongaguá",
	"Monjolos",
	"Monsenhor Paulo",
	"Montalvânia",
	"Montanha",
	"Monte Alegre de Minas",
	"Monte Alegre do Sul",
	"Monte Alto",
	"Monte Aprazível",
	"Monte Azul",
	"Monte Azul Paulista",
	"Monte Belo",
	"Monte Carmelo",
	"Monte Castelo",
	"Monte Formoso",
	"Monte Mor",
	"Monte Santo de Minas",
	"Monte Sião",
	"Monteiro Lobato",
	"Montes Claros",
	"Montezuma",
	"Morada Nova de Minas",
	"Morro Agudo",
	"Morro da Garça",
	"Morro do Pilar",
	"Morungaba",
	"Motuca",
	"Mucurici",
	"Munhoz",
	"Muniz Freire",
	"Muqui",
	"Muriaé",
	"Murutinga do Sul",
	"Mutum",
	"Muzambinho",
	"Nacip Raydan",
	"Nantes",
	"Nanuque",
	"Naque",
	"Narandiba",
	"Natalândia",
	"Natércia",
	"Natividade",
	"Natividade da Serra",
	"Nazaré Paulista",
	"Nazareno",
	"Nepomuceno",
	"Neves Paulista",
	"Nhandeara",
	"Nilópolis",
	"Ninheira",
	"Nipoã",
	"Niterói",
	"Nova Aliança",
	"Nova Belém",
	"Nova Campina",
	"Nova Canaã Paulista",
	"Nova Castilho",
	"Nova Era",
	"Nova Europa",
	"Nova Friburgo",
	"Nova Granada",
	"Nova Guataporanga",
	"Nova Iguaçu",
	"Nova Independência",
	"Nova Lima",
	"Nova Luzitânia",
	"Nova Módica",
	"Nova Odessa",
	"Nova Ponte",
	"Nova Porteirinha",
	"Nova Resende",
	"Nova Serrana",
	"Nova União",
	"Nova Venécia",
	"Novais",
	"Novo Cruzeiro",
	"Novo Horizonte",
	"Novo Oriente de Minas",
	"Novorizonte",
	"Nuporanga",
	"Ocauçu",
	"Olaria",
	"Óleo",
	"Olhos-d'Água",
	"Olímpia",
	"Olímpio Noronha",
	"Oliveira",
	"Oliveira Fortes",
	"Onça de Pitangui",
	"Onda Verde",
	"Oratórios",
	"Oriente",
	"Orindiúva",
	"Orizânia",
	"Orlândia",
	"Osasco",
	"Oscar Bressane",
	"Osvaldo Cruz",
	"Ourinhos",
	"Ouro Branco",
	"Ouro Fino",
	"Ouro Preto",
	"Ouro Verde",
	"Ouro Verde de Minas",
	"Ouroeste",
	"Pacaembu",
	"Padre Carvalho",
	"Padre Paraíso",
	"Pai Pedro",
	"Paineiras",
	"Pains",
	"Paiva",
	"Palestina",
	"Palma",
	"Palmares Paulista",
	"Palmeira d'Oeste",
	"Palmital",
	"Palmópolis",
	"Pancas",
	"Panorama",
	"Papagaios",
	"Pará de Minas",
	"Paracambi",
	"Paracatu",
	"Paraguaçu",
	"Paraguaçu Paulista",
	"Paraíba do Sul",
	"Paraibuna",
	"Paraíso",
	"Paraisópolis",
	"Paranapanema",
	"Paranapuã",
	"Paraopeba",
	"Parapuã",
	"Paraty",
	"Pardinho",
	"Pariquera-Açu",
	"Parisi",
	"Passa Quatro",
	"Passa Tempo",
	"Passa Vinte",
	"Passabém",
	"Passos",
	"Patis",
	"Patos de Minas",
	"Patrocínio",
	"Patrocínio do Muriaé",
	"Patrocínio Paulista",
	"Paty do Alferes",
	"Paula Cândido",
	"Paulicéia",
	"Paulínia",
	"Paulistânia",
	"Paulistas",
	"Paulo de Faria",
	"Pavão",
	"Peçanha",
	"Pederneiras",
	"Pedra Azul",
	"Pedra Bela",
	"Pedra Bonita",
	"Pedra do Anta",
	"Pedra do Indaiá",
	"Pedra Dourada",
	"Pedralva",
	"Pedranópolis",
	"Pedras de Maria da Cruz",
	"Pedregulho",
	"Pedreira",
	"Pedrinhas Paulista",
	"Pedrinópolis",
	"Pedro Canário",
	"Pedro de Toledo",
	"Pedro Leopoldo",
	"Pedro Teixeira",
	"Penápolis",
	"Pequeri",
	"Pequi",
	"Perdigão",
	"Perdizes",
	"Perdões",
	"Pereira Barreto",
	"Pereiras",
	"Periquito",
	"Peruíbe",
	"Pescador",
	"Petrópolis",
	"Piacatu",
	"Piau",
	"Piedade",
	"Piedade de Caratinga",
	"Piedade de Ponte Nova",
	"Piedade do Rio Grande",
	"Piedade dos Gerais",
	"Pilar do Sul",
	"Pimenta",
	"Pindamonhangaba",
	"Pindorama",
	"Pingo-d'Água",
	"Pinhalzinho",
	"Pinheiral",
	"Pinheiros",
	"Pintópolis",
	"Piquerobi",
	"Piquete",
	"Piracaia",
	"Piracema",
	"Piracicaba",
	"Piraí",
	"Piraju",
	"Pirajuba",
	"Pirajuí",
	"Piranga",
	"Pirangi",
	"Piranguçu",
	"Piranguinho",
	"Pirapetinga",
	"Pirapora",
	"Pirapora do Bom Jesus",
	"Pirapozinho",
	"Pirassununga",
	"Piratininga",
	"Piraúba",
	"Pitangueiras",
	"Pitangui",
	"Piúma",
	"Piumhi",
	"Planalto",
	"Planura",
	"Platina",
	"Poá",
	"Poço Fundo",
	"Poços de Caldas",
	"Pocrane",
	"Poloni",
	"Pompéia",
	"Pompéu",
	"Pongaí",
	"Pontal",
	"Pontalinda",
	"Ponte Nova",
	"Pontes Gestal",
	"Ponto Belo",
	"Ponto Chique",
	"Ponto dos Volantes",
	"Populina",
	"Porangaba",
	"Porciúncula",
	"Porteirinha",
	"Porto Feliz",
	"Porto Ferreira",
	"Porto Firme",
	"Porto Real",
	"Poté",
	"Potim",
	"Potirendaba",
	"Pouso Alegre",
	"Pouso Alto",
	"Pracinha",
	"Pradópolis",
	"Prados",
	"Praia Grande",
	"Prata",
	"Pratânia",
	"Pratápolis",
	"Pratinha",
	"Presidente Alves",
	"Presidente Bernardes",
	"Presidente Epitácio",
	"Presidente Juscelino",
	"Presidente Kennedy",
	"Presidente Kubitschek",
	"Presidente Olegário",
	"Presidente Prudente",
	"Presidente Venceslau",
	"Promissão",
	"Prudente de Morais",
	"Quadra",
	"Quartel Geral",
	"Quatá",
	"Quatis",
	"Queimados",
	"Queiroz",
	"Queluz",
	"Queluzito",
	"Quintana",
	"Quissamã",
	"Rafard",
	"Rancharia",
	"Raposos",
	"Raul Soares",
	"Recreio",
	"Redenção da Serra",
	"Reduto",
	"Regente Feijó",
	"Reginópolis",
	"Registro",
	"Resende",
	"Resende Costa",
	"Resplendor",
	"Ressaquinha",
	"Restinga",
	"Riachinho",
	"Riacho dos Machados",
	"Ribeira",
	"Ribeirão Bonito",
	"Ribeirão Branco",
	"Ribeirão Corrente",
	"Ribeirão das Neves",
	"Ribeirão do Sul",
	"Ribeirão dos Índios",
	"Ribeirão Grande",
	"Ribeirão Pires",
	"Ribeirão Preto",
	"Ribeirão Vermelho",
	"Rifaina",
	"Rincão",
	"Rinópolis",
	"Rio Acima",
	"Rio Bananal",
	"Rio Bonito",
	"Rio Casca",
	"Rio Claro",
	"Rio das Flores",
	"Rio das Ostras",
	"Rio das Pedras",
	"Rio de Janeiro",
	"Rio do Prado",
	"Rio Doce",
	"Rio Espera",
	"Rio Grande da Serra",
	"Rio Manso",
	"Rio Novo",
	"Rio Novo do Sul",
	"Rio Paranaíba",
	"Rio Pardo de Minas",
	"Rio Piracicaba",
	"Rio Pomba",
	"Rio Preto",
	"Rio Vermelho",
	"Riolândia",
	"Ritápolis",
	"Riversul",
	"Rochedo de Minas",
	"Rodeiro",
	"Romaria",
	"Rosana",
	"Rosário da Limeira",
	"Roseira",
	"Rubelita",
	"Rubiácea",
	"Rubim",
	"Rubinéia",
	"Sabará",
	"Sabino",
	"Sabinópolis",
	"Sacramento",
	"Sagres",
	"Sales",
	"Sales Oliveira",
	"Salesópolis",
	"Salinas",
	"Salmourão",
	"Saltinho",
	"Salto",
	"Salto da Divisa",
	"Salto de Pirapora",
	"Salto Grande",
	"Sandovalina",
	"Santa Adélia",
	"Santa Albertina",
	"Santa Bárbara",
	"Santa Bárbara d'Oeste",
	"Santa Bárbara do Leste",
	"Santa Bárbara do Monte Verde",
	"Santa Bárbara do Tugúrio",
	"Santa Branca",
	"Santa Clara d'Oeste",
	"Santa Cruz da Conceição",
	"Santa Cruz da Esperança",
	"Santa Cruz das Palmeiras",
	"Santa Cruz de Minas",
	"Santa Cruz de Salinas",
	"Santa Cruz do Escalvado",
	"Santa Cruz do Rio Pardo",
	"Santa Efigênia de Minas",
	"Santa Ernestina",
	"Santa Fé de Minas",
	"Santa Fé do Sul",
	"Santa Gertrudes",
	"Santa Helena de Minas",
	"Santa Isabel",
	"Santa Juliana",
	"Santa Leopoldina",
	"Santa Lúcia",
	"Santa Luzia",
	"Santa Margarida",
	"Santa Maria da Serra",
	"Santa Maria de Itabira",
	"Santa Maria de Jetibá",
	"Santa Maria do Salto",
	"Santa Maria do Suaçuí",
	"Santa Maria Madalena",
	"Santa Mercedes",
	"Santa Rita d'Oeste",
	"Santa Rita de Caldas",
	"Santa Rita de Ibitipoca",
	"Santa Rita de Jacutinga",
	"Santa Rita de Minas",
	"Santa Rita do Itueto",
	"Santa Rita do Passa Quatro",
	"Santa Rita do Sapucaí",
	"Santa Rosa da Serra",
	"Santa Rosa de Viterbo",
	"Santa Salete",
	"Santa Teresa",
	"Santa Vitória",
	"Santana da Ponte Pensa",
	"Santana da Vargem",
	"Santana de Cataguases",
	"Santana de Parnaíba",
	"Santana de Pirapama",
	"Santana do Deserto",
	"Santana do Garambéu",
	"Santana do Jacaré",
	"Santana do Manhuaçu",
	"Santana do Paraíso",
	"Santana do Riacho",
	"Santana dos Montes",
	"Santo Anastácio",
	"Santo André",
	"Santo Antônio da Alegria",
	"Santo Antônio de Pádua",
	"Santo Antônio de Posse",
	"Santo Antônio do Amparo",
	"Santo Antônio do Aracanguá",
	"Santo Antônio do Aventureiro",
	"Santo Antônio do Grama",
	"Santo Antônio do Itambé",
	"Santo Antônio do Jacinto",
	"Santo Antônio do Jardim",
	"Santo Antônio do Monte",
	"Santo Antônio do Pinhal",
	"Santo Antônio do Retiro",
	"Santo Antônio do Rio Abaixo",
	"Santo Expedito",
	"Santo Hipólito",
	"Santópolis do Aguapeí",
	"Santos",
	"Santos Dumont",
	"São Bento Abade",
	"São Bento do Sapucaí",
	"São Bernardo do Campo",
	"São Brás do Suaçuí",
	"São Caetano do Sul",
	"São Carlos",
	"São Domingos das Dores",
	"São Domingos do Norte",
	"São Domingos do Prata",
	"São Félix de Minas",
	"São Fidélis",
	"São Francisco",
	"São Francisco de Itabapoana",
	"São Francisco de Paula",
	"São Francisco de Sales",
	"São Francisco do Glória",
	"São Gabriel da Palha",
	"São Geraldo",
	"São Geraldo da Piedade",
	"São Geraldo do Baixio",
	"São Gonçalo",
	"São Gonçalo do Abaeté",
	"São Gonçalo do Pará",
	"São Gonçalo do Rio Abaixo",
	"São Gonçalo do Rio Preto",
	"São Gonçalo do Sapucaí",
	"São Gotardo",
	"São João Batista do Glória",
	"São João da Barra",
	"São João da Boa Vista",
	"São João da Lagoa",
	"São João da Mata",
	"São João da Ponte",
	"São João das Duas Pontes",
	"São João das Missões",
	"São João de Iracema",
	"São João de Meriti",
	"São João del Rei",
	"São João do Manhuaçu",
	"São João do Manteninha",
	"São João do Oriente",
	"São João do Pacuí",
	"São João do Paraíso",
	"São João do Pau d'Alho",
	"São João Evangelista",
	"São João Nepomuceno",
	"São Joaquim da Barra",
	"São Joaquim de Bicas",
	"São José da Barra",
	"São José da Bela Vista",
	"São José da Lapa",
	"São José da Safira",
	"São José da Varginha",
	"São José de Ubá",
	"São José do Alegre",
	"São José do Barreiro",
	"São José do Calçado",
	"São José do Divino",
	"São José do Goiabal",
	"São José do Jacuri",
	"São José do Mantimento",
	"São José do Rio Pardo",
	"São José do Rio Preto",
	"São José do Vale do Rio Preto",
	"São José dos Campos",
	"São Lourenço",
	"São Lourenço da Serra",
	"São Luiz do Paraitinga",
	"São Manuel",
	"São Mateus",
	"São Miguel Arcanjo",
	"São Miguel do Anta",
	"São Paulo",
	"São Pedro",
	"São Pedro da Aldeia",
	"São Pedro da União",
	"São Pedro do Suaçuí",
	"São Pedro do Turvo",
	"São Pedro dos Ferros",
	"São Romão",
	"São Roque",
	"São Roque de Minas",
	"São Roque do Canaã",
	"São Sebastião",
	"São Sebastião da Bela Vista",
	"São Sebastião da Grama",
	"São Sebastião da Vargem Alegre",
	"São Sebastião do Alto",
	"São Sebastião do Anta",
	"São Sebastião do Maranhão",
	"São Sebastião do Oeste",
	"São Sebastião do Paraíso",
	"São Sebastião do Rio Preto",
	"São Sebastião do Rio Verde",
	"São Simão",
	"São Tiago",
	"São Tomás de Aquino",
	"São Tomé das Letras",
	"São Vicente",
	"São Vicente de Minas",
	"Sapucaí-Mirim",
	"Sapucaia",
	"Saquarema",
	"Sarapuí",
	"Sardoá",
	"Sarutaiá",
	"Sarzedo",
	"Sebastianópolis do Sul",
	"Sem-Peixe",
	"Senador Amaral",
	"Senador Cortes",
	"Senador Firmino",
	"Senador José Bento",
	"Senador Modestino Gonçalves",
	"Senhora de Oliveira",
	"Senhora do Porto",
	"Senhora dos Remédios",
	"Sericita",
	"Seritinga",
	"Seropédica",
	"Serra",
	"Serra Azul",
	"Serra Azul de Minas",
	"Serra da Saudade",
	"Serra do Salitre",
	"Serra dos Aimorés",
	"Serra Negra",
	"Serrana",
	"Serrania",
	"Serranópolis de Minas",
	"Serranos",
	"Serro",
	"Sertãozinho",
	"Sete Barras",
	"Sete Lagoas",
	"Setubinha",
	"Severínia",
	"Silva Jardim",
	"Silveirânia",
	"Silveiras",
	"Silvianópolis",
	"Simão Pereira",
	"Simonésia",
	"Sobrália",
	"Socorro",
	"Soledade de Minas",
	"Sooretama",
	"Sorocaba",
	"Sud Mennucci",
	"Sumaré",
	"Sumidouro",
	"Suzanápolis",
	"Suzano",
	"Tabapuã",
	"Tabatinga",
	"Taboão da Serra",
	"Tabuleiro",
	"Taciba",
	"Taguaí",
	"Taiaçu",
	"Taiobeiras",
	"Taiúva",
	"Tambaú",
	"Tanabi",
	"Tanguá",
	"Taparuba",
	"Tapira",
	"Tapiraí",
	"Tapiratiba",
	"Taquaraçu de Minas",
	"Taquaral",
	"Taquaritinga",
	"Taquarituba",
	"Taquarivaí",
	"Tarabai",
	"Tarumã",
	"Tarumirim",
	"Tatuí",
	"Taubaté",
	"Teixeiras",
	"Tejupá",
	"Teodoro Sampaio",
	"Teófilo Otoni",
	"Teresópolis",
	"Terra Roxa",
	"Tietê",
	"Timburi",
	"Timóteo",
	"Tiradentes",
	"Tiros",
	"Tocantins",
	"Tocos do Moji",
	"Toledo",
	"Tombos",
	"Torre de Pedra",
	"Torrinha",
	"Trabiju",
	"Trajano de Moraes",
	"Tremembé",
	"Três Corações",
	"Três Fronteiras",
	"Três Marias",
	"Três Pontas",
	"Três Rios",
	"Tuiuti",
	"Tumiritinga",
	"Tupã",
	"Tupaciguara",
	"Tupi Paulista",
	"Turiúba",
	"Turmalina",
	"Turvolândia",
	"Ubá",
	"Ubaí",
	"Ubaporanga",
	"Ubarana",
	"Ubatuba",
	"Uberaba",
	"Uberlândia",
	"Ubirajara",
	"Uchoa",
	"Umburatiba",
	"Unaí",
	"União de Minas",
	"União Paulista",
	"Urânia",
	"Uru",
	"Uruana de Minas",
	"Urucânia",
	"Urucuia",
	"Urupês",
	"Valença",
	"Valentim Gentil",
	"Valinhos",
	"Valparaíso",
	"Vargem",
	"Vargem Alegre",
	"Vargem Alta",
	"Vargem Bonita",
	"Vargem Grande do Rio Pardo",
	"Vargem Grande do Sul",
	"Vargem Grande Paulista",
	"Varginha",
	"Varjão de Minas",
	"Varre-Sai",
	"Várzea da Palma",
	"Várzea Paulista",
	"Varzelândia",
	"Vassouras",
	"Vazante",
	"Venda Nova do Imigrante",
	"Vera Cruz",
	"Verdelândia",
	"Veredinha",
	"Veríssimo",
	"Vermelho Novo",
	"Vespasiano",
	"Viana",
	"Viçosa",
	"Vieiras",
	"Vila Pavão",
	"Vila Valério",
	"Vila Velha",
	"Vinhedo",
	"Viradouro",
	"Virgem da Lapa",
	"Virgínia",
	"Virginópolis",
	"Virgolândia",
	"Visconde do Rio Branco",
	"Vista Alegre do Alto",
	"Vitória",
	"Vitória Brasil",
	"Volta Grande",
	"Volta Redonda",
	"Votorantim",
	"Votuporanga",
	"Wenceslau Braz",
	"Zacarias"
}
