-- Source: IBGE (servicodados.ibge.gov.br/api/v1/localidades/municipios)
return {
	"Abadia de Goiás",
	"Abadiânia",
	"Acorizal",
	"Acreúna",
	"Adelândia",
	"Água Boa",
	"Água Clara",
	"Água Fria de Goiás",
	"Água Limpa",
	"Águas Lindas de Goiás",
	"Alcinópolis",
	"Alexânia",
	"Aloândia",
	"Alta Floresta",
	"Alto Araguaia",
	"Alto Boa Vista",
	"Alto Garças",
	"Alto Horizonte",
	"Alto Paraguai",
	"Alto Paraíso de Goiás",
	"Alto Taquari",
	"Alvorada do Norte",
	"Amambai",
	"Amaralina",
	"Americano do Brasil",
	"Amorinópolis",
	"Anápolis",
	"Anastácio",
	"Anaurilândia",
	"Angélica",
	"Anhanguera",
	"Anicuns",
	"Antônio João",
	"Aparecida de Goiânia",
	"Aparecida do Rio Doce",
	"Aparecida do Taboado",
	"Apiacás",
	"Aporé",
	"Aquidauana",
	"Araçu",
	"Aragarças",
	"Aragoiânia",
	"Araguaiana",
	"Araguainha",
	"Araguapaz",
	"Aral Moreira",
	"Araputanga",
	"Arenápolis",
	"Arenópolis",
	"Aripuanã",
	"Aruanã",
	"Aurilândia",
	"Avelinópolis",
	"Baliza",
	"Bandeirantes",
	"Barão de Melgaço",
	"Barra do Bugres",
	"Barra do Garças",
	"Barro Alto",
	"Bataguassu",
	"Batayporã",
	"Bela Vista",
	"Bela Vista de Goiás",
	"Boa Esperança do Norte",
	"Bodoquena",
	"Bom Jardim de Goiás",
	"Bom Jesus de Goiás",
	"Bom Jesus do Araguaia",
	"Bonfinópolis",
	"Bonito",
	"Bonópolis",
	"Brasilândia",
	"Brasília",
	"Brasnorte",
	"Brazabrantes",
	"Britânia",
	"Buriti Alegre",
	"Buriti de Goiás",
	"Buritinópolis",
	"Caarapó",
	"Cabeceiras",
	"Cáceres",
	"Cachoeira Alta",
	"Cachoeira de Goiás",
	"Cachoeira Dourada",
	"Caçu",
	"Caiapônia",
	"Caldas Novas",
	"Caldazinha",
	"Camapuã",
	"Campestre de Goiás",
	"Campinaçu",
	"Campinápolis",
	"Campinorte",
	"Campo Alegre de Goiás",
	"Campo Grande",
	"Campo Limpo de Goiás",
	"Campo Novo do Parecis",
	"Campo Verde",
	"Campos Belos",
	"Campos de Júlio",
	"Campos Verdes",
	"Canabrava do Norte",
	"Canarana",
	"Caracol",
	"Carlinda",
	"Carmo do Rio Verde",
	"Cassilândia",
	"Castanheira",
	"Castelândia",
	"Catalão",
	"Caturaí",
	"Cavalcante",
	"Ceres",
	"Cezarina",
	"Chapada dos Guimarães",
	"Chapadão do Céu",
	"Chapadão do Sul",
	"Cidade Ocidental",
	"Cláudia",
	"Cocalinho",
	"Cocalzinho de Goiás",
	"Colíder",
	"Colinas do Sul",
	"Colniza",
	"Comodoro",
	"Confresa",
	"Conquista D'Oeste",
	"Corguinho",
	"Coronel Sapucaia",
	"Córrego do Ouro",
	"Corumbá",
	"Corumbá de Goiás",
	"Corumbaíba",
	"Costa Rica",
	"Cotriguaçu",
	"Coxim",
	"Cristalina",
	"Cristianópolis",
	"Crixás",
	"Cromínia",
	"Cuiabá",
	"Cumari",
	"Curvelândia",
	"Damianópolis",
	"Damolândia",
	"Davinópolis",
	"Denise",
	"Deodápolis",
	"Diamantino",
	"Diorama",
	"Divinópolis de Goiás",
	"Dois Irmãos do Buriti",
	"Dom Aquino",
	"Douradina",
	"Dourados",
	"Doverlândia",
	"Edealina",
	"Edéia",
	"Eldorado",
	"Estrela do Norte",
	"Faina",
	"Fátima do Sul",
	"Fazenda Nova",
	"Feliz Natal",
	"Figueirão",
	"Figueirópolis D'Oeste",
	"Firminópolis",
	"Flores de Goiás",
	"Formosa",
	"Formoso",
	"Gameleira de Goiás",
	"Gaúcha do Norte",
	"General Carneiro",
	"Glória D'Oeste",
	"Glória de Dourados",
	"Goianápolis",
	"Goiandira",
	"Goianésia",
	"Goiânia",
	"Goianira",
	"Goiás",
	"Goiatuba",
	"Gouvelândia",
	"Guapó",
	"Guaraíta",
	"Guarani de Goiás",
	"Guarantã do Norte",
	"Guarinos",
	"Guia Lopes da Laguna",
	"Guiratinga",
	"Heitoraí",
	"Hidrolândia",
	"Hidrolina",
	"Iaciara",
	"Iguatemi",
	"Inaciolândia",
	"Indiara",
	"Indiavaí",
	"Inhumas",
	"Inocência",
	"Ipameri",
	"Ipiranga de Goiás",
	"Ipiranga do Norte",
	"Iporá",
	"Israelândia",
	"Itaberaí",
	"Itaguari",
	"Itaguaru",
	"Itajá",
	"Itanhangá",
	"Itapaci",
	"Itapirapuã",
	"Itaporã",
	"Itapuranga",
	"Itaquiraí",
	"Itarumã",
	"Itaúba",
	"Itauçu",
	"Itiquira",
	"Itumbiara",
	"Ivinhema",
	"Ivolândia",
	"Jaciara",
	"Jandaia",
	"Jangada",
	"Japorã",
	"Jaraguá",
	"Jaraguari",
	"Jardim",
	"Jataí",
	"Jateí",
	"Jaupaci",
	"Jauru",
	"Jesúpolis",
	"Joviânia",
	"Juara",
	"Juína",
	"Juruena",
	"Juscimeira",
	"Jussara",
	"Juti",
	"Ladário",
	"Lagoa Santa",
	"Laguna Carapã",
	"Lambari D'Oeste",
	"Leopoldo de Bulhões",
	"Lucas do Rio Verde",
	"Luciara",
	"Luziânia",
	"Mairipotaba",
	"Mambaí",
	"Mara Rosa",
	"Maracaju",
	"Marcelândia",
	"Marzagão",
	"Matrinchã",
	"Matupá",
	"Maurilândia",
	"Mimoso de Goiás",
	"Minaçu",
	"Mineiros",
	"Miranda",
	"Mirassol d'Oeste",
	"Moiporá",
	"Monte Alegre de Goiás",
	"Montes Claros de Goiás",
	"Montividiu",
	"Montividiu do Norte",
	"Morrinhos",
	"Morro Agudo de Goiás",
	"Mossâmedes",
	"Mozarlândia",
	"Mundo Novo",
	"Mutunópolis",
	"Naviraí",
	"Nazário",
	"Nerópolis",
	"Nioaque",
	"Niquelândia",
	"Nobres",
	"Nortelândia",
	"Nossa Senhora do Livramento",
	"Nova Alvorada do Sul",
	"Nova América",
	"Nova Andradina",
	"Nova Aurora",
	"Nova Bandeirantes",
	"Nova Brasilândia",
	"Nova Canaã do Norte",
	"Nova Crixás",
	"Nova Glória",
	"Nova Guarita",
	"Nova Iguaçu de Goiás",
	"Nova Lacerda",
	"Nova Marilândia",
	"Nova Maringá",
	"Nova Monte Verde",
	"Nova Mutum",
	"Nova Nazaré",
	"Nova Olímpia",
	"Nova Roma",
	"Nova Santa Helena",
	"Nova Ubiratã",
	"Nova Veneza",
	"Nova Xavantina",
	"Novo Brasil",
	"Novo Gama",
	"Novo Horizonte do Norte",
	"Novo Horizonte do Sul",
	"Novo Mundo",
	"Novo Planalto",
	"Novo Santo Antônio",
	"Novo São Joaquim",
	"Orizona",
	"Ouro Verde de Goiás",
	"Ouvidor",
	"Padre Bernardo",
	"Palestina de Goiás",
	"Palmeiras de Goiás",
	"Palmelo",
	"Palminópolis",
	"Panamá",
	"Paraíso das Águas",
	"Paranaíba",
	"Paranaiguara",
	"Paranaíta",
	"Paranatinga",
	"Paranhos",
	"Paraúna",
	"Pedra Preta",
	"Pedro Gomes",
	"Peixoto de Azevedo",
	"Perolândia",
	"Petrolina de Goiás",
	"Pilar de Goiás",
	"Piracanjuba",
	"Piranhas",
	"Pirenópolis",
	"Pires do Rio",
	"Planaltina",
	"Planalto da Serra",
	"Poconé",
	"Ponta Porã",
	"Pontal do Araguaia",
	"Pontalina",
	"Ponte Branca",
	"Pontes e Lacerda",
	"Porangatu",
	"Porteirão",
	"Portelândia",
	"Porto Alegre do Norte",
	"Porto dos Gaúchos",
	"Porto Esperidião",
	"Porto Estrela",
	"Porto Murtinho",
	"Posse",
	"Poxoréu",
	"Primavera do Leste",
	"Professor Jamil",
	"Querência",
	"Quirinópolis",
	"Reserva do Cabaçal",
	"Rialma",
	"Rianápolis",
	"Ribas do Rio Pardo",
	"Ribeirão Cascalheira",
	"Ribeirãozinho",
	"Rio Branco",
	"Rio Brilhante",
	"Rio Negro",
	"Rio Quente",
	"Rio Verde",
	"Rio Verde de Mato Grosso",
	"Rochedo",
	"Rondolândia",
	"Rondonópolis",
	"Rosário Oeste",
	"Rubiataba",
	"Salto do Céu",
	"Sanclerlândia",
	"Santa Bárbara de Goiás",
	"Santa Carmem",
	"Santa Cruz de Goiás",
	"Santa Cruz do Xingu",
	"Santa Fé de Goiás",
	"Santa Helena de Goiás",
	"Santa Isabel",
	"Santa Rita do Araguaia",
	"Santa Rita do Novo Destino",
	"Santa Rita do Pardo",
	"Santa Rita do Trivelato",
	"Santa Rosa de Goiás",
	"Santa Tereza de Goiás",
	"Santa Terezinha",
	"Santa Terezinha de Goiás",
	"Santo Afonso",
	"Santo Antônio da Barra",
	"Santo Antônio de Goiás",
	"Santo Antônio de Leverger",
	"Santo Antônio do Descoberto",
	"Santo Antônio do Leste",
	"São Domingos",
	"São Félix do Araguaia",
	"São Francisco de Goiás",
	"São Gabriel do Oeste",
	"São João d'Aliança",
	"São João da Paraúna",
	"São José do Povo",
	"São José do Rio Claro",
	"São José do Xingu",
	"São José dos Quatro Marcos",
	"São Luís de Montes Belos",
	"São Luiz do Norte",
	"São Miguel do Araguaia",
	"São Miguel do Passa Quatro",
	"São Patrício",
	"São Pedro da Cipa",
	"São Simão",
	"Sapezal",
	"Selvíria",
	"Senador Canedo",
	"Serra Nova Dourada",
	"Serranópolis",
	"Sete Quedas",
	"Sidrolândia",
	"Silvânia",
	"Simolândia",
	"Sinop",
	"Sítio d'Abadia",
	"Sonora",
	"Sorriso",
	"Tabaporã",
	"Tacuru",
	"Tangará da Serra",
	"Tapurah",
	"Taquaral de Goiás",
	"Taquarussu",
	"Terenos",
	"Teresina de Goiás",
	"Terezópolis de Goiás",
	"Terra Nova do Norte",
	"Tesouro",
	"Torixoréu",
	"Três Lagoas",
	"Três Ranchos",
	"Trindade",
	"Trombas",
	"Turvânia",
	"Turvelândia",
	"Uirapuru",
	"União do Sul",
	"Uruaçu",
	"Uruana",
	"Urutaí",
	"Vale de São Domingos",
	"Valparaíso de Goiás",
	"Varjão",
	"Várzea Grande",
	"Vera",
	"Vianópolis",
	"Vicentina",
	"Vicentinópolis",
	"Vila Bela da Santíssima Trindade",
	"Vila Boa",
	"Vila Propício",
	"Vila Rica"
}
