-- Source: IBGE (servicodados.ibge.gov.br/api/v1/localidades/municipios)
return {
	"Abatiá",
	"Abdon Batista",
	"Abelardo Luz",
	"Aceguá",
	"Adrianópolis",
	"Agrolândia",
	"Agronômica",
	"Água Doce",
	"Água Santa",
	"Águas de Chapecó",
	"Águas Frias",
	"Águas Mornas",
	"Agudo",
	"Agudos do Sul",
	"Ajuricaba",
	"Alecrim",
	"Alegrete",
	"Alegria",
	"Alfredo Wagner",
	"Almirante Tamandaré",
	"Almirante Tamandaré do Sul",
	"Alpestre",
	"Altamira do Paraná",
	"Alto Alegre",
	"Alto Bela Vista",
	"Alto Feliz",
	"Alto Paraíso",
	"Alto Paraná",
	"Alto Piquiri",
	"Altônia",
	"Alvorada",
	"Alvorada do Sul",
	"Amaporã",
	"Amaral Ferrador",
	"Ametista do Sul",
	"Ampére",
	"Anahy",
	"Anchieta",
	"Andirá",
	"André da Rocha",
	"Angelina",
	"Ângulo",
	"Anita Garibaldi",
	"Anitápolis",
	"Anta Gorda",
	"Antonina",
	"Antônio Carlos",
	"Antônio Olinto",
	"Antônio Prado",
	"Apiúna",
	"Apucarana",
	"Arabutã",
	"Arambaré",
	"Arapongas",
	"Arapoti",
	"Arapuã",
	"Araquari",
	"Araranguá",
	"Araricá",
	"Araruna",
	"Aratiba",
	"Araucária",
	"Ariranha do Ivaí",
	"Armazém",
	"Arroio do Meio",
	"Arroio do Padre",
	"Arroio do Sal",
	"Arroio do Tigre",
	"Arroio dos Ratos",
	"Arroio Grande",
	"Arroio Trinta",
	"Arvoredo",
	"Arvorezinha",
	"Ascurra",
	"Assaí",
	"Assis Chateaubriand",
	"Astorga",
	"Atalaia",
	"Atalanta",
	"Augusto Pestana",
	"Áurea",
	"Aurora",
	"Bagé",
	"Balneário Arroio do Silva",
	"Balneário Barra do Sul",
	"Balneário Camboriú",
	"Balneário Gaivota",
	"Balneário Piçarras",
	"Balneário Pinhal",
	"Balneário Rincão",
	"Balsa Nova",
	"Bandeirante",
	"Bandeirantes",
	"Barão",
	"Barão de Cotegipe",
	"Barão do Triunfo",
	"Barbosa Ferraz",
	"Barra Bonita",
	"Barra do Guarita",
	"Barra do Jacaré",
	"Barra do Quaraí",
	"Barra do Ribeiro",
	"Barra do Rio Azul",
	"Barra Funda",
	"Barra Velha",
	"Barracão",
	"Barros Cassal",
	"Bela Vista da Caroba",
	"Bela Vista do Paraíso",
	"Bela Vista do Toldo",
	"Belmonte",
	"Benedito Novo",
	"Benjamin Constant do Sul",
	"Bento Gonçalves",
	"Biguaçu",
	"Bituruna",
	"Blumenau",
	"Boa Esperança",
	"Boa Esperança do Iguaçu",
	"Boa Ventura de São Roque",
	"Boa Vista da Aparecida",
	"Boa Vista das Missões",
	"Boa Vista do Buricá",
	"Boa Vista do Cadeado",
	"Boa Vista do Incra",
	"Boa Vista do Sul",
	"Bocaina do Sul",
	"Bocaiúva do Sul",
	"Bom Jardim da Serra",
	"Bom Jesus",
	"Bom Jesus do Oeste",
	"Bom Jesus do Sul",
	"Bom Princípio",
	"Bom Progresso",
	"Bom Retiro",
	"Bom Retiro do Sul",
	"Bom Sucesso",
	"Bom Sucesso do Sul",
	"Bombinhas",
	"Boqueirão do Leão",
	"Borrazópolis",
	"Bossoroca",
	"Botuverá",
	"Bozano",
	"Braço do Norte",
	"Braço do Trombudo",
	"Braga",
	"Braganey",
	"Brasilândia do Sul",
	"Brochier",
	"Brunópolis",
	"Brusque",
	"Butiá",
	"Caçador",
	"Caçapava do Sul",
	"Cacequi",
	"Cachoeira do Sul",
	"Cachoeirinha",
	"Cacique Doble",
	"Cafeara",
	"Cafelândia",
	"Cafezal do Sul",
	"Caibaté",
	"Caibi",
	"Caiçara",
	"Califórnia",
	"Calmon",
	"Camaquã",
	"Camargo",
	"Cambará",
	"Cambará do Sul",
	"Cambé",
	"Cambira",
	"Camboriú",
	"Campestre da Serra",
	"Campina da Lagoa",
	"Campina das Missões",
	"Campina do Simão",
	"Campina Grande do Sul",
	"Campinas do Sul",
	"Campo Alegre",
	"Campo Belo do Sul",
	"Campo Bom",
	"Campo Bonito",
	"Campo do Tenente",
	"Campo Erê",
	"Campo Largo",
	"Campo Magro",
	"Campo Mourão",
	"Campo Novo",
	"Campos Borges",
	"Campos Novos",
	"Candelária",
	"Cândido de Abreu",
	"Cândido Godói",
	"Candiota",
	"Candói",
	"Canela",
	"Canelinha",
	"Canguçu",
	"Canoas",
	"Canoinhas",
	"Cantagalo",
	"Canudos do Vale",
	"Capanema",
	"Capão Alto",
	"Capão Bonito do Sul",
	"Capão da Canoa",
	"Capão do Cipó",
	"Capão do Leão",
	"Capela de Santana",
	"Capinzal",
	"Capitão",
	"Capitão Leônidas Marques",
	"Capivari de Baixo",
	"Capivari do Sul",
	"Caraá",
	"Carambeí",
	"Carazinho",
	"Carlópolis",
	"Carlos Barbosa",
	"Carlos Gomes",
	"Casca",
	"Cascavel",
	"Caseiros",
	"Castro",
	"Catanduvas",
	"Catuípe",
	"Caxambu do Sul",
	"Caxias do Sul",
	"Celso Ramos",
	"Centenário",
	"Centenário do Sul",
	"Cerrito",
	"Cerro Azul",
	"Cerro Branco",
	"Cerro Grande",
	"Cerro Grande do Sul",
	"Cerro Largo",
	"Cerro Negro",
	"Céu Azul",
	"Chapada",
	"Chapadão do Lageado",
	"Chapecó",
	"Charqueadas",
	"Charrua",
	"Chiapetta",
	"Chopinzinho",
	"Chuí",
	"Chuvisca",
	"Cianorte",
	"Cidade Gaúcha",
	"Cidreira",
	"Ciríaco",
	"Clevelândia",
	"Cocal do Sul",
	"Colinas",
	"Colombo",
	"Colorado",
	"Concórdia",
	"Condor",
	"Congonhinhas",
	"Conselheiro Mairinck",
	"Constantina",
	"Contenda",
	"Coqueiro Baixo",
	"Coqueiros do Sul",
	"Corbélia",
	"Cordilheira Alta",
	"Cornélio Procópio",
	"Coronel Barros",
	"Coronel Bicaco",
	"Coronel Domingos Soares",
	"Coronel Freitas",
	"Coronel Martins",
	"Coronel Pilar",
	"Coronel Vivida",
	"Correia Pinto",
	"Corumbataí do Sul",
	"Corupá",
	"Cotiporã",
	"Coxilha",
	"Criciúma",
	"Crissiumal",
	"Cristal",
	"Cristal do Sul",
	"Cruz Alta",
	"Cruz Machado",
	"Cruzaltense",
	"Cruzeiro do Iguaçu",
	"Cruzeiro do Oeste",
	"Cruzeiro do Sul",
	"Cruzmaltina",
	"Cunha Porã",
	"Cunhataí",
	"Curitiba",
	"Curitibanos",
	"Curiúva",
	"David Canabarro",
	"Derrubadas",
	"Descanso",
	"Dezesseis de Novembro",
	"Diamante D'Oeste",
	"Diamante do Norte",
	"Diamante do Sul",
	"Dilermando de Aguiar",
	"Dionísio Cerqueira",
	"Dois Irmãos",
	"Dois Irmãos das Missões",
	"Dois Lajeados",
	"Dois Vizinhos",
	"Dom Feliciano",
	"Dom Pedrito",
	"Dom Pedro de Alcântara",
	"Dona Emma",
	"Dona Francisca",
	"Douradina",
	"Doutor Camargo",
	"Doutor Maurício Cardoso",
	"Doutor Pedrinho",
	"Doutor Ricardo",
	"Doutor Ulysses",
	"Eldorado do Sul",
	"Encantado",
	"Encruzilhada do Sul",
	"Enéas Marques",
	"Engenheiro Beltrão",
	"Engenho Velho",
	"Entre Rios",
	"Entre Rios do Oeste",
	"Entre Rios do Sul",
	"Entre-Ijuís",
	"Erebango",
	"Erechim",
	"Ermo",
	"Ernestina",
	"Erval Grande",
	"Erval Seco",
	"Erval Velho",
	"Esmeralda",
	"Esperança do Sul",
	"Esperança Nova",
	"Espigão Alto do Iguaçu",
	"Espumoso",
	"Estação",
	"Estância Velha",
	"Esteio",
	"Estrela",
	"Estrela Velha",
	"Eugênio de Castro",
	"Fagundes Varela",
	"Farol",
	"Farroupilha",
	"Faxinal",
	"Faxinal do Soturno",
	"Faxinal dos Guedes",
	"Faxinalzinho",
	"Fazenda Rio Grande",
	"Fazenda Vilanova",
	"Feliz",
	"Fênix",
	"Fernandes Pinheiro",
	"Figueira",
	"Flor da Serra do Sul",
	"Flor do Sertão",
	"Floraí",
	"Flores da Cunha",
	"Floresta",
	"Florestópolis",
	"Floriano Peixoto",
	"Florianópolis",
	"Flórida",
	"Fontoura Xavier",
	"Formigueiro",
	"Formosa do Oeste",
	"Formosa do Sul",
	"Forquetinha",
	"Forquilhinha",
	"Fortaleza dos Valos",
	"Foz do Iguaçu",
	"Foz do Jordão",
	"Fraiburgo",
	"Francisco Alves",
	"Francisco Beltrão",
	"Frederico Westphalen",
	"Frei Rogério",
	"Galvão",
	"Garibaldi",
	"Garopaba",
	"Garruchos",
	"Garuva",
	"Gaspar",
	"Gaurama",
	"General Câmara",
	"General Carneiro",
	"Gentil",
	"Getúlio Vargas",
	"Giruá",
	"Glorinha",
	"Godoy Moreira",
	"Goioerê",
	"Goioxim",
	"Governador Celso Ramos",
	"Gramado",
	"Gramado dos Loureiros",
	"Gramado Xavier",
	"Grandes Rios",
	"Grão-Pará",
	"Gravataí",
	"Gravatal",
	"Guabiju",
	"Guabiruba",
	"Guaíba",
	"Guaíra",
	"Guairaçá",
	"Guamiranga",
	"Guapirama",
	"Guaporé",
	"Guaporema",
	"Guaraci",
	"Guaraciaba",
	"Guaramirim",
	"Guarani das Missões",
	"Guaraniaçu",
	"Guarapuava",
	"Guaraqueçaba",
	"Guaratuba",
	"Guarujá do Sul",
	"Guatambú",
	"Harmonia",
	"Herval",
	"Herval d'Oeste",
	"Herveiras",
	"Honório Serpa",
	"Horizontina",
	"Hulha Negra",
	"Humaitá",
	"Ibaiti",
	"Ibarama",
	"Ibema",
	"Ibiaçá",
	"Ibiam",
	"Ibicaré",
	"Ibiporã",
	"Ibiraiaras",
	"Ibirama",
	"Ibirapuitã",
	"Ibirubá",
	"Içara",
	"Icaraíma",
	"Igrejinha",
	"Iguaraçu",
	"Iguatu",
	"Ijuí",
	"Ilhota",
	"Ilópolis",
	"Imaruí",
	"Imbaú",
	"Imbé",
	"Imbituba",
	"Imbituva",
	"Imbuia",
	"Imigrante",
	"Inácio Martins",
	"Inajá",
	"Indaial",
	"Independência",
	"Indianópolis",
	"Inhacorá",
	"Iomerê",
	"Ipê",
	"Ipira",
	"Ipiranga",
	"Ipiranga do Sul",
	"Iporã",
	"Iporã do Oeste",
	"Ipuaçu",
	"Ipumirim",
	"Iracema do Oeste",
	"Iraceminha",
	"Iraí",
	"Irani",
	"Irati",
	"Iretama",
	"Irineópolis",
	"Itá",
	"Itaara",
	"Itacurubi",
	"Itaguajé",
	"Itaiópolis",
	"Itaipulândia",
	"Itajaí",
	"Itambaracá",
	"Itambé",
	"Itapejara d'Oeste",
	"Itapema",
	"Itaperuçu",
	"Itapiranga",
	"Itapoá",
	"Itapuca",
	"Itaqui",
	"Itati",
	"Itatiba do Sul",
	"Itaúna do Sul",
	"Ituporanga",
	"Ivaí",
	"Ivaiporã",
	"Ivaté",
	"Ivatuba",
	"Ivorá",
	"Ivoti",
	"Jaborá",
	"Jaboti",
	"Jaboticaba",
	"Jacarezinho",
	"Jacinto Machado",
	"Jacuizinho",
	"Jacutinga",
	"Jaguapitã",
	"Jaguarão",
	"Jaguari",
	"Jaguariaíva",
	"Jaguaruna",
	"Jandaia do Sul",
	"Janiópolis",
	"Japira",
	"Japurá",
	"Jaquirana",
	"Jaraguá do Sul",
	"Jardim Alegre",
	"Jardim Olinda",
	"Jardinópolis",
	"Jari",
	"Jataizinho",
	"Jesuítas",
	"Joaçaba",
	"Joaquim Távora",
	"Jóia",
	"Joinville",
	"José Boiteux",
	"Júlio de Castilhos",
	"Jundiaí do Sul",
	"Jupiá",
	"Juranda",
	"Jussara",
	"Kaloré",
	"Lacerdópolis",
	"Lages",
	"Lagoa Bonita do Sul",
	"Lagoa dos Três Cantos",
	"Lagoa Vermelha",
	"Lagoão",
	"Laguna",
	"Lajeado",
	"Lajeado do Bugre",
	"Lajeado Grande",
	"Lapa",
	"Laranjal",
	"Laranjeiras do Sul",
	"Laurentino",
	"Lauro Müller",
	"Lavras do Sul",
	"Lebon Régis",
	"Leoberto Leal",
	"Leópolis",
	"Liberato Salzano",
	"Lidianópolis",
	"Lindoeste",
	"Lindóia do Sul",
	"Lindolfo Collor",
	"Linha Nova",
	"Loanda",
	"Lobato",
	"Londrina",
	"Lontras",
	"Luiz Alves",
	"Luiziana",
	"Lunardelli",
	"Lupionópolis",
	"Luzerna",
	"Maçambará",
	"Machadinho",
	"Macieira",
	"Mafra",
	"Major Gercino",
	"Major Vieira",
	"Mallet",
	"Mamborê",
	"Mampituba",
	"Mandaguaçu",
	"Mandaguari",
	"Mandirituba",
	"Manfrinópolis",
	"Mangueirinha",
	"Manoel Ribas",
	"Manoel Viana",
	"Maquiné",
	"Maracajá",
	"Maratá",
	"Marau",
	"Maravilha",
	"Marcelino Ramos",
	"Marechal Cândido Rondon",
	"Marema",
	"Maria Helena",
	"Marialva",
	"Mariana Pimentel",
	"Mariano Moro",
	"Marilândia do Sul",
	"Marilena",
	"Mariluz",
	"Maringá",
	"Mariópolis",
	"Maripá",
	"Marmeleiro",
	"Marques de Souza",
	"Marquinho",
	"Marumbi",
	"Massaranduba",
	"Mata",
	"Matelândia",
	"Matinhos",
	"Mato Castelhano",
	"Mato Leitão",
	"Mato Queimado",
	"Mato Rico",
	"Matos Costa",
	"Mauá da Serra",
	"Maximiliano de Almeida",
	"Medianeira",
	"Meleiro",
	"Mercedes",
	"Minas do Leão",
	"Mirador",
	"Miraguaí",
	"Miraselva",
	"Mirim Doce",
	"Missal",
	"Modelo",
	"Mondaí",
	"Montauri",
	"Monte Alegre dos Campos",
	"Monte Belo do Sul",
	"Monte Carlo",
	"Monte Castelo",
	"Montenegro",
	"Moreira Sales",
	"Mormaço",
	"Morretes",
	"Morrinhos do Sul",
	"Morro da Fumaça",
	"Morro Grande",
	"Morro Redondo",
	"Morro Reuter",
	"Mostardas",
	"Muçum",
	"Muitos Capões",
	"Muliterno",
	"Munhoz de Melo",
	"Não-Me-Toque",
	"Navegantes",
	"Nicolau Vergueiro",
	"Nonoai",
	"Nossa Senhora das Graças",
	"Nova Aliança do Ivaí",
	"Nova Alvorada",
	"Nova América da Colina",
	"Nova Araçá",
	"Nova Aurora",
	"Nova Bassano",
	"Nova Boa Vista",
	"Nova Bréscia",
	"Nova Candelária",
	"Nova Cantu",
	"Nova Erechim",
	"Nova Esperança",
	"Nova Esperança do Sudoeste",
	"Nova Esperança do Sul",
	"Nova Fátima",
	"Nova Hartz",
	"Nova Itaberaba",
	"Nova Laranjeiras",
	"Nova Londrina",
	"Nova Olímpia",
	"Nova Pádua",
	"Nova Palma",
	"Nova Petrópolis",
	"Nova Prata",
	"Nova Prata do Iguaçu",
	"Nova Ramada",
	"Nova Roma do Sul",
	"Nova Santa Bárbara",
	"Nova Santa Rita",
	"Nova Santa Rosa",
	"Nova Tebas",
	"Nova Trento",
	"Nova Veneza",
	"Novo Barreiro",
	"Novo Cabrais",
	"Novo Hamburgo",
	"Novo Horizonte",
	"Novo Itacolomi",
	"Novo Machado",
	"Novo Tiradentes",
	"Novo Xingu",
	"Orleans",
	"Ortigueira",
	"Osório",
	"Otacílio Costa",
	"Ourizona",
	"Ouro",
	"Ouro Verde",
	"Ouro Verde do Oeste",
	"Paial",
	"Paiçandu",
	"Paim Filho",
	"Painel",
	"Palhoça",
	"Palma Sola",
	"Palmares do Sul",
	"Palmas",
	"Palmeira",
	"Palmeira das Missões",
	"Palmital",
	"Palmitinho",
	"Palmitos",
	"Palotina",
	"Panambi",
	"Pantano Grande",
	"Papanduva",
	"Paraí",
	"Paraíso",
	"Paraíso do Norte",
	"Paraíso do Sul",
	"Paranacity",
	"Paranaguá",
	"Paranapoema",
	"Paranavaí",
	"Pareci Novo",
	"Parobé",
	"Passa Sete",
	"Passo de Torres",
	"Passo do Sobrado",
	"Passo Fundo",
	"Passos Maia",
	"Pato Bragado",
	"Pato Branco",
	"Paula Freitas",
	"Paulo Bento",
	"Paulo Frontin",
	"Paulo Lopes",
	"Paverama",
	"Peabiru",
	"Pedras Altas",
	"Pedras Grandes",
	"Pedro Osório",
	"Pejuçara",
	"Pelotas",
	"Penha",
	"Peritiba",
	"Perobal",
	"Pérola",
	"Pérola d'Oeste",
	"Pescaria Brava",
	"Petrolândia",
	"Picada Café",
	"Piên",
	"Pinhais",
	"Pinhal",
	"Pinhal da Serra",
	"Pinhal de São Bento",
	"Pinhal Grande",
	"Pinhalão",
	"Pinhalzinho",
	"Pinhão",
	"Pinheirinho do Vale",
	"Pinheiro Machado",
	"Pinheiro Preto",
	"Pinto Bandeira",
	"Piraí do Sul",
	"Pirapó",
	"Piraquara",
	"Piratini",
	"Piratuba",
	"Pitanga",
	"Pitangueiras",
	"Planaltina do Paraná",
	"Planalto",
	"Planalto Alegre",
	"Poço das Antas",
	"Pomerode",
	"Ponta Grossa",
	"Pontal do Paraná",
	"Pontão",
	"Ponte Alta",
	"Ponte Alta do Norte",
	"Ponte Preta",
	"Ponte Serrada",
	"Porecatu",
	"Portão",
	"Porto Alegre",
	"Porto Amazonas",
	"Porto Barreiro",
	"Porto Belo",
	"Porto Lucena",
	"Porto Mauá",
	"Porto Rico",
	"Porto União",
	"Porto Vera Cruz",
	"Porto Vitória",
	"Porto Xavier",
	"Pouso Novo",
	"Pouso Redondo",
	"Prado Ferreira",
	"Praia Grande",
	"Pranchita",
	"Presidente Castello Branco",
	"Presidente Castelo Branco",
	"Presidente Getúlio",
	"Presidente Lucena",
	"Presidente Nereu",
	"Primeiro de Maio",
	"Princesa",
	"Progresso",
	"Protásio Alves",
	"Prudentópolis",
	"Putinga",
	"Quaraí",
	"Quarto Centenário",
	"Quatiguá",
	"Quatro Barras",
	"Quatro Irmãos",
	"Quatro Pontes",
	"Quedas do Iguaçu",
	"Querência do Norte",
	"Quevedos",
	"Quilombo",
	"Quinta do Sol",
	"Quinze de Novembro",
	"Quitandinha",
	"Ramilândia",
	"Rancho Alegre",
	"Rancho Alegre D'Oeste",
	"Rancho Queimado",
	"Realeza",
	"Rebouças",
	"Redentora",
	"Relvado",
	"Renascença",
	"Reserva",
	"Reserva do Iguaçu",
	"Restinga Sêca",
	"Ribeirão Claro",
	"Ribeirão do Pinhal",
	"Rio Azul",
	"Rio Bom",
	"Rio Bonito do Iguaçu",
	"Rio Branco do Ivaí",
	"Rio Branco do Sul",
	"Rio das Antas",
	"Rio do Campo",
	"Rio do Oeste",
	"Rio do Sul",
	"Rio dos Cedros",
	"Rio dos Índios",
	"Rio Fortuna",
	"Rio Grande",
	"Rio Negrinho",
	"Rio Negro",
	"Rio Pardo",
	"Rio Rufino",
	"Riozinho",
	"Riqueza",
	"Roca Sales",
	"Rodeio",
	"Rodeio Bonito",
	"Rolador",
	"Rolândia",
	"Rolante",
	"Romelândia",
	"Roncador",
	"Ronda Alta",
	"Rondinha",
	"Rondon",
	"Roque Gonzales",
	"Rosário do Ivaí",
	"Rosário do Sul",
	"Sabáudia",
	"Sagrada Família",
	"Saldanha Marinho",
	"Salete",
	"Salgado Filho",
	"Saltinho",
	"Salto do Itararé",
	"Salto do Jacuí",
	"Salto do Lontra",
	"Salto Veloso",
	"Salvador das Missões",
	"Salvador do Sul",
	"Sananduva",
	"Sangão",
	"Sant'Ana do Livramento",
	"Santa Amélia",
	"Santa Bárbara do Sul",
	"Santa Cecília",
	"Santa Cecília do Pavão",
	"Santa Cecília do Sul",
	"Santa Clara do Sul",
	"Santa Cruz de Monte Castelo",
	"Santa Cruz do Sul",
	"Santa Fé",
	"Santa Helena",
	"Santa Inês",
	"Santa Isabel do Ivaí",
	"Santa Izabel do Oeste",
	"Santa Lúcia",
	"Santa Margarida do Sul",
	"Santa Maria",
	"Santa Maria do Herval",
	"Santa Maria do Oeste",
	"Santa Mariana",
	"Santa Mônica",
	"Santa Rosa",
	"Santa Rosa de Lima",
	"Santa Rosa do Sul",
	"Santa Tereza",
	"Santa Tereza do Oeste",
	"Santa Terezinha",
	"Santa Terezinha de Itaipu",
	"Santa Terezinha do Progresso",
	"Santa Vitória do Palmar",
	"Santana da Boa Vista",
	"Santana do Itararé",
	"Santiago",
	"Santiago do Sul",
	"Santo Amaro da Imperatriz",
	"Santo Ângelo",
	"Santo Antônio da Patrulha",
	"Santo Antônio da Platina",
	"Santo Antônio das Missões",
	"Santo Antônio do Caiuá",
	"Santo Antônio do Palma",
	"Santo Antônio do Paraíso",
	"Santo Antônio do Planalto",
	"Santo Antônio do Sudoeste",
	"Santo Augusto",
	"Santo Cristo",
	"Santo Expedito do Sul",
	"Santo Inácio",
	"São Bento do Sul",
	"São Bernardino",
	"São Bonifácio",
	"São Borja",
	"São Carlos",
	"São Carlos do Ivaí",
	"São Cristóvão do Sul",
	"São Domingos",
	"São Domingos do Sul",
	"São Francisco de Assis",
	"São Francisco de Paula",
	"São Francisco do Sul",
	"São Gabriel",
	"São Jerônimo",
	"São Jerônimo da Serra",
	"São João",
	"São João Batista",
	"São João da Urtiga",
	"São João do Caiuá",
	"São João do Itaperiú",
	"São João do Ivaí",
	"São João do Oeste",
	"São João do Polêsine",
	"São João do Sul",
	"São João do Triunfo",
	"São Joaquim",
	"São Jorge",
	"São Jorge d'Oeste",
	"São Jorge do Ivaí",
	"São Jorge do Patrocínio",
	"São José",
	"São José da Boa Vista",
	"São José das Missões",
	"São José das Palmeiras",
	"São José do Cedro",
	"São José do Cerrito",
	"São José do Herval",
	"São José do Hortêncio",
	"São José do Inhacorá",
	"São José do Norte",
	"São José do Ouro",
	"São José do Sul",
	"São José dos Ausentes",
	"São José dos Pinhais",
	"São Leopoldo",
	"São Lourenço do Oeste",
	"São Lourenço do Sul",
	"São Ludgero",
	"São Luiz Gonzaga",
	"São Manoel do Paraná",
	"São Marcos",
	"São Martinho",
	"São Martinho da Serra",
	"São Mateus do Sul",
	"São Miguel da Boa Vista",
	"São Miguel das Missões",
	"São Miguel do Iguaçu",
	"São Miguel do Oeste",
	"São Nicolau",
	"São Paulo das Missões",
	"São Pedro da Serra",
	"São Pedro das Missões",
	"São Pedro de Alcântara",
	"São Pedro do Butiá",
	"São Pedro do Iguaçu",
	"São Pedro do Ivaí",
	"São Pedro do Paraná",
	"São Pedro do Sul",
	"São Sebastião da Amoreira",
	"São Sebastião do Caí",
	"São Sepé",
	"São Tomé",
	"São Valentim",
	"São Valentim do Sul",
	"São Valério do Sul",
	"São Vendelino",
	"São Vicente do Sul",
	"Sapiranga",
	"Sapopema",
	"Sapucaia do Sul",
	"Sarandi",
	"Saudade do Iguaçu",
	"Saudades",
	"Schroeder",
	"Seara",
	"Seberi",
	"Sede Nova",
	"Segredo",
	"Selbach",
	"Senador Salgado Filho",
	"Sengés",
	"Sentinela do Sul",
	"Serafina Corrêa",
	"Sério",
	"Serra Alta",
	"Serranópolis do Iguaçu",
	"Sertaneja",
	"Sertanópolis",
	"Sertão",
	"Sertão Santana",
	"Sete de Setembro",
	"Severiano de Almeida",
	"Siderópolis",
	"Silveira Martins",
	"Sinimbu",
	"Siqueira Campos",
	"Sobradinho",
	"Soledade",
	"Sombrio",
	"Sul Brasil",
	"Sulina",
	"Tabaí",
	"Taió",
	"Tamarana",
	"Tamboara",
	"Tangará",
	"Tapejara",
	"Tapera",
	"Tapes",
	"Tapira",
	"Taquara",
	"Taquari",
	"Taquaruçu do Sul",
	"Tavares",
	"Teixeira Soares",
	"Telêmaco Borba",
	"Tenente Portela",
	"Terra Boa",
	"Terra de Areia",
	"Terra Rica",
	"Terra Roxa",
	"Teutônia",
	"Tibagi",
	"Tigrinhos",
	"Tijucas",
	"Tijucas do Sul",
	"Timbé do Sul",
	"Timbó",
	"Timbó Grande",
	"Tio Hugo",
	"Tiradentes do Sul",
	"Toledo",
	"Tomazina",
	"Toropi",
	"Torres",
	"Tramandaí",
	"Travesseiro",
	"Três Arroios",
	"Três Barras",
	"Três Barras do Paraná",
	"Três Cachoeiras",
	"Três Coroas",
	"Três de Maio",
	"Três Forquilhas",
	"Três Palmeiras",
	"Três Passos",
	"Treviso",
	"Treze de Maio",
	"Treze Tílias",
	"Trindade do Sul",
	"Triunfo",
	"Trombudo Central",
	"Tubarão",
	"Tucunduva",
	"Tunápolis",
	"Tunas",
	"Tunas do Paraná",
	"Tuneiras do Oeste",
	"Tupanci do Sul",
	"Tupanciretã",
	"Tupandi",
	"Tuparendi",
	"Tupãssi",
	"Turuçu",
	"Turvo",
	"Ubiratã",
	"Ubiretama",
	"Umuarama",
	"União da Serra",
	"União da Vitória",
	"União do Oeste",
	"Uniflor",
	"Unistalda",
	"Uraí",
	"Urubici",
	"Uruguaiana",
	"Urupema",
	"Urussanga",
	"Vacaria",
	"Vale do Sol",
	"Vale Real",
	"Vale Verde",
	"Vanini",
	"Vargeão",
	"Vargem",
	"Vargem Bonita",
	"Venâncio Aires",
	"Ventania",
	"Vera Cruz",
	"Vera Cruz do Oeste",
	"Veranópolis",
	"Verê",
	"Vespasiano Corrêa",
	"Viadutos",
	"Viamão",
	"Vicente Dutra",
	"Victor Graeff",
	"Vidal Ramos",
	"Videira",
	"Vila Flores",
	"Vila Lângaro",
	"Vila Maria",
	"Vila Nova do Sul",
	"Virmond",
	"Vista Alegre",
	"Vista Alegre do Prata",
	"Vista Gaúcha",
	"Vitor Meireles",
	"Vitória das Missões",
	"Vitorino",
	"Wenceslau Braz",
	"Westfália",
	"Witmarsum",
	"Xambrê",
	"Xangri-lá",
	"Xanxerê",
	"Xavantina",
	"Xaxim",
	"Zortéa"
}
