-- Source: IBGE (servicodados.ibge.gov.br/api/v1/localidades/municipios)
return {
	"Abaetetuba",
	"Abel Figueiredo",
	"Abreulândia",
	"Acará",
	"Acrelândia",
	"Afuá",
	"Água Azul do Norte",
	"Aguiarnópolis",
	"Alenquer",
	"Aliança do Tocantins",
	"Almas",
	"Almeirim",
	"Alta Floresta D'Oeste",
	"Altamira",
	"Alto Alegre",
	"Alto Alegre dos Parecis",
	"Alto Paraíso",
	"Alvarães",
	"Alvorada",
	"Alvorada D'Oeste",
	"Amajari",
	"Amapá",
	"Amaturá",
	"Anajás",
	"Anamã",
	"Ananás",
	"Ananindeua",
	"Anapu",
	"Angico",
	"Anori",
	"Aparecida do Rio Negro",
	"Apuí",
	"Aragominas",
	"Araguacema",
	"Araguaçu",
	"Araguaína",
	"Araguanã",
	"Araguatins",
	"Arapoema",
	"Ariquemes",
	"Arraias",
	"Assis Brasil",
	"Atalaia do Norte",
	"Augustinópolis",
	"Augusto Corrêa",
	"Aurora do Pará",
	"Aurora do Tocantins",
	"Autazes",
	"Aveiro",
	"Axixá do Tocantins",
	"Babaçulândia",
	"Bagre",
	"Baião",
	"Bandeirantes do Tocantins",
	"Bannach",
	"Barcarena",
	"Barcelos",
	"Barra do Ouro",
	"Barreirinha",
	"Barrolândia",
	"Belém",
	"Belterra",
	"Benevides",
	"Benjamin Constant",
	"Bernardo Sayão",
	"Beruri",
	"Boa Vista",
	"Boa Vista do Ramos",
	"Boca do Acre",
	"Bom Jesus do Tocantins",
	"Bonfim",
	"Bonito",
	"Borba",
	"Bragança",
	"Brasil Novo",
	"Brasilândia do Tocantins",
	"Brasiléia",
	"Brejinho de Nazaré",
	"Brejo Grande do Araguaia",
	"Breu Branco",
	"Breves",
	"Bujari",
	"Bujaru",
	"Buriti do Tocantins",
	"Buritis",
	"Caapiranga",
	"Cabixi",
	"Cacaulândia",
	"Cachoeira do Arari",
	"Cachoeira do Piriá",
	"Cachoeirinha",
	"Cacoal",
	"Calçoene",
	"Cametá",
	"Campo Novo de Rondônia",
	"Campos Lindos",
	"Canaã dos Carajás",
	"Candeias do Jamari",
	"Cantá",
	"Canutama",
	"Capanema",
	"Capitão Poço",
	"Capixaba",
	"Caracaraí",
	"Carauari",
	"Careiro",
	"Careiro da Várzea",
	"Cariri do Tocantins",
	"Carmolândia",
	"Caroebe",
	"Carrasco Bonito",
	"Caseara",
	"Castanhal",
	"Castanheiras",
	"Centenário",
	"Cerejeiras",
	"Chapada da Natividade",
	"Chapada de Areia",
	"Chaves",
	"Chupinguaia",
	"Coari",
	"Codajás",
	"Colares",
	"Colinas do Tocantins",
	"Colméia",
	"Colorado do Oeste",
	"Combinado",
	"Conceição do Araguaia",
	"Conceição do Tocantins",
	"Concórdia do Pará",
	"Corumbiara",
	"Costa Marques",
	"Couto Magalhães",
	"Cristalândia",
	"Crixás do Tocantins",
	"Cruzeiro do Sul",
	"Cujubim",
	"Cumaru do Norte",
	"Curionópolis",
	"Curralinho",
	"Curuá",
	"Curuçá",
	"Cutias",
	"Darcinópolis",
	"Dianópolis",
	"Divinópolis do Tocantins",
	"Dois Irmãos do Tocantins",
	"Dom Eliseu",
	"Dueré",
	"Eirunepé",
	"Eldorado do Carajás",
	"Envira",
	"Epitaciolândia",
	"Esperantina",
	"Espigão D'Oeste",
	"Faro",
	"Fátima",
	"Feijó",
	"Ferreira Gomes",
	"Figueirópolis",
	"Filadélfia",
	"Floresta do Araguaia",
	"Fonte Boa",
	"Formoso do Araguaia",
	"Garrafão do Norte",
	"Goianésia do Pará",
	"Goianorte",
	"Goiatins",
	"Governador Jorge Teixeira",
	"Guajará",
	"Guajará-Mirim",
	"Guaraí",
	"Gurupá",
	"Gurupi",
	"Humaitá",
	"Igarapé-Açu",
	"Igarapé-Miri",
	"Inhangapi",
	"Ipixuna",
	"Ipixuna do Pará",
	"Ipueiras",
	"Iracema",
	"Iranduba",
	"Irituia",
	"Itacajá",
	"Itacoatiara",
	"Itaguatins",
	"Itaituba",
	"Itamarati",
	"Itapiranga",
	"Itapiratins",
	"Itaporã do Tocantins",
	"Itapuã do Oeste",
	"Itaubal",
	"Itupiranga",
	"Jacareacanga",
	"Jacundá",
	"Japurá",
	"Jaru",
	"Jaú do Tocantins",
	"Ji-Paraná",
	"Jordão",
	"Juarina",
	"Juruá",
	"Juruti",
	"Jutaí",
	"Lábrea",
	"Lagoa da Confusão",
	"Lagoa do Tocantins",
	"Lajeado",
	"Laranjal do Jari",
	"Lavandeira",
	"Limoeiro do Ajuru",
	"Lizarda",
	"Luzinópolis",
	"Macapá",
	"Machadinho D'Oeste",
	"Mãe do Rio",
	"Magalhães Barata",
	"Manacapuru",
	"Manaquiri",
	"Manaus",
	"Mâncio Lima",
	"Manicoré",
	"Manoel Urbano",
	"Maraã",
	"Marabá",
	"Maracanã",
	"Marapanim",
	"Marechal Thaumaturgo",
	"Marianópolis do Tocantins",
	"Marituba",
	"Mateiros",
	"Maués",
	"Maurilândia do Tocantins",
	"Mazagão",
	"Medicilândia",
	"Melgaço",
	"Ministro Andreazza",
	"Miracema do Tocantins",
	"Miranorte",
	"Mirante da Serra",
	"Mocajuba",
	"Moju",
	"Mojuí dos Campos",
	"Monte Alegre",
	"Monte do Carmo",
	"Monte Negro",
	"Monte Santo do Tocantins",
	"Muaná",
	"Mucajaí",
	"Muricilândia",
	"Natividade",
	"Nazaré",
	"Nhamundá",
	"Normandia",
	"Nova Brasilândia D'Oeste",
	"Nova Esperança do Piriá",
	"Nova Ipixuna",
	"Nova Mamoré",
	"Nova Olinda",
	"Nova Olinda do Norte",
	"Nova Rosalândia",
	"Nova Timboteua",
	"Nova União",
	"Novo Acordo",
	"Novo Airão",
	"Novo Alegre",
	"Novo Aripuanã",
	"Novo Horizonte do Oeste",
	"Novo Jardim",
	"Novo Progresso",
	"Novo Repartimento",
	"Óbidos",
	"Oeiras do Pará",
	"Oiapoque",
	"Oliveira de Fátima",
	"Oriximiná",
	"Ourém",
	"Ourilândia do Norte",
	"Ouro Preto do Oeste",
	"Pacajá",
	"Pacaraima",
	"Palestina do Pará",
	"Palmas",
	"Palmeirante",
	"Palmeiras do Tocantins",
	"Palmeirópolis",
	"Paragominas",
	"Paraíso do Tocantins",
	"Paranã",
	"Parauapebas",
	"Parecis",
	"Parintins",
	"Pau D'Arco",
	"Pauini",
	"Pedra Branca do Amapari",
	"Pedro Afonso",
	"Peixe",
	"Peixe-Boi",
	"Pequizeiro",
	"Piçarra",
	"Pimenta Bueno",
	"Pimenteiras do Oeste",
	"Pindorama do Tocantins",
	"Piraquê",
	"Pium",
	"Placas",
	"Plácido de Castro",
	"Ponta de Pedras",
	"Ponte Alta do Bom Jesus",
	"Ponte Alta do Tocantins",
	"Portel",
	"Porto Acre",
	"Porto Alegre do Tocantins",
	"Porto de Moz",
	"Porto Grande",
	"Porto Nacional",
	"Porto Velho",
	"Porto Walter",
	"Pracuúba",
	"Praia Norte",
	"Prainha",
	"Presidente Figueiredo",
	"Presidente Kennedy",
	"Presidente Médici",
	"Primavera",
	"Primavera de Rondônia",
	"Pugmil",
	"Quatipuru",
	"Recursolândia",
	"Redenção",
	"Riachinho",
	"Rio Branco",
	"Rio Crespo",
	"Rio da Conceição",
	"Rio dos Bois",
	"Rio Maria",
	"Rio Preto da Eva",
	"Rio Sono",
	"Rodrigues Alves",
	"Rolim de Moura",
	"Rondon do Pará",
	"Rorainópolis",
	"Rurópolis",
	"Salinópolis",
	"Salvaterra",
	"Sampaio",
	"Sandolândia",
	"Santa Bárbara do Pará",
	"Santa Cruz do Arari",
	"Santa Fé do Araguaia",
	"Santa Isabel do Rio Negro",
	"Santa Izabel do Pará",
	"Santa Luzia D'Oeste",
	"Santa Luzia do Pará",
	"Santa Maria das Barreiras",
	"Santa Maria do Pará",
	"Santa Maria do Tocantins",
	"Santa Rita do Tocantins",
	"Santa Rosa do Purus",
	"Santa Rosa do Tocantins",
	"Santa Tereza do Tocantins",
	"Santa Terezinha do Tocantins",
	"Santana",
	"Santana do Araguaia",
	"Santarém",
	"Santarém Novo",
	"Santo Antônio do Içá",
	"Santo Antônio do Tauá",
	"São Bento do Tocantins",
	"São Caetano de Odivelas",
	"São Domingos do Araguaia",
	"São Domingos do Capim",
	"São Felipe D'Oeste",
	"São Félix do Tocantins",
	"São Félix do Xingu",
	"São Francisco do Guaporé",
	"São Francisco do Pará",
	"São Gabriel da Cachoeira",
	"São Geraldo do Araguaia",
	"São João da Baliza",
	"São João da Ponta",
	"São João de Pirabas",
	"São João do Araguaia",
	"São Luiz do Anauá",
	"São Miguel do Guamá",
	"São Miguel do Guaporé",
	"São Miguel do Tocantins",
	"São Paulo de Olivença",
	"São Salvador do Tocantins",
	"São Sebastião da Boa Vista",
	"São Sebastião do Tocantins",
	"São Sebastião do Uatumã",
	"São Valério",
	"Sapucaia",
	"Sena Madureira",
	"Senador Guiomard",
	"Senador José Porfírio",
	"Seringueiras",
	"Serra do Navio",
	"Silvanópolis",
	"Silves",
	"Sítio Novo do Tocantins",
	"Soure",
	"Sucupira",
	"Tabatinga",
	"Tabocão",
	"Taguatinga",
	"Tailândia",
	"Taipas do Tocantins",
	"Talismã",
	"Tapauá",
	"Tarauacá",
	"Tartarugalzinho",
	"Tefé",
	"Teixeirópolis",
	"Terra Alta",
	"Terra Santa",
	"Theobroma",
	"Tocantínia",
	"Tocantinópolis",
	"Tomé-Açu",
	"Tonantins",
	"Tracuateua",
	"Trairão",
	"Tucumã",
	"Tucuruí",
	"Tupirama",
	"Tupiratins",
	"Uarini",
	"Uiramutã",
	"Ulianópolis",
	"Uruará",
	"Urucará",
	"Urucurituba",
	"Urupá",
	"Vale do Anari",
	"Vale do Paraíso",
	"Vigia",
	"Vilhena",
	"Viseu",
	"Vitória do Jari",
	"Vitória do Xingu",
	"Wanderlândia",
	"Xambioá",
	"Xapuri",
	"Xinguara"
}
