-- Source: IBGE (servicodados.ibge.gov.br/api/v1/localidades/municipios)
return {
	"Abaiara",
	"Abaíra",
	"Abaré",
	"Abreu e Lima",
	"Açailândia",
	"Acajutiba",
	"Acarape",
	"Acaraú",
	"Acari",
	"Acauã",
	"Acopiara",
	"Adustina",
	"Afogados da Ingazeira",
	"Afonso Bezerra",
	"Afonso Cunha",
	"Afrânio",
	"Agrestina",
	"Agricolândia",
	"Água Branca",
	"Água Doce do Maranhão",
	"Água Fria",
	"Água Nova",
	"Água Preta",
	"Águas Belas",
	"Aguiar",
	"Aiquara",
	"Aiuaba",
	"Alagoa Grande",
	"Alagoa Nova",
	"Alagoinha",
	"Alagoinha do Piauí",
	"Alagoinhas",
	"Alcântara",
	"Alcântaras",
	"Alcantil",
	"Alcobaça",
	"Aldeias Altas",
	"Alegrete do Piauí",
	"Alexandria",
	"Algodão de Jandaíra",
	"Alhandra",
	"Aliança",
	"Almadina",
	"Almino Afonso",
	"Altamira do Maranhão",
	"Altaneira",
	"Altinho",
	"Alto Alegre do Maranhão",
	"Alto Alegre do Pindaré",
	"Alto do Rodrigues",
	"Alto Longá",
	"Alto Parnaíba",
	"Alto Santo",
	"Altos",
	"Alvorada do Gurguéia",
	"Amapá do Maranhão",
	"Amaraji",
	"Amarante",
	"Amarante do Maranhão",
	"Amargosa",
	"Amélia Rodrigues",
	"América Dourada",
	"Amontada",
	"Amparo",
	"Amparo do São Francisco",
	"Anadia",
	"Anagé",
	"Anajatuba",
	"Anapurus",
	"Andaraí",
	"Andorinha",
	"Angelim",
	"Angical",
	"Angical do Piauí",
	"Angicos",
	"Anguera",
	"Anísio de Abreu",
	"Antas",
	"Antonina do Norte",
	"Antônio Almeida",
	"Antônio Cardoso",
	"Antônio Gonçalves",
	"Antônio Martins",
	"Aparecida",
	"Apicum-Açu",
	"Apodi",
	"Aporá",
	"Apuarema",
	"Apuiarés",
	"Aquidabã",
	"Aquiraz",
	"Araçagi",
	"Aracaju",
	"Araçás",
	"Aracati",
	"Aracatu",
	"Araci",
	"Aracoiaba",
	"Araçoiaba",
	"Araguanã",
	"Araioses",
	"Aramari",
	"Arame",
	"Arapiraca",
	"Arara",
	"Ararendá",
	"Arari",
	"Araripe",
	"Araripina",
	"Araruna",
	"Arataca",
	"Aratuba",
	"Aratuípe",
	"Arauá",
	"Arcoverde",
	"Areia",
	"Areia Branca",
	"Areia de Baraúnas",
	"Areial",
	"Arez",
	"Arneiroz",
	"Aroazes",
	"Aroeiras",
	"Aroeiras do Itaim",
	"Arraial",
	"Assaré",
	"Assú",
	"Assunção",
	"Assunção do Piauí",
	"Atalaia",
	"Aurelino Leal",
	"Aurora",
	"Avelino Lopes",
	"Axixá",
	"Bacabal",
	"Bacabeira",
	"Bacuri",
	"Bacurituba",
	"Baía da Traição",
	"Baía Formosa",
	"Baianópolis",
	"Baixa Grande",
	"Baixa Grande do Ribeiro",
	"Baixio",
	"Balsas",
	"Banabuiú",
	"Bananeiras",
	"Banzaê",
	"Barão de Grajaú",
	"Baraúna",
	"Barbalha",
	"Barcelona",
	"Barra",
	"Barra D'Alcântara",
	"Barra da Estiva",
	"Barra de Guabiraba",
	"Barra de Santa Rosa",
	"Barra de Santana",
	"Barra de Santo Antônio",
	"Barra de São Miguel",
	"Barra do Choça",
	"Barra do Corda",
	"Barra do Mendes",
	"Barra do Rocha",
	"Barra dos Coqueiros",
	"Barras",
	"Barreira",
	"Barreiras",
	"Barreiras do Piauí",
	"Barreirinhas",
	"Barreiros",
	"Barro",
	"Barro Alto",
	"Barro Duro",
	"Barro Preto",
	"Barrocas",
	"Barroquinha",
	"Batalha",
	"Baturité",
	"Bayeux",
	"Beberibe",
	"Bela Cruz",
	"Bela Vista do Maranhão",
	"Bela Vista do Piauí",
	"Belágua",
	"Belém",
	"Belém de Maria",
	"Belém do Brejo do Cruz",
	"Belém do Piauí",
	"Belém do São Francisco",
	"Belmonte",
	"Belo Campo",
	"Belo Jardim",
	"Belo Monte",
	"Beneditinos",
	"Benedito Leite",
	"Bento Fernandes",
	"Bequimão",
	"Bernardino Batista",
	"Bernardo do Mearim",
	"Bertolínia",
	"Betânia",
	"Betânia do Piauí",
	"Bezerros",
	"Biritinga",
	"Boa Hora",
	"Boa Nova",
	"Boa Ventura",
	"Boa Viagem",
	"Boa Vista",
	"Boa Vista do Gurupi",
	"Boa Vista do Tupim",
	"Boca da Mata",
	"Bocaina",
	"Bodó",
	"Bodocó",
	"Bom Conselho",
	"Bom Jardim",
	"Bom Jesus",
	"Bom Jesus da Lapa",
	"Bom Jesus da Serra",
	"Bom Jesus das Selvas",
	"Bom Lugar",
	"Bom Princípio do Piauí",
	"Bom Sucesso",
	"Bonfim do Piauí",
	"Boninal",
	"Bonito",
	"Bonito de Santa Fé",
	"Boqueirão",
	"Boqueirão do Piauí",
	"Boquim",
	"Boquira",
	"Borborema",
	"Botuporã",
	"Branquinha",
	"Brasileira",
	"Brejão",
	"Brejinho",
	"Brejo",
	"Brejo da Madre de Deus",
	"Brejo de Areia",
	"Brejo do Cruz",
	"Brejo do Piauí",
	"Brejo dos Santos",
	"Brejo Grande",
	"Brejo Santo",
	"Brejões",
	"Brejolândia",
	"Brotas de Macaúbas",
	"Brumado",
	"Buenos Aires",
	"Buerarema",
	"Buíque",
	"Buriti",
	"Buriti Bravo",
	"Buriti dos Lopes",
	"Buriti dos Montes",
	"Buriticupu",
	"Buritirama",
	"Buritirana",
	"Caaporã",
	"Caatiba",
	"Cabaceiras",
	"Cabaceiras do Paraguaçu",
	"Cabeceiras do Piauí",
	"Cabedelo",
	"Cabo de Santo Agostinho",
	"Cabrobó",
	"Cachoeira",
	"Cachoeira dos Índios",
	"Cachoeira Grande",
	"Cachoeirinha",
	"Cacimba de Areia",
	"Cacimba de Dentro",
	"Cacimbas",
	"Cacimbinhas",
	"Caculé",
	"Caém",
	"Caetanos",
	"Caetés",
	"Caetité",
	"Cafarnaum",
	"Caiçara",
	"Caiçara do Norte",
	"Caiçara do Rio do Vento",
	"Caicó",
	"Cairu",
	"Cajapió",
	"Cajari",
	"Cajazeiras",
	"Cajazeiras do Piauí",
	"Cajazeirinhas",
	"Cajueiro",
	"Cajueiro da Praia",
	"Calçado",
	"Caldas Brandão",
	"Caldeirão Grande",
	"Caldeirão Grande do Piauí",
	"Calumbi",
	"Camacan",
	"Camaçari",
	"Camalaú",
	"Camamu",
	"Camaragibe",
	"Camocim",
	"Camocim de São Félix",
	"Campestre",
	"Campestre do Maranhão",
	"Campina Grande",
	"Campinas do Piauí",
	"Campo Alegre",
	"Campo Alegre de Lourdes",
	"Campo Alegre do Fidalgo",
	"Campo do Brito",
	"Campo Formoso",
	"Campo Grande",
	"Campo Grande do Piauí",
	"Campo Largo do Piauí",
	"Campo Maior",
	"Campo Redondo",
	"Campos Sales",
	"Camutanga",
	"Canapi",
	"Canápolis",
	"Canarana",
	"Canavieira",
	"Canavieiras",
	"Candeal",
	"Candeias",
	"Candiba",
	"Cândido Mendes",
	"Cândido Sales",
	"Canguaretama",
	"Canhoba",
	"Canhotinho",
	"Canindé",
	"Canindé de São Francisco",
	"Cansanção",
	"Cantanhede",
	"Canto do Buriti",
	"Canudos",
	"Capela",
	"Capela do Alto Alegre",
	"Capim",
	"Capim Grosso",
	"Capinzal do Norte",
	"Capistrano",
	"Capitão de Campos",
	"Capitão Gervásio Oliveira",
	"Capoeiras",
	"Caracol",
	"Caraíbas",
	"Caraúbas",
	"Caraúbas do Piauí",
	"Caravelas",
	"Cardeal da Silva",
	"Caridade",
	"Caridade do Piauí",
	"Carinhanha",
	"Carira",
	"Cariré",
	"Caririaçu",
	"Cariús",
	"Carmópolis",
	"Carnaíba",
	"Carnaúba dos Dantas",
	"Carnaubais",
	"Carnaubal",
	"Carnaubeira da Penha",
	"Carneiros",
	"Carolina",
	"Carpina",
	"Carrapateira",
	"Caruaru",
	"Carutapera",
	"Casa Nova",
	"Cascavel",
	"Casinhas",
	"Casserengue",
	"Castelo do Piauí",
	"Castro Alves",
	"Catarina",
	"Catende",
	"Catingueira",
	"Catolândia",
	"Catolé do Rocha",
	"Catu",
	"Catunda",
	"Caturama",
	"Caturité",
	"Caucaia",
	"Caxias",
	"Caxingó",
	"Ceará-Mirim",
	"Cedral",
	"Cedro",
	"Cedro de São João",
	"Central",
	"Central do Maranhão",
	"Centro do Guilherme",
	"Centro Novo do Maranhão",
	"Cerro Corá",
	"Chã de Alegria",
	"Chã Grande",
	"Chã Preta",
	"Chapadinha",
	"Chaval",
	"Choró",
	"Chorozinho",
	"Chorrochó",
	"Cícero Dantas",
	"Cidelândia",
	"Cipó",
	"Coaraci",
	"Cocal",
	"Cocal de Telha",
	"Cocal dos Alves",
	"Cocos",
	"Codó",
	"Coelho Neto",
	"Coité do Nóia",
	"Coivaras",
	"Colinas",
	"Colônia do Gurguéia",
	"Colônia do Piauí",
	"Colônia Leopoldina",
	"Conceição",
	"Conceição da Feira",
	"Conceição do Almeida",
	"Conceição do Canindé",
	"Conceição do Coité",
	"Conceição do Jacuípe",
	"Conceição do Lago-Açu",
	"Condado",
	"Conde",
	"Condeúba",
	"Congo",
	"Contendas do Sincorá",
	"Coqueiro Seco",
	"Coração de Maria",
	"Cordeiros",
	"Coreaú",
	"Coremas",
	"Coribe",
	"Coroatá",
	"Coronel Ezequiel",
	"Coronel João Pessoa",
	"Coronel João Sá",
	"Coronel José Dias",
	"Corrente",
	"Correntes",
	"Correntina",
	"Cortês",
	"Coruripe",
	"Cotegipe",
	"Coxixola",
	"Craíbas",
	"Crateús",
	"Crato",
	"Cravolândia",
	"Crisópolis",
	"Cristalândia do Piauí",
	"Cristinápolis",
	"Cristino Castro",
	"Cristópolis",
	"Croatá",
	"Cruz",
	"Cruz das Almas",
	"Cruz do Espírito Santo",
	"Cruzeta",
	"Cubati",
	"Cuité",
	"Cuité de Mamanguape",
	"Cuitegi",
	"Cumaru",
	"Cumbe",
	"Cupira",
	"Curaçá",
	"Curimatá",
	"Currais",
	"Currais Novos",
	"Curral de Cima",
	"Curral Novo do Piauí",
	"Curral Velho",
	"Curralinhos",
	"Cururupu",
	"Custódia",
	"Damião",
	"Dário Meira",
	"Davinópolis",
	"Delmiro Gouveia",
	"Demerval Lobão",
	"Deputado Irapuan Pinheiro",
	"Desterro",
	"Diamante",
	"Dias d'Ávila",
	"Dirceu Arcoverde",
	"Divina Pastora",
	"Dois Riachos",
	"Dom Basílio",
	"Dom Expedito Lopes",
	"Dom Inocêncio",
	"Dom Macedo Costa",
	"Dom Pedro",
	"Domingos Mourão",
	"Dona Inês",
	"Dormentes",
	"Doutor Severiano",
	"Duas Estradas",
	"Duque Bacelar",
	"Elesbão Veloso",
	"Eliseu Martins",
	"Elísio Medrado",
	"Emas",
	"Encanto",
	"Encruzilhada",
	"Entre Rios",
	"Equador",
	"Ereré",
	"Érico Cardoso",
	"Escada",
	"Esperança",
	"Esperantina",
	"Esperantinópolis",
	"Espírito Santo",
	"Esplanada",
	"Estância",
	"Estreito",
	"Estrela de Alagoas",
	"Euclides da Cunha",
	"Eunápolis",
	"Eusébio",
	"Extremoz",
	"Exu",
	"Fagundes",
	"Farias Brito",
	"Fartura do Piauí",
	"Fátima",
	"Feira da Mata",
	"Feira de Santana",
	"Feira Grande",
	"Feira Nova",
	"Feira Nova do Maranhão",
	"Felipe Guerra",
	"Feliz Deserto",
	"Fernando de Noronha",
	"Fernando Falcão",
	"Fernando Pedroza",
	"Ferreiros",
	"Filadélfia",
	"Firmino Alves",
	"Flexeiras",
	"Florânia",
	"Flores",
	"Flores do Piauí",
	"Floresta",
	"Floresta Azul",
	"Floresta do Piauí",
	"Floriano",
	"Formosa da Serra Negra",
	"Formosa do Rio Preto",
	"Forquilha",
	"Fortaleza",
	"Fortaleza dos Nogueiras",
	"Fortim",
	"Fortuna",
	"Francinópolis",
	"Francisco Ayres",
	"Francisco Dantas",
	"Francisco Macedo",
	"Francisco Santos",
	"Frecheirinha",
	"Frei Martinho",
	"Frei Miguelinho",
	"Frei Paulo",
	"Fronteiras",
	"Frutuoso Gomes",
	"Gado Bravo",
	"Galinhos",
	"Gameleira",
	"Gandu",
	"Garanhuns",
	"Gararu",
	"Gavião",
	"Geminiano",
	"General Maynard",
	"General Sampaio",
	"Gentio do Ouro",
	"Gilbués",
	"Girau do Ponciano",
	"Glória",
	"Glória do Goitá",
	"Godofredo Viana",
	"Goiana",
	"Goianinha",
	"Gonçalves Dias",
	"Gongogi",
	"Governador Archer",
	"Governador Dix-Sept Rosado",
	"Governador Edison Lobão",
	"Governador Eugênio Barros",
	"Governador Luiz Rocha",
	"Governador Mangabeira",
	"Governador Newton Bello",
	"Governador Nunes Freire",
	"Graça",
	"Graça Aranha",
	"Graccho Cardoso",
	"Grajaú",
	"Granito",
	"Granja",
	"Granjeiro",
	"Gravatá",
	"Groaíras",
	"Grossos",
	"Guadalupe",
	"Guaiúba",
	"Guajeru",
	"Guamaré",
	"Guanambi",
	"Guarabira",
	"Guaraciaba do Norte",
	"Guaramiranga",
	"Guaratinga",
	"Guaribas",
	"Guimarães",
	"Gurinhém",
	"Gurjão",
	"Heliópolis",
	"Hidrolândia",
	"Horizonte",
	"Hugo Napoleão",
	"Humberto de Campos",
	"Iaçu",
	"Iati",
	"Ibaretama",
	"Ibateguara",
	"Ibiapina",
	"Ibiara",
	"Ibiassucê",
	"Ibicaraí",
	"Ibicoara",
	"Ibicuí",
	"Ibicuitinga",
	"Ibimirim",
	"Ibipeba",
	"Ibipitanga",
	"Ibiquera",
	"Ibirajuba",
	"Ibirapitanga",
	"Ibirapuã",
	"Ibirataia",
	"Ibitiara",
	"Ibititá",
	"Ibotirama",
	"Icapuí",
	"Icatu",
	"Ichu",
	"Icó",
	"Ielmo Marinho",
	"Igaci",
	"Igaporã",
	"Igaracy",
	"Igarapé do Meio",
	"Igarapé Grande",
	"Igarassu",
	"Igrapiúna",
	"Igreja Nova",
	"Iguaí",
	"Iguaracy",
	"Iguatu",
	"Ilha das Flores",
	"Ilha de Itamaracá",
	"Ilha Grande",
	"Ilhéus",
	"Imaculada",
	"Imperatriz",
	"Inajá",
	"Independência",
	"Indiaroba",
	"Ingá",
	"Ingazeira",
	"Inhambupe",
	"Inhapi",
	"Inhuma",
	"Ipanguaçu",
	"Ipaporanga",
	"Ipaumirim",
	"Ipecaetá",
	"Ipiaú",
	"Ipirá",
	"Ipiranga do Piauí",
	"Ipojuca",
	"Ipu",
	"Ipubi",
	"Ipueira",
	"Ipueiras",
	"Ipupiara",
	"Iracema",
	"Irajuba",
	"Iramaia",
	"Iraquara",
	"Irará",
	"Irauçuba",
	"Irecê",
	"Isaías Coelho",
	"Itabaiana",
	"Itabaianinha",
	"Itabela",
	"Itaberaba",
	"Itabi",
	"Itabuna",
	"Itacaré",
	"Itacuruba",
	"Itaeté",
	"Itagi",
	"Itagibá",
	"Itagimirim",
	"Itaguaçu da Bahia",
	"Itaíba",
	"Itaiçaba",
	"Itainópolis",
	"Itaipava do Grajaú",
	"Itaitinga",
	"Itajá",
	"Itaju do Colônia",
	"Itajuípe",
	"Itamaraju",
	"Itamari",
	"Itambé",
	"Itanagra",
	"Itanhém",
	"Itapajé",
	"Itaparica",
	"Itapé",
	"Itapebi",
	"Itapecuru Mirim",
	"Itapetim",
	"Itapetinga",
	"Itapicuru",
	"Itapipoca",
	"Itapissuma",
	"Itapitanga",
	"Itapiúna",
	"Itaporanga",
	"Itaporanga d'Ajuda",
	"Itapororoca",
	"Itaquara",
	"Itaquitinga",
	"Itarantim",
	"Itarema",
	"Itatim",
	"Itatira",
	"Itatuba",
	"Itaú",
	"Itaueira",
	"Itinga do Maranhão",
	"Itiruçu",
	"Itiúba",
	"Itororó",
	"Ituaçu",
	"Ituberá",
	"Iuiu",
	"Jaboatão dos Guararapes",
	"Jaborandi",
	"Jaçanã",
	"Jacaraci",
	"Jacaraú",
	"Jacaré dos Homens",
	"Jacobina",
	"Jacobina do Piauí",
	"Jacuípe",
	"Jaguaquara",
	"Jaguarari",
	"Jaguaretama",
	"Jaguaribara",
	"Jaguaribe",
	"Jaguaripe",
	"Jaguaruana",
	"Jaicós",
	"Jandaíra",
	"Janduís",
	"Januário Cicco",
	"Japaratinga",
	"Japaratuba",
	"Japi",
	"Japoatã",
	"Jaqueira",
	"Jaramataia",
	"Jardim",
	"Jardim de Angicos",
	"Jardim de Piranhas",
	"Jardim do Mulato",
	"Jardim do Seridó",
	"Jataúba",
	"Jati",
	"Jatobá",
	"Jatobá do Piauí",
	"Jenipapo dos Vieiras",
	"Jequiá da Praia",
	"Jequié",
	"Jeremoabo",
	"Jericó",
	"Jerumenha",
	"Jijoca de Jericoacoara",
	"Jiquiriçá",
	"Jitaúna",
	"João Alfredo",
	"João Câmara",
	"João Costa",
	"João Dias",
	"João Dourado",
	"João Lisboa",
	"João Pessoa",
	"Joaquim Gomes",
	"Joaquim Nabuco",
	"Joaquim Pires",
	"Joca Claudino",
	"Joca Marques",
	"José da Penha",
	"José de Freitas",
	"Joselândia",
	"Juarez Távora",
	"Juazeirinho",
	"Juazeiro",
	"Juazeiro do Norte",
	"Juazeiro do Piauí",
	"Jucás",
	"Jucati",
	"Jucuruçu",
	"Jucurutu",
	"Júlio Borges",
	"Junco do Maranhão",
	"Junco do Seridó",
	"Jundiá",
	"Junqueiro",
	"Jupi",
	"Jurema",
	"Juripiranga",
	"Juru",
	"Jussara",
	"Jussari",
	"Jussiape",
	"Lafaiete Coutinho",
	"Lagarto",
	"Lago da Pedra",
	"Lago do Junco",
	"Lago dos Rodrigues",
	"Lago Verde",
	"Lagoa",
	"Lagoa Alegre",
	"Lagoa d'Anta",
	"Lagoa da Canoa",
	"Lagoa de Dentro",
	"Lagoa de Itaenga",
	"Lagoa de Pedras",
	"Lagoa de São Francisco",
	"Lagoa de Velhos",
	"Lagoa do Barro do Piauí",
	"Lagoa do Carro",
	"Lagoa do Mato",
	"Lagoa do Ouro",
	"Lagoa do Piauí",
	"Lagoa do Sítio",
	"Lagoa dos Gatos",
	"Lagoa Grande",
	"Lagoa Grande do Maranhão",
	"Lagoa Nova",
	"Lagoa Real",
	"Lagoa Salgada",
	"Lagoa Seca",
	"Lagoinha do Piauí",
	"Laje",
	"Lajeado Novo",
	"Lajedão",
	"Lajedinho",
	"Lajedo",
	"Lajedo do Tabocal",
	"Lajes",
	"Lajes Pintadas",
	"Lamarão",
	"Landri Sales",
	"Lapão",
	"Laranjeiras",
	"Lastro",
	"Lauro de Freitas",
	"Lavras da Mangabeira",
	"Lençóis",
	"Licínio de Almeida",
	"Lima Campos",
	"Limoeiro",
	"Limoeiro de Anadia",
	"Limoeiro do Norte",
	"Livramento",
	"Livramento de Nossa Senhora",
	"Logradouro",
	"Loreto",
	"Lucena",
	"Lucrécia",
	"Luís Correia",
	"Luís Domingues",
	"Luís Eduardo Magalhães",
	"Luís Gomes",
	"Luzilândia",
	"Macaíba",
	"Macajuba",
	"Macambira",
	"Macaparana",
	"Macarani",
	"Macau",
	"Macaúbas",
	"Maceió",
	"Machados",
	"Macururé",
	"Madalena",
	"Madeiro",
	"Madre de Deus",
	"Mãe d'Água",
	"Maetinga",
	"Magalhães de Almeida",
	"Maiquinique",
	"Mairi",
	"Major Isidoro",
	"Major Sales",
	"Malhada",
	"Malhada de Pedras",
	"Malhada dos Bois",
	"Malhador",
	"Malta",
	"Mamanguape",
	"Manaíra",
	"Manari",
	"Manoel Emídio",
	"Manoel Vitorino",
	"Mansidão",
	"Mar Vermelho",
	"Maracaçumé",
	"Maracanaú",
	"Maracás",
	"Maragogi",
	"Maragogipe",
	"Maraial",
	"Marajá do Sena",
	"Maranguape",
	"Maranhãozinho",
	"Maraú",
	"Maravilha",
	"Marcação",
	"Marcelino Vieira",
	"Marcionílio Souza",
	"Marco",
	"Marcolândia",
	"Marcos Parente",
	"Marechal Deodoro",
	"Mari",
	"Maribondo",
	"Marizópolis",
	"Martinópole",
	"Martins",
	"Maruim",
	"Mascote",
	"Massapê",
	"Massapê do Piauí",
	"Massaranduba",
	"Mata de São João",
	"Mata Grande",
	"Mata Roma",
	"Mataraca",
	"Matias Olímpio",
	"Matina",
	"Matinha",
	"Matinhas",
	"Mato Grosso",
	"Matões",
	"Matões do Norte",
	"Matriz de Camaragibe",
	"Maturéia",
	"Mauriti",
	"Maxaranguape",
	"Medeiros Neto",
	"Meruoca",
	"Messias",
	"Messias Targino",
	"Miguel Alves",
	"Miguel Calmon",
	"Miguel Leão",
	"Milagres",
	"Milagres do Maranhão",
	"Milhã",
	"Milton Brandão",
	"Minador do Negrão",
	"Mirador",
	"Miraíma",
	"Miranda do Norte",
	"Mirandiba",
	"Mirangaba",
	"Mirante",
	"Mirinzal",
	"Missão Velha",
	"Mogeiro",
	"Moita Bonita",
	"Mombaça",
	"Monção",
	"Monsenhor Gil",
	"Monsenhor Hipólito",
	"Monsenhor Tabosa",
	"Montadas",
	"Montanhas",
	"Monte Alegre",
	"Monte Alegre de Sergipe",
	"Monte Alegre do Piauí",
	"Monte das Gameleiras",
	"Monte Horebe",
	"Monte Santo",
	"Monteiro",
	"Monteirópolis",
	"Montes Altos",
	"Morada Nova",
	"Moraújo",
	"Moreilândia",
	"Moreno",
	"Morpará",
	"Morrinhos",
	"Morro Cabeça no Tempo",
	"Morro do Chapéu",
	"Morro do Chapéu do Piauí",
	"Morros",
	"Mortugaba",
	"Mossoró",
	"Mucambo",
	"Mucugê",
	"Mucuri",
	"Mulungu",
	"Mulungu do Morro",
	"Mundo Novo",
	"Muniz Ferreira",
	"Muquém do São Francisco",
	"Muribeca",
	"Murici",
	"Murici dos Portelas",
	"Muritiba",
	"Mutuípe",
	"Natal",
	"Natuba",
	"Nazaré",
	"Nazaré da Mata",
	"Nazaré do Piauí",
	"Nazarezinho",
	"Nazária",
	"Neópolis",
	"Nilo Peçanha",
	"Nina Rodrigues",
	"Nísia Floresta",
	"Nordestina",
	"Nossa Senhora Aparecida",
	"Nossa Senhora da Glória",
	"Nossa Senhora das Dores",
	"Nossa Senhora de Lourdes",
	"Nossa Senhora de Nazaré",
	"Nossa Senhora do Socorro",
	"Nossa Senhora dos Remédios",
	"Nova Canaã",
	"Nova Colinas",
	"Nova Cruz",
	"Nova Fátima",
	"Nova Floresta",
	"Nova Ibiá",
	"Nova Iorque",
	"Nova Itarana",
	"Nova Olinda",
	"Nova Olinda do Maranhão",
	"Nova Palmeira",
	"Nova Redenção",
	"Nova Russas",
	"Nova Santa Rita",
	"Nova Soure",
	"Nova Viçosa",
	"Novo Horizonte",
	"Novo Lino",
	"Novo Oriente",
	"Novo Oriente do Piauí",
	"Novo Santo Antônio",
	"Novo Triunfo",
	"Ocara",
	"Oeiras",
	"Olho d'Água",
	"Olho d'Água das Cunhãs",
	"Olho d'Água das Flores",
	"Olho d'Água do Borges",
	"Olho d'Água do Casado",
	"Olho D'Água do Piauí",
	"Olho d'Água Grande",
	"Olinda",
	"Olinda Nova do Maranhão",
	"Olindina",
	"Olivedos",
	"Oliveira dos Brejinhos",
	"Olivença",
	"Orobó",
	"Orocó",
	"Orós",
	"Ouriçangas",
	"Ouricuri",
	"Ouro Branco",
	"Ouro Velho",
	"Ourolândia",
	"Pacajus",
	"Pacatuba",
	"Paço do Lumiar",
	"Pacoti",
	"Pacujá",
	"Padre Marcos",
	"Paes Landim",
	"Pajeú do Piauí",
	"Palestina",
	"Palhano",
	"Palmácia",
	"Palmares",
	"Palmas de Monte Alto",
	"Palmeira do Piauí",
	"Palmeira dos Índios",
	"Palmeirais",
	"Palmeirândia",
	"Palmeiras",
	"Palmeirina",
	"Panelas",
	"Pão de Açúcar",
	"Paquetá",
	"Paracuru",
	"Paraibano",
	"Paraipaba",
	"Parambu",
	"Paramirim",
	"Paramoti",
	"Paraná",
	"Paranatama",
	"Parari",
	"Paratinga",
	"Paraú",
	"Parazinho",
	"Parelhas",
	"Pariconha",
	"Paripiranga",
	"Paripueira",
	"Parnaguá",
	"Parnaíba",
	"Parnamirim",
	"Parnarama",
	"Passa e Fica",
	"Passagem",
	"Passagem Franca",
	"Passagem Franca do Piauí",
	"Passira",
	"Passo de Camaragibe",
	"Pastos Bons",
	"Patos",
	"Patos do Piauí",
	"Patu",
	"Pau Brasil",
	"Pau D'Arco do Piauí",
	"Pau dos Ferros",
	"Paudalho",
	"Paulino Neves",
	"Paulista",
	"Paulistana",
	"Paulo Afonso",
	"Paulo Jacinto",
	"Paulo Ramos",
	"Pavussu",
	"Pé de Serra",
	"Pedra",
	"Pedra Branca",
	"Pedra Grande",
	"Pedra Lavrada",
	"Pedra Mole",
	"Pedra Preta",
	"Pedrão",
	"Pedras de Fogo",
	"Pedreiras",
	"Pedrinhas",
	"Pedro Alexandre",
	"Pedro Avelino",
	"Pedro do Rosário",
	"Pedro II",
	"Pedro Laurentino",
	"Pedro Régis",
	"Pedro Velho",
	"Penaforte",
	"Penalva",
	"Pendências",
	"Penedo",
	"Pentecoste",
	"Pereiro",
	"Peri Mirim",
	"Peritoró",
	"Pesqueira",
	"Petrolândia",
	"Petrolina",
	"Piaçabuçu",
	"Piancó",
	"Piatã",
	"Picos",
	"Picuí",
	"Pilão Arcado",
	"Pilar",
	"Pilões",
	"Pilõezinhos",
	"Pimenteiras",
	"Pindaí",
	"Pindaré-Mirim",
	"Pindoba",
	"Pindobaçu",
	"Pindoretama",
	"Pinhão",
	"Pinheiro",
	"Pintadas",
	"Pio IX",
	"Pio XII",
	"Piquet Carneiro",
	"Piracuruca",
	"Piraí do Norte",
	"Pirambu",
	"Piranhas",
	"Pirapemas",
	"Pires Ferreira",
	"Piripá",
	"Piripiri",
	"Piritiba",
	"Pirpirituba",
	"Pitimbu",
	"Planaltino",
	"Planalto",
	"Poção",
	"Poção de Pedras",
	"Pocinhos",
	"Poço Branco",
	"Poço Dantas",
	"Poço das Trincheiras",
	"Poço de José de Moura",
	"Poço Redondo",
	"Poço Verde",
	"Poções",
	"Pojuca",
	"Pombal",
	"Pombos",
	"Ponto Novo",
	"Poranga",
	"Portalegre",
	"Porteiras",
	"Porto",
	"Porto Alegre do Piauí",
	"Porto Calvo",
	"Porto da Folha",
	"Porto de Pedras",
	"Porto do Mangue",
	"Porto Franco",
	"Porto Real do Colégio",
	"Porto Rico do Maranhão",
	"Porto Seguro",
	"Potengi",
	"Potiraguá",
	"Potiretama",
	"Prado",
	"Prata",
	"Prata do Piauí",
	"Presidente Dutra",
	"Presidente Jânio Quadros",
	"Presidente Juscelino",
	"Presidente Médici",
	"Presidente Sarney",
	"Presidente Tancredo Neves",
	"Presidente Vargas",
	"Primavera",
	"Primeira Cruz",
	"Princesa Isabel",
	"Propriá",
	"Pureza",
	"Puxinanã",
	"Quebrangulo",
	"Queimada Nova",
	"Queimadas",
	"Quijingue",
	"Quipapá",
	"Quiterianópolis",
	"Quixaba",
	"Quixabeira",
	"Quixadá",
	"Quixelô",
	"Quixeramobim",
	"Quixeré",
	"Rafael Fernandes",
	"Rafael Godeiro",
	"Rafael Jambeiro",
	"Raposa",
	"Recife",
	"Redenção",
	"Redenção do Gurguéia",
	"Regeneração",
	"Remanso",
	"Remígio",
	"Reriutaba",
	"Retirolândia",
	"Riachão",
	"Riachão das Neves",
	"Riachão do Bacamarte",
	"Riachão do Dantas",
	"Riachão do Jacuípe",
	"Riachão do Poço",
	"Riacho da Cruz",
	"Riacho das Almas",
	"Riacho de Santana",
	"Riacho de Santo Antônio",
	"Riacho dos Cavalos",
	"Riacho Frio",
	"Riachuelo",
	"Ribamar Fiquene",
	"Ribeira do Amparo",
	"Ribeira do Piauí",
	"Ribeira do Pombal",
	"Ribeirão",
	"Ribeirão do Largo",
	"Ribeiro Gonçalves",
	"Ribeirópolis",
	"Rio de Contas",
	"Rio do Antônio",
	"Rio do Fogo",
	"Rio do Pires",
	"Rio Formoso",
	"Rio Grande do Piauí",
	"Rio Largo",
	"Rio Real",
	"Rio Tinto",
	"Rodelas",
	"Rodolfo Fernandes",
	"Rosário",
	"Rosário do Catete",
	"Roteiro",
	"Russas",
	"Ruy Barbosa",
	"Saboeiro",
	"Sairé",
	"Salgadinho",
	"Salgado",
	"Salgado de São Félix",
	"Salgueiro",
	"Salinas da Margarida",
	"Salitre",
	"Saloá",
	"Salvador",
	"Sambaíba",
	"Sanharó",
	"Santa Bárbara",
	"Santa Brígida",
	"Santa Cecília",
	"Santa Cruz",
	"Santa Cruz Cabrália",
	"Santa Cruz da Baixa Verde",
	"Santa Cruz da Vitória",
	"Santa Cruz do Capibaribe",
	"Santa Cruz do Piauí",
	"Santa Cruz dos Milagres",
	"Santa Filomena",
	"Santa Filomena do Maranhão",
	"Santa Helena",
	"Santa Inês",
	"Santa Luz",
	"Santa Luzia",
	"Santa Luzia do Itanhy",
	"Santa Luzia do Norte",
	"Santa Luzia do Paruá",
	"Santa Maria",
	"Santa Maria da Boa Vista",
	"Santa Maria da Vitória",
	"Santa Maria do Cambucá",
	"Santa Quitéria",
	"Santa Quitéria do Maranhão",
	"Santa Rita",
	"Santa Rita de Cássia",
	"Santa Rosa de Lima",
	"Santa Rosa do Piauí",
	"Santa Teresinha",
	"Santa Terezinha",
	"Santaluz",
	"Santana",
	"Santana de Mangueira",
	"Santana do Acaraú",
	"Santana do Cariri",
	"Santana do Ipanema",
	"Santana do Maranhão",
	"Santana do Matos",
	"Santana do Mundaú",
	"Santana do Piauí",
	"Santana do São Francisco",
	"Santana do Seridó",
	"Santana dos Garrotes",
	"Santanópolis",
	"Santo Amaro",
	"Santo Amaro das Brotas",
	"Santo Amaro do Maranhão",
	"Santo André",
	"Santo Antônio",
	"Santo Antônio de Jesus",
	"Santo Antônio de Lisboa",
	"Santo Antônio dos Lopes",
	"Santo Antônio dos Milagres",
	"Santo Estêvão",
	"Santo Inácio do Piauí",
	"São Benedito",
	"São Benedito do Rio Preto",
	"São Benedito do Sul",
	"São Bentinho",
	"São Bento",
	"São Bento do Norte",
	"São Bento do Trairí",
	"São Bento do Una",
	"São Bernardo",
	"São Brás",
	"São Braz do Piauí",
	"São Caitano",
	"São Cristóvão",
	"São Desidério",
	"São Domingos",
	"São Domingos do Azeitão",
	"São Domingos do Cariri",
	"São Domingos do Maranhão",
	"São Felipe",
	"São Félix",
	"São Félix de Balsas",
	"São Félix do Coribe",
	"São Félix do Piauí",
	"São Fernando",
	"São Francisco",
	"São Francisco de Assis do Piauí",
	"São Francisco do Brejão",
	"São Francisco do Conde",
	"São Francisco do Maranhão",
	"São Francisco do Oeste",
	"São Francisco do Piauí",
	"São Gabriel",
	"São Gonçalo do Amarante",
	"São Gonçalo do Gurguéia",
	"São Gonçalo do Piauí",
	"São Gonçalo dos Campos",
	"São João",
	"São João Batista",
	"São João da Canabrava",
	"São João da Fronteira",
	"São João da Serra",
	"São João da Varjota",
	"São João do Arraial",
	"São João do Cariri",
	"São João do Carú",
	"São João do Jaguaribe",
	"São João do Paraíso",
	"São João do Piauí",
	"São João do Rio do Peixe",
	"São João do Sabugi",
	"São João do Soter",
	"São João do Tigre",
	"São João dos Patos",
	"São Joaquim do Monte",
	"São José da Coroa Grande",
	"São José da Lagoa Tapada",
	"São José da Laje",
	"São José da Tapera",
	"São José da Vitória",
	"São José de Caiana",
	"São José de Espinharas",
	"São José de Mipibu",
	"São José de Piranhas",
	"São José de Princesa",
	"São José de Ribamar",
	"São José do Belmonte",
	"São José do Bonfim",
	"São José do Brejo do Cruz",
	"São José do Campestre",
	"São José do Divino",
	"São José do Egito",
	"São José do Jacuípe",
	"São José do Peixe",
	"São José do Piauí",
	"São José do Sabugi",
	"São José do Seridó",
	"São José dos Basílios",
	"São José dos Cordeiros",
	"São José dos Ramos",
	"São Julião",
	"São Lourenço da Mata",
	"São Lourenço do Piauí",
	"São Luís",
	"São Luís do Curu",
	"São Luis do Piauí",
	"São Luís do Quitunde",
	"São Luís Gonzaga do Maranhão",
	"São Mamede",
	"São Mateus do Maranhão",
	"São Miguel",
	"São Miguel da Baixa Grande",
	"São Miguel das Matas",
	"São Miguel de Taipu",
	"São Miguel do Aleixo",
	"São Miguel do Fidalgo",
	"São Miguel do Gostoso",
	"São Miguel do Tapuio",
	"São Miguel dos Campos",
	"São Miguel dos Milagres",
	"São Paulo do Potengi",
	"São Pedro",
	"São Pedro da Água Branca",
	"São Pedro do Piauí",
	"São Pedro dos Crentes",
	"São Rafael",
	"São Raimundo das Mangabeiras",
	"São Raimundo do Doca Bezerra",
	"São Raimundo Nonato",
	"São Roberto",
	"São Sebastião",
	"São Sebastião de Lagoa de Roça",
	"São Sebastião do Passé",
	"São Sebastião do Umbuzeiro",
	"São Tomé",
	"São Vicente",
	"São Vicente do Seridó",
	"São Vicente Ferrer",
	"São Vicente Férrer",
	"Sapé",
	"Sapeaçu",
	"Sátiro Dias",
	"Satuba",
	"Satubinha",
	"Saubara",
	"Saúde",
	"Seabra",
	"Sebastião Barros",
	"Sebastião Laranjeiras",
	"Sebastião Leal",
	"Senador Alexandre Costa",
	"Senador Elói de Souza",
	"Senador Georgino Avelino",
	"Senador La Rocque",
	"Senador Pompeu",
	"Senador Rui Palmeira",
	"Senador Sá",
	"Senhor do Bonfim",
	"Sento Sé",
	"Serra Branca",
	"Serra Caiada",
	"Serra da Raiz",
	"Serra de São Bento",
	"Serra do Mel",
	"Serra do Ramalho",
	"Serra Dourada",
	"Serra Grande",
	"Serra Negra do Norte",
	"Serra Preta",
	"Serra Redonda",
	"Serra Talhada",
	"Serrano do Maranhão",
	"Serraria",
	"Serrinha",
	"Serrinha dos Pintos",
	"Serrita",
	"Serrolândia",
	"Sertânia",
	"Sertãozinho",
	"Severiano Melo",
	"Sigefredo Pacheco",
	"Simão Dias",
	"Simões",
	"Simões Filho",
	"Simplício Mendes",
	"Sirinhaém",
	"Siriri",
	"Sítio do Mato",
	"Sítio do Quinto",
	"Sítio Novo",
	"Sobradinho",
	"Sobrado",
	"Sobral",
	"Socorro do Piauí",
	"Solânea",
	"Soledade",
	"Solidão",
	"Solonópole",
	"Sossêgo",
	"Sousa",
	"Souto Soares",
	"Sucupira do Norte",
	"Sucupira do Riachão",
	"Sumé",
	"Surubim",
	"Sussuapara",
	"Tabira",
	"Tabocas do Brejo Velho",
	"Taboleiro Grande",
	"Tabuleiro do Norte",
	"Tacaimbó",
	"Tacaratu",
	"Tacima",
	"Taipu",
	"Tamandaré",
	"Tamboril",
	"Tamboril do Piauí",
	"Tangará",
	"Tanhaçu",
	"Tanque d'Arca",
	"Tanque do Piauí",
	"Tanque Novo",
	"Tanquinho",
	"Taperoá",
	"Tapiramutá",
	"Taquarana",
	"Taquaritinga do Norte",
	"Tarrafas",
	"Tasso Fragoso",
	"Tauá",
	"Tavares",
	"Teixeira",
	"Teixeira de Freitas",
	"Tejuçuoca",
	"Telha",
	"Tenente Ananias",
	"Tenente Laurentino Cruz",
	"Tenório",
	"Teodoro Sampaio",
	"Teofilândia",
	"Teolândia",
	"Teotônio Vilela",
	"Teresina",
	"Terezinha",
	"Terra Nova",
	"Tianguá",
	"Tibau",
	"Tibau do Sul",
	"Timbaúba",
	"Timbaúba dos Batistas",
	"Timbiras",
	"Timon",
	"Tobias Barreto",
	"Tomar do Geru",
	"Toritama",
	"Touros",
	"Tracunhaém",
	"Traipu",
	"Trairi",
	"Tremedal",
	"Trindade",
	"Triunfo",
	"Triunfo Potiguar",
	"Trizidela do Vale",
	"Tucano",
	"Tufilândia",
	"Tuntum",
	"Tupanatinga",
	"Tuparetama",
	"Turiaçu",
	"Turilândia",
	"Tururu",
	"Tutóia",
	"Uauá",
	"Ubaíra",
	"Ubaitaba",
	"Ubajara",
	"Ubatã",
	"Uibaí",
	"Uiraúna",
	"Umari",
	"Umarizal",
	"Umbaúba",
	"Umburanas",
	"Umbuzeiro",
	"Umirim",
	"Una",
	"União",
	"União dos Palmares",
	"Upanema",
	"Urandi",
	"Urbano Santos",
	"Uruburetama",
	"Uruçuca",
	"Uruçuí",
	"Uruoca",
	"Utinga",
	"Valença",
	"Valença do Piauí",
	"Valente",
	"Vargem Grande",
	"Varjota",
	"Várzea",
	"Várzea Alegre",
	"Várzea Branca",
	"Várzea da Roça",
	"Várzea do Poço",
	"Várzea Grande",
	"Várzea Nova",
	"Varzedo",
	"Venha-Ver",
	"Venturosa",
	"Vera Cruz",
	"Vera Mendes",
	"Verdejante",
	"Vereda",
	"Vertente do Lério",
	"Vertentes",
	"Viana",
	"Vicência",
	"Viçosa",
	"Viçosa do Ceará",
	"Vieirópolis",
	"Vila Flor",
	"Vila Nova do Piauí",
	"Vila Nova dos Martírios",
	"Vista Serrana",
	"Vitória da Conquista",
	"Vitória de Santo Antão",
	"Vitória do Mearim",
	"Vitorino Freire",
	"Wagner",
	"Wall Ferraz",
	"Wanderley",
	"Wenceslau Guimarães",
	"Xexéu",
	"Xique-Xique",
	"Zabelê",
	"Zé Doca"
}
