-- Source: IBGE (servicodados.ibge.gov.br/api/v1/localidades/municipios)
return {
	"Abatiá",
	"Abdon Batista",
	"Abelardo Luz",
	"Aceguá",
	"Adrianópolis",
	"Agrolândia",
	"Agronômica",
	"Água Doce",
	"Água Santa",
	"Águas de Chapecó",
	"Águas Frias",
	"Águas Mornas",
	"Agudo",
	"Agudos do Sul",
	"Ajuricaba",
	"Alecrim",
	"Alegrete",
	"Alegria",
	"Alfredo Wagner",
	"Almirante Tamandaré",
	"Almirante Tamandaré do Sul",
	"Alpestre",
	"Altamira do Paraná",
	"Alto Alegre",
	"Alto Bela Vista",
	"Alto Feliz",
	"Alto Paraíso",
	"Alto Paraná",
	"Alto Piquiri",
	"Altônia",
	"Alvorada",
	"Alvorada do Sul",
	"Amaporã",
	"Amaral Ferrador",
	"Ametista do Sul",
	"Ampére",
	"Anahy",
	"Anchieta",
	"Andirá",
	"André da Rocha",
	"Angelina",
	"Ângulo",
	"Anita Garibaldi",
	"Anitápolis",
	"Anta Gorda",
	"Antonina",
	"Antônio Carlos",
	"Antônio Olinto",
	"Antônio Prado",
	"Apiúna",
	"Apucarana",
	"Arabutã",
	"Arambaré",
	"Arapongas",
	"Arapoti",
	"Arapuã",
	"Araquari",
	"Araranguá",
	"Araricá",
	"Araruna",
	"Aratiba",
	"Araucária",
	"Ariranha do Ivaí",
	"Armazém",
	"Arroio do Meio",
	"Arroio do Padre",
	"Arroio do Sal",
	"Arroio do Tigre",
	"Arroio dos Ratos",
	"Arroio Grande",
	"Arroio Trinta",
	"Arvoredo",
	"Arvorezinha",
	"Ascurra",
	"Assaí",
	"Assis Chateaubriand",
	"Astorga",
	"Atalaia",
	"Atalanta",
	"Augusto Pestana",
	"Áurea",
	"Aurora",
	"Bagé",
	"Balneário Arroio do Silva",
	"Balneário Barra do Sul",
	"Balneário Camboriú",
	"Balneário Gaivota",
	"Balneário Piçarras",
	"Balneário Pinhal",
	"Balneário Rincão",
	"Balsa Nova",
	"Bandeirante",
	"Bandeirantes",
	"Barão",
	"Barão de Cotegipe",
	"Barão do Triunfo",
	"Barbosa Ferraz",
	"Barra Bonita",
	"Barra do Guarita",
	"Barra do Jacaré",
	"Barra do Quaraí",
	"Barra do Ribeiro",
	"Barra do Rio Azul",
	"Barra Funda",
	"Barra Velha",
	"Barracão",
	"Barros Cassal",
	"Bela Vista da Caroba",
	"Bela Vista do Paraíso",
	"Bela Vista do Toldo",
	"Belmonte",
	"Benedito Novo",
	"Benjamin Constant do Sul",
	"Bento Gonçalves",
	"Biguaçu",
	"Bituruna",
	"Blumenau",
	"Boa Esperança",
	"Boa Esperança do Iguaçu",
	"Boa Ventura de São Roque",
	"Boa Vista da Aparecida",
	"Boa Vista das Missões",
	"Boa Vista do Buricá",
	"Boa Vista do Cadeado",
	"Boa Vista do Incra",
	"Boa Vista do Sul",
	"Bocaina do Sul",
	"Bocaiúva do Sul",
	"Bom Jardim da Serra",
	"Bom Jesus",
	"Bom Jesus do Oeste",
	"Bom Jesus do Sul",
	"Bom Princípio",
	"Bom Progresso",
	"Bom Retiro",
	"Bom Retiro do Sul",
	"Bom Sucesso",
	"Bom Sucesso do Sul",
	"Bombinhas",
	"Boqueirão do Leão",
	"Borrazópolis",
	"Bossoroca",
	"Botuverá",
	"Bozano",
	"Braço do Norte",
	"Braço do Trombudo",
	"Braga",
	"Braganey",
	"Brasilândia do Sul",
	"Brochier",
	"Brunópolis",
	"Brusque",
	"Butiá",
	"Caçador",
	"Caçapava do Sul",
	"Cacequi",
	"Cachoeira do Sul",
	"Cachoeirinha",
	"Cacique Doble",
	"Cafeara",
	"Cafelândia",
	"Cafezal do Sul",
	"Caibaté",
	"Caibi",
	"Caiçara",
	"Califórnia",
	"Calmon",
	"Camaquã",
	"Camargo",
	"Cambará",
	"Cambará do Sul",
	"Cambé",
	"Cambira",
	"Camboriú",
	"Campestre da Serra",
	"Campina da Lagoa",
	"Campina das Missões",
	"Campina do Simão",
	"Campina Grande do Sul",
	"Campinas do Sul",
	"Campo Alegre",
	"Campo Belo do Sul",
	"Campo Bom",
	"Campo Bonito",
	"Campo do Tenente",
	"Campo Erê",
	"Campo Largo",
	"Campo Magro",
	"Campo Mourão",
	"Campo Novo",
	"Campos Borges",
	"Campos Novos",
	"Candelária",
	"Cândido de Abreu",
	"Cândido Godói",
	"Candiota",
	"Candói",
	"Canela",
	"Canelinha",
	"Canguçu",
	"Canoas",
	"Canoinhas",
	"Cantagalo",
	"Canudos do Vale",
	"Capanema",
	"Capão Alto",
	"Capão Bonito do Sul",
	"Capão da Canoa",
	"Capão do Cipó",
	"Capão do Leão",
	"Capela de Santana",
	"Capinzal",
	"Capitão",
	"Capitão Leônidas Marques",
	"Capivari de Baixo",
	"Capivari do Sul",
	"Caraá",
	"Carambeí",
	"Carazinho",
	"Carlópolis",
	"Carlos Barbosa",
	"Carlos Gomes",
	"Casca",
	"Cascavel",
	"Caseiros",
	"Castro",
	"Catanduvas",
	"Catuípe",
	"Caxambu do Sul",
	"Caxias do Sul",
	"Celso Ramos",
	"Centenário",
	"Centenário do Sul",
	"Cerrito",
	"Cerro Azul",
	"Cerro Branco",
	"Cerro Grande",
	"Cerro Grande do Sul",
	"Cerro Largo",
	"Cerro Negro",
	"Céu Azul",
	"Chapada",
	"Chapadão do Lageado",
	"Chapecó",
	"Charqueadas",
	"Charrua",
	"Chiapetta",
	"Chopinzinho",
	"Chuí",
	"Chuvisca",
	"Cianorte",
	"Cidade Gaúcha",
	"Cidreira",
	"Ciríaco",
	"Clevelândia",
	"Cocal do Sul",
	"Colinas",
	"Colombo",
	"Colorado",
	"Concórdia",
	"Condor",
	"Congonhinhas",
	"Conselheiro Mairinck",
	"Constantina",
	"Contenda",
	"Coqueiro Baixo",
	"Coqueiros do Sul",
	"Corbélia",
	"Cordilheira Alta",
	"Cornélio Procópio",
	"Coronel Barros",
	"Coronel Bicaco",
	"Coronel Domingos Soares",
	"Coronel Freitas",
	"Coronel Martins",
	"Coronel Pilar",
	"Coronel Vivida",
	"Correia Pinto",
	"Corumbataí do Sul",
	"Corupá",
	"Cotiporã",
	"Coxilha",
	"Criciúma",
	"Crissiumal",
	"Cristal",
	"Cristal do Sul",
	"Cruz Alta",
	"Cruz Machado",
	"Cruzaltense",
	"Cruzeiro do Iguaçu",
	"Cruzeiro do Oeste",
	"Cruzeiro do Sul",
	"Cruzmaltina",
	"Cunha Porã",
	"Cunhataí",
	"Curitiba",
	"Curitibanos",
	"Curiúva",
	"David Canabarro",
	"Derrubadas",
	"Descanso",
	"Dezesseis de Novembro",
	"Diamante D'Oeste",
	"Diamante do Norte",
	"Diamante do Sul",
	"Dilermando de Aguiar",
	"Dionísio Cerqueira",
	"Dois Irmãos",
	"Dois Irmãos das Missões",
	"Dois Lajeados",
	"Dois Vizinhos",
	"Dom Feliciano",
	"Dom Pedrito",
	"Dom Pedro de Alcântara",
	"Dona Emma",
	"Dona Francisca",
	"Douradina",
	"Doutor Camargo",
	"Doutor Maurício Cardoso",
	"Doutor Pedrinho",
	"Doutor Ricardo",
	"Doutor Ulysses",
	"Eldorado do Sul",
	"Encantado",
	"Encruzilhada do Sul",
	"Enéas Marques",
	"Engenheiro Beltrão",
	"Engenho Velho",
	"Entre Rios",
	"Entre Rios do Oeste",
	"Entre Rios do Sul",
	"Entre-Ijuís",
	"Erebango",
	"Erechim",
	"Ermo",
	"Ernestina",
	"Erval Grande",
	"Erval Seco",
	"Erval Velho",
	"Esmeralda",
	"Esperança do Sul",
	"Esperança Nova",
	"Espigão Alto do Iguaçu",
	"Espumoso",
	"Estação",
	"Estância Velha",
	"Esteio",
	"Estrela",
	"Estrela Velha",
	"Eugênio de Castro",
	"Fagundes Varela",
	"Farol",
	"Farroupilha",
	"Faxinal",
	"Faxinal do Soturno",
	"Faxinal dos Guedes",
	"Faxinalzinho",
	"Fazenda Rio Grande",
	"Fazenda Vilanova",
	"Feliz",
	"Fênix",
	"Fernandes Pinheiro",
	"Figueira",
	"Flor da Serra do Sul",
	"Flor do Sertão",
	"Floraí",
	"Flores da Cunha",
	"Floresta",
	"Florestópolis",
	"Floriano Peixoto",
	"Florianópolis",
	"Flórida",
	"Fontoura Xavier",
	"Formigueiro",
	"Formosa do Oeste",
	"Formosa do Sul",
	"Forquetinha",
	"Forquilhinha",
	"Fortaleza dos Valos",
	"Foz do Iguaçu",
	"Foz do Jordão",
	"Fraiburgo",
	"Francisco Alves",
	"Francisco Beltrão",
	"Frederico Westphalen",
	"Frei Rogério",
	"Galvão",
	"Garibaldi",
	"Garopaba",
	"Garruchos",
	"Garuva",
	"Gaspar",
	"Gaurama",
	"General Câmara",
	"General Carneiro",
	"Gentil",
	"Getúlio Vargas",
	"Giruá",
	"Glorinha",
	"Godoy Moreira",
	"Goioerê",
	"Goioxim",
	"Governador Celso Ramos",
	"Gramado",
	"Gramado dos Loureiros",
	"Gramado Xavier",
	"Grandes Rios",
	"Grão-Pará",
	"Gravataí",
	"Gravatal",
	"Guabiju",
	"Guabiruba",
	"Guaíba",
	"Guaíra",
	"Guairaçá",
	"Guamiranga",
	"Guapirama",
	"Guaporé",
	"Guaporema",
	"Guaraci",
	"Guaraciaba",
	"Guaramirim",
	"Guarani das Missões",
	"Guaraniaçu",
	"Guarapuava",
	"Guaraqueçaba",
	"Guaratuba",
	"Guarujá do Sul",
	"Guatambú",
	"Harmonia",
	"Herval",
	"Herval d'Oeste",
	"Herveiras",
	"Honório Serpa",
	"Horizontina",
	"Hulha Negra",
	"Humaitá",
	"Ibaiti",
	"Ibarama",
	"Ibema",
	"Ibiaçá",
	"Ibiam",
	"Ibicaré",
	"Ibiporã",
	"Ibiraiaras",
	"Ibirama",
	"Ibirapuitã",
	"Ibirubá",
	"Içara",
	"Icaraíma",
	"Igrejinha",
	"Iguaraçu",
	"Iguatu",
	"Ijuí",
	"Ilhota",
	"Ilópolis",
	"Imaruí",
	"Imbaú",
	"Imbé",
	"Imbituba",
	"Imbituva",
	"Imbuia",
	"Imigrante",
	"Inácio Martins",
	"Inajá",
	"Indaial",
	"Independência",
	"Indianópolis",
	"Inhacorá",
	"Iomerê",
	"Ipê",
	"Ipira",
	"Ipiranga",
	"Ipiranga do Sul",
	"Iporã",
	"Iporã do Oeste",
	"Ipuaçu",
	"Ipumirim",
	"Iracema do Oeste",
	"Iraceminha",
	"Iraí",
	"Irani",
	"Irati",
	"Iretama",
	"Irineópolis",
	"Itá",
	"Itaara",
	"Itacurubi",
	"Itaguajé",
	"Itaiópolis",
	"Itaipulândia",
	"Itajaí",
	"Itambaracá",
	"Itambé",
	"Itapejara d'Oeste",
	"Itapema",
	"Itaperuçu",
	"Itapiranga",
	"Itapoá",
	"Itapuca",
	"Itaqui",
	"Itati",
	"Itatiba do Sul",
	"Itaúna do Sul",
	"Ituporanga",
	"Ivaí",
	"Ivaiporã",
	"Ivaté",
	"Ivatuba",
	"Ivorá",
	"Ivoti",
	"Jaborá",
	"Jaboti",
	"Jaboticaba",
	"Jacarezinho",
	"Jacinto Machado",
	"Jacuizinho",
	"Jacutinga",
	"Jaguapitã",
	"Jaguarão",
	"Jaguari",
	"Jaguariaíva",
	"Jaguaruna",
	"Jandaia do Sul",
	"Janiópolis",
	"Japira",
	"Japurá",
	"Jaquirana",
	"Jaraguá do Sul",
	"Jardim Alegre",
	"Jardim Olinda",
	"Jardinópolis",
	"Jari",
	"Jataizinho",
	"Jesuítas",
	"Joaçaba",
	"Joaquim Távora",
	"Jóia",
	"Joinville",
	"José Boiteux",
	"Júlio de Castilhos",
	"Jundiaí do Sul",
	"Jupiá",
	"Juranda",
	"Jussara",
	"Kaloré",
	"Lacerdópolis",
	"Lages",
	"Lagoa Bonita do Sul",
	"Lagoa dos Três Cantos",
	"Lagoa Vermelha",
	"Lagoão",
	"Laguna",
	"Lajeado",
	"Lajeado do Bugre",
	"Lajeado Grande",
	"Lapa",
	"Laranjal",
	"Laranjeiras do Sul",
	"Laurentino",
	"Lauro Müller",
	"Lavras do Sul",
	"Lebon Régis",
	"Leoberto Leal",
	"Leópolis",
	"Liberato Salzano",
	"Lidianópolis",
	"Lindoeste",
	"Lindóia do Sul",
	"Lindolfo Collor",
	"Linha Nova",
	"Loanda",
	"Lobato",
	"Londrina",
	"Lontras",
	"Luiz Alves",
	"Luiziana",
	"Lunardelli",
	"Lupionópolis",
	"Luzerna",
	"Maçambará",
	"Machadinho",
	"Macieira",
	"Mafra",
	"Major Gercino",
	"Major Vieira",
	"Mallet",
	"Mamborê",
	"Mampituba",
	"Mandaguaçu",
	"Mandaguari",
	"Mandirituba",
	"Manfrinópolis",
	"Mangueirinha",
	"Manoel Ribas",
	"Manoel Viana",
	"Maquiné",
	"Maracajá",
	"Maratá",
	"Marau",
	"Maravilha",
	"Marcelino Ramos",
	"Marechal Cândido Rondon",
	"Marema",
	"Maria Helena",
	"Marialva",
	"Mariana Pimentel",
	"Mariano Moro",
	"Marilândia do Sul",
	"Marilena",
	"Mariluz",
	"Maringá",
	"Mariópolis",
	"Maripá",
	"Marmeleiro",
	"Marques de Souza",
	"Marquinho",
	"Marumbi",
	"Massaranduba",
	"Mata",
	"Matelândia",
	"Matinhos",
	"Mato Castelhano",
	"Mato Leitão",
	"Mato Queimado",
	"Mato Rico",
	"Matos Costa",
	"Mauá da Serra",
	"Maximiliano de Almeida",
	"Medianeira",
	"Meleiro",
	"Mercedes",
	"Minas do Leão",
	"Mirador",
	"Miraguaí",
	"Miraselva",
	"Mirim Doce",
	"Missal",
	"Modelo",
	"Mondaí",
	"Montauri",
	"Monte Alegre dos Campos",
	"Monte Belo do Sul",
	"Monte Carlo",
	"Monte Castelo",
	"Montenegro",
	"Moreira Sales",
	"Mormaço",
	"Morretes",
	"Morrinhos do Sul",
	"Morro da Fumaça",
	"Morro Grande",
	"Morro Redondo",
	"Morro Reuter",
	"Mostardas",
	"Muçum",
	"Muitos Capões",
	"Muliterno",
	"Munhoz de Melo",
	"Não-Me-Toque",
	"Navegantes",
	"Nicolau Vergueiro",
	"Nonoai",
	"Nossa Senhora das Graças",
	"Nova Aliança do Ivaí",
	"Nova Alvorada",
	"Nova América da Colina",
	"Nova Araçá",
	"Nova Aurora",
	"Nova Bassano",
	"Nova Boa Vista",
	"Nova Bréscia",
	"Nova Candelária",
	"Nova Cantu",
	"Nova Erechim",
	"Nova Esperança",
	"Nova Esperança do Sudoeste",
	"Nova Esperança do Sul",
	"Nova Fátima",
	"Nova Hartz",
	"Nova Itaberaba",
	"Nova Laranjeiras",
	"Nova Londrina",
	"Nova Olímpia",
	"Nova Pádua",
	"Nova Palma",
	"Nova Petrópolis",
	"Nova Prata",
	"Nova Prata do Iguaçu",
	"Nova Ramada",
	"Nova Roma do Sul",
	"Nova Santa Bárbara",
	"Nova Santa Rita",
	"Nova Santa Rosa",
	"Nova Tebas",
	"Nova Trento",
	"Nova Veneza",
	"Novo Barreiro",
	"Novo Cabrais",
	"Novo Hamburgo",
	"Novo Horizonte",
	"Novo Itacolomi",
	"Novo Machado",
	"Novo Tiradentes",
	"Novo Xingu",
	"Orleans",
	"Ortigueira",
	"Osório",
	"Otacílio Costa",
	"Ourizona",
	"Ouro",
	"Ouro Verde",
	"Ouro Verde do Oeste",
	"Paial",
	"Paiçandu",
	"Paim Filho",
	"Painel",
	"Palhoça",
	"Palma Sola",
	"Palmares do Sul",
	"Palmas",
	"Palmeira",
	"Palmeira das Missões",
	"Palmital",
	"Palmitinho",
	"Palmitos",
	"Palotina",
	"Panambi",
	"Pantano Grande",
	"Papanduva",
	"Paraí",
	"Paraíso",
	"Paraíso do Norte",
	"Paraíso do Sul",
	"Paranacity",
	"Paranaguá",
	"Paranapoema",
	"Paranavaí",
	"Pareci Novo",
	"Parobé",
	"Passa Sete",
	"Passo de Torres",
	"Passo do Sobrado",
	"Passo Fundo",
	"Passos Maia",
	"Pato Bragado",
	"Pato Branco",
	"Paula Freitas",
	"Paulo Bento",
	"Paulo Frontin",
	"Paulo Lopes",
	"Paverama",
	"Peabiru",
	"Pedras Altas",
	"Pedras Grandes",
	"Pedro Osório",
	"Pejuçara",
	"Pelotas",
	"Penha",
	"Peritiba",
	"Perobal",
	"Pérola",
	"Pérola d'Oeste",
	"Pescaria Brava",
	"Petrolândia",
	"Picada Café",
	"Piên",
	"Pinhais",
	"Pinhal",
	"Pinhal da Serra",
	"Pinhal de São Bento",
	"Pinhal Grande",
	"Pinhalão",
	"Pinhalzinho",
	"Pinhão",
	"Pinheirinho do Vale",
	"Pinheiro Machado",
	"Pinheiro Preto",
	"Pinto Bandeira",
	"Piraí do Sul",
	"Pirapó",
	"Piraquara",
	"Piratini",
	"Piratuba",
	"Pitanga",
	"Pitangueiras",
	"Planaltina do Paraná",
	"Planalto",
	"Planalto Alegre",
	"Poço das Antas",
	"Pomerode",
	"Ponta Grossa",
	"Pontal do Paraná",
	"Pontão",
	"Ponte Alta",
	"Ponte Alta do Norte",
	"Ponte Preta",
	"Ponte Serrada",
	"Porecatu",
	"Portão",
	"Porto Alegre",
	"Porto Amazonas",
	"Porto Barreiro",
	"Porto Belo",
	"Porto Lucena",
	"Porto Mauá",
	"Porto Rico",
	"Porto União",
	"Porto Vera Cruz",
	"Porto Vitória",
	"Porto Xavier",
	"Pouso Novo",
	"Pouso Redondo",
	"Prado Ferreira",
	"Praia Grande",
	"Pranchita",
	"Presidente Castello Branco",
	"Presidente Castelo Branco",
	"Presidente Getúlio",
	"Presidente Lucena",
	"Presidente Nereu",
	"Primeiro de Maio",
	"Princesa",
	"Progresso",
	"Protásio Alves",
	"Prudentópolis",
	"Putinga",
	"Quaraí",
	"Quarto Centenário",
	"Quatiguá",
	"Quatro Barras",
	"Quatro Irmãos",
	"Quatro Pontes",
	"Quedas do Iguaçu",
	"Querência do Norte",
	"Quevedos",
	"Quilombo",
	"Quinta do Sol",
	"Quinze de Novembro",
	"Quitandinha",
	"Ramilândia",
	"Rancho Alegre",
	"Rancho Alegre D'Oeste",
	"Rancho Queimado",
	"Realeza",
	"Rebouças",
	"Redentora",
	"Relvado",
	"Renascença",
	"Reserva",
	"Reserva do Iguaçu",
	"Restinga Sêca",
	"Ribeirão Claro",
	"Ribeirão do Pinhal",
	"Rio Azul",
	"Rio Bom",
	"Rio Bonito do Iguaçu",
	"Rio Branco do Ivaí",
	"Rio Branco do Sul",
	"Rio das Antas",
	"Rio do Campo",
	"Rio do Oeste",
	"Rio do Sul",
	"Rio dos Cedros",
	"Rio dos Índios",
	"Rio Fortuna",
	"Rio Grande",
	"Rio Negrinho",
	"Rio Negro",
	"Rio Pardo",
	"Rio Rufino",
	"Riozinho",
	"Riqueza",
	"Roca Sales",
	"Rodeio",
	"Rodeio Bonito",
	"Rolador",
	"Rolândia",
	"Rolante",
	"Romelândia",
	"Roncador",
	"Ronda Alta",
	"Rondinha",
	"Rondon",
	"Roque Gonzales",
	"Rosário do Ivaí",
	"Rosário do Sul",
	"Sabáudia",
	"Sagrada Família",
	"Saldanha Marinho",
	"Salete",
	"Salgado Filho",
	"Saltinho",
	"Salto do Itararé",
	"Salto do Jacuí",
	"Salto do Lontra",
	"Salto Veloso",
	"Salvador das Missões",
	"Salvador do Sul",
	"Sananduva",
	"Sangão",
	"Sant'Ana do Livramento",
	"Santa Amélia",
	"Santa Bárbara do Sul",
	"Santa Cecília",
	"Santa Cecília do Pavão",
	"Santa Cecília do Sul",
	"Santa Clara do Sul",
	"Santa Cruz de Monte Castelo",
	"Santa Cruz do Sul",
	"Santa Fé",
	"Santa Helena",
	"Santa Inês",
	"Santa Isabel do Ivaí",
	"Santa Izabel do Oeste",
	"Santa Lúcia",
	"Santa Margarida do Sul",
	"Santa Maria",
	"Santa Maria do Herval",
	"Santa Maria do Oeste",
	"Santa Mariana",
	"Santa Mônica",
	"Santa Rosa",
	"Santa Rosa de Lima",
	"Santa Rosa do Sul",
	"Santa Tereza",
	"Santa Tereza do Oeste",
	"Santa Terezinha",
	"Santa Terezinha de Itaipu",
	"Santa Terezinha do Progresso",
	"Santa Vitória do Palmar",
	"Santana da Boa Vista",
	"Santana do Itararé",
	"Santiago",
	"Santiago do Sul",
	"Santo Amaro da Imperatriz",
	"Santo Ângelo",
	"Santo Antônio da Patrulha",
	"Santo Antônio da Platina",
	"Santo Antônio das Missões",
	"Santo Antônio do Caiuá",
	"Santo Antônio do Palma",
	"Santo Antônio do Paraíso",
	"Santo Antônio do Planalto",
	"Santo Antônio do Sudoeste",
	"Santo Augusto",
	"Santo Cristo",
	"Santo Expedito do Sul",
	"Santo Inácio",
	"São Bento do Sul",
	"São Bernardino",
	"São Bonifácio",
	"São Borja",
	"São Carlos",
	"São Carlos do Ivaí",
	"São Cristóvão do Sul",
	"São Domingos",
	"São Domingos do Sul",
	"São Francisco de Assis",
	"São Francisco de Paula",
	"São Francisco do Sul",
	"São Gabriel",
	"São Jerônimo",
	"São Jerônimo da Serra",
	"São João",
	"São João Batista",
	"São João da Urtiga",
	"São João do Caiuá",
	"São João do Itaperiú",
	"São João do Ivaí",
	"São João do Oeste",
	"São João do Polêsine",
	"São João do Sul",
	"São João do Triunfo",
	"São Joaquim",
	"São Jorge",
	"São Jorge d'Oeste",
	"São Jorge do Ivaí",
	"São Jorge do Patrocínio",
	"São José",
	"São José da Boa Vista",
	"São José das Missões",
	"São José das Palmeiras",
	"São José do Cedro",
	"São José do Cerrito",
	"São José do Herval",
	"São José do Hortêncio",
	"São José do Inhacorá",
	"São José do Norte",
	"São José do Ouro",
	"São José do Sul",
	"São José dos Ausentes",
	"São José dos Pinhais",
	"São Leopoldo",
	"São Lourenço do Oeste",
	"São Lourenço do Sul",
	"São Ludgero",
	"São Luiz Gonzaga",
	"São Manoel do Paraná",
	"São Marcos",
	"São Martinho",
	"São Martinho da Serra",
	"São Mateus do Sul",
	"São Miguel da Boa Vista",
	"São Miguel das Missões",
	"São Miguel do Iguaçu",
	"São Miguel do Oeste",
	"São Nicolau",
	"São Paulo das Missões",
	"São Pedro da Serra",
	"São Pedro das Missões",
	"São Pedro de Alcântara",
	"São Pedro do Butiá",
	"São Pedro do Iguaçu",
	"São Pedro do Ivaí",
	"São Pedro do Paraná",
	"São Pedro do Sul",
	"São Sebastião da Amoreira",
	"São Sebastião do Caí",
	"São Sepé",
	"São Tomé",
	"São Valentim",
	"São Valentim do Sul",
	"São Valério do Sul",
	"São Vendelino",
	"São Vicente do Sul",
	"Sapiranga",
	"Sapopema",
	"Sapucaia do Sul",
	"Sarandi",
	"Saudade do Iguaçu",
	"Saudades",
	"Schroeder",
	"Seara",
	"Seberi",
	"Sede Nova",
	"Segredo",
	"Selbach",
	"Senador Salgado Filho",
	"Sengés",
	"Sentinela do Sul",
	"Serafina Corrêa",
	"Sério",
	"Serra Alta",
	"Serranópolis do Iguaçu",
	"Sertaneja",
	"Sertanópolis",
	"Sertão",
	"Sertão Santana",
	"Sete de Setembro",
	"Severiano de Almeida",
	"Siderópolis",
	"Silveira Martins",
	"Sinimbu",
	"Siqueira Campos",
	"Sobradinho",
	"Soledade",
	"Sombrio",
	"Sul Brasil",
	"Sulina",
	"Tabaí",
	"Taió",
	"Tamarana",
	"Tamboara",
	"Tangará",
	"Tapejara",
	"Tapera",
	"Tapes",
	"Tapira",
	"Taquara",
	"Taquari",
	"Taquaruçu do Sul",
	"Tavares",
	"Teixeira Soares",
	"Telêmaco Borba",
	"Tenente Portela",
	"Terra Boa",
	"Terra de Areia",
	"Terra Rica",
	"Terra Roxa",
	"Teutônia",
	"Tibagi",
	"Tigrinhos",
	"Tijucas",
	"Tijucas do Sul",
	"Timbé do Sul",
	"Timbó",
	"Timbó Grande",
	"Tio Hugo",
	"Tiradentes do Sul",
	"Toledo",
	"Tomazina",
	"Toropi",
	"Torres",
	"Tramandaí",
	"Travesseiro",
	"Três Arroios",
	"Três Barras",
	"Três Barras do Paraná",
	"Três Cachoeiras",
	"Três Coroas",
	"Três de Maio",
	"Três Forquilhas",
	"Três Palmeiras",
	"Três Passos",
	"Treviso",
	"Treze de Maio",
	"Treze Tílias",
	"Trindade do Sul",
	"Triunfo",
	"Trombudo Central",
	"Tubarão",
	"Tucunduva",
	"Tunápolis",
	"Tunas",
	"Tunas do Paraná",
	"Tuneiras do Oeste",
	"Tupanci do Sul",
	"Tupanciretã",
	"Tupandi",
	"Tuparendi",
	"Tupãssi",
	"Turuçu",
	"Turvo",
	"Ubiratã",
	"Ubiretama",
	"Umuarama",
	"União da Serra",
	"União da Vitória",
	"União do Oeste",
	"Uniflor",
	"Unistalda",
	"Uraí",
	"Urubici",
	"Uruguaiana",
	"Urupema",
	"Urussanga",
	"Vacaria",
	"Vale do Sol",
	"Vale Real",
	"Vale Verde",
	"Vanini",
	"Vargeão",
	"Vargem",
	"Vargem Bonita",
	"Venâncio Aires",
	"Ventania",
	"Vera Cruz",
	"Vera Cruz do Oeste",
	"Veranópolis",
	"Verê",
	"Vespasiano Corrêa",
	"Viadutos",
	"Viamão",
	"Vicente Dutra",
	"Victor Graeff",
	"Vidal Ramos",
	"Videira",
	"Vila Flores",
	"Vila Lângaro",
	"Vila Maria",
	"Vila Nova do Sul",
	"Virmond",
	"Vista Alegre",
	"Vista Alegre do Prata",
	"Vista Gaúcha",
	"Vitor Meireles",
	"Vitória das Missões",
	"Vitorino",
	"Wenceslau Braz",
	"Westfália",
	"Witmarsum",
	"Xambrê",
	"Xangri-lá",
	"Xanxerê",
	"Xavantina",
	"Xaxim",
	"Zortéa",
	"Abadia dos Dourados",
	"Abaeté",
	"Abre Campo",
	"Acaiaca",
	"Açucena",
	"Adamantina",
	"Adolfo",
	"Afonso Cláudio",
	"Água Boa",
	"Água Comprida",
	"Água Doce do Norte",
	"Aguaí",
	"Aguanil",
	"Águas da Prata",
	"Águas de Lindóia",
	"Águas de Santa Bárbara",
	"Águas de São Pedro",
	"Águas Formosas",
	"Águas Vermelhas",
	"Agudos",
	"Águia Branca",
	"Aimorés",
	"Aiuruoca",
	"Alagoa",
	"Alambari",
	"Albertina",
	"Alegre",
	"Além Paraíba",
	"Alfenas",
	"Alfredo Chaves",
	"Alfredo Marcondes",
	"Alfredo Vasconcelos",
	"Almenara",
	"Alpercata",
	"Alpinópolis",
	"Altair",
	"Alterosa",
	"Altinópolis",
	"Alto Caparaó",
	"Alto Jequitibá",
	"Alto Rio Doce",
	"Alto Rio Novo",
	"Alumínio",
	"Alvarenga",
	"Álvares Florence",
	"Álvares Machado",
	"Álvaro de Carvalho",
	"Alvinlândia",
	"Alvinópolis",
	"Alvorada de Minas",
	"Americana",
	"Américo Brasiliense",
	"Américo de Campos",
	"Amparo",
	"Amparo do Serra",
	"Analândia",
	"Andradas",
	"Andradina",
	"Andrelândia",
	"Angatuba",
	"Angelândia",
	"Angra dos Reis",
	"Anhembi",
	"Anhumas",
	"Antônio Dias",
	"Antônio Prado de Minas",
	"Aparecida",
	"Aparecida d'Oeste",
	"Aperibé",
	"Apiacá",
	"Apiaí",
	"Araçaí",
	"Araçariguama",
	"Araçatuba",
	"Aracitaba",
	"Araçoiaba da Serra",
	"Aracruz",
	"Araçuaí",
	"Araguari",
	"Aramina",
	"Arandu",
	"Arantina",
	"Arapeí",
	"Araponga",
	"Araporã",
	"Arapuá",
	"Araraquara",
	"Araras",
	"Araruama",
	"Araújos",
	"Araxá",
	"Arceburgo",
	"Arco-Íris",
	"Arcos",
	"Areado",
	"Areal",
	"Arealva",
	"Areias",
	"Areiópolis",
	"Argirita",
	"Aricanduva",
	"Arinos",
	"Ariranha",
	"Armação dos Búzios",
	"Arraial do Cabo",
	"Artur Nogueira",
	"Arujá",
	"Aspásia",
	"Assis",
	"Astolfo Dutra",
	"Ataléia",
	"Atibaia",
	"Atílio Vivácqua",
	"Augusto de Lima",
	"Auriflama",
	"Avaí",
	"Avanhandava",
	"Avaré",
	"Bady Bassitt",
	"Baependi",
	"Baixo Guandu",
	"Balbinos",
	"Baldim",
	"Bálsamo",
	"Bambuí",
	"Bananal",
	"Bandeira",
	"Bandeira do Sul",
	"Barão de Antonina",
	"Barão de Cocais",
	"Barão do Monte Alto",
	"Barbacena",
	"Barbosa",
	"Bariri",
	"Barra de São Francisco",
	"Barra do Chapéu",
	"Barra do Piraí",
	"Barra do Turvo",
	"Barra Longa",
	"Barra Mansa",
	"Barretos",
	"Barrinha",
	"Barroso",
	"Barueri",
	"Bastos",
	"Batatais",
	"Bauru",
	"Bebedouro",
	"Bela Vista de Minas",
	"Belford Roxo",
	"Belmiro Braga",
	"Belo Horizonte",
	"Belo Oriente",
	"Belo Vale",
	"Bento de Abreu",
	"Berilo",
	"Berizal",
	"Bernardino de Campos",
	"Bertioga",
	"Bertópolis",
	"Betim",
	"Bias Fortes",
	"Bicas",
	"Bilac",
	"Biquinhas",
	"Birigui",
	"Biritiba Mirim",
	"Boa Esperança do Sul",
	"Bocaina",
	"Bocaina de Minas",
	"Bocaiúva",
	"Bofete",
	"Boituva",
	"Bom Despacho",
	"Bom Jardim",
	"Bom Jardim de Minas",
	"Bom Jesus da Penha",
	"Bom Jesus do Amparo",
	"Bom Jesus do Galho",
	"Bom Jesus do Itabapoana",
	"Bom Jesus do Norte",
	"Bom Jesus dos Perdões",
	"Bom Repouso",
	"Bom Sucesso de Itararé",
	"Bonfim",
	"Bonfinópolis de Minas",
	"Bonito de Minas",
	"Borá",
	"Boracéia",
	"Borborema",
	"Borda da Mata",
	"Borebi",
	"Botelhos",
	"Botucatu",
	"Botumirim",
	"Bragança Paulista",
	"Brás Pires",
	"Brasilândia de Minas",
	"Brasília de Minas",
	"Braúna",
	"Braúnas",
	"Brazópolis",
	"Brejetuba",
	"Brejo Alegre",
	"Brodowski",
	"Brotas",
	"Brumadinho",
	"Bueno Brandão",
	"Buenópolis",
	"Bugre",
	"Buri",
	"Buritama",
	"Buritis",
	"Buritizal",
	"Buritizeiro",
	"Cabeceira Grande",
	"Cabo Frio",
	"Cabo Verde",
	"Cabrália Paulista",
	"Cabreúva",
	"Caçapava",
	"Cachoeira da Prata",
	"Cachoeira de Minas",
	"Cachoeira de Pajeú",
	"Cachoeira Dourada",
	"Cachoeira Paulista",
	"Cachoeiras de Macacu",
	"Cachoeiro de Itapemirim",
	"Caconde",
	"Caetanópolis",
	"Caeté",
	"Caiabu",
	"Caiana",
	"Caieiras",
	"Caiuá",
	"Cajamar",
	"Cajati",
	"Cajobi",
	"Cajuri",
	"Cajuru",
	"Caldas",
	"Camacho",
	"Camanducaia",
	"Cambuci",
	"Cambuí",
	"Cambuquira",
	"Campanário",
	"Campanha",
	"Campestre",
	"Campina do Monte Alegre",
	"Campina Verde",
	"Campinas",
	"Campo Azul",
	"Campo Belo",
	"Campo do Meio",
	"Campo Florido",
	"Campo Limpo Paulista",
	"Campos Altos",
	"Campos do Jordão",
	"Campos dos Goytacazes",
	"Campos Gerais",
	"Campos Novos Paulista",
	"Cana Verde",
	"Canaã",
	"Cananéia",
	"Canápolis",
	"Canas",
	"Candeias",
	"Cândido Mota",
	"Cândido Rodrigues",
	"Canitar",
	"Capão Bonito",
	"Caparaó",
	"Capela do Alto",
	"Capela Nova",
	"Capelinha",
	"Capetinga",
	"Capim Branco",
	"Capinópolis",
	"Capitão Andrade",
	"Capitão Enéas",
	"Capitólio",
	"Capivari",
	"Caputira",
	"Caraguatatuba",
	"Caraí",
	"Caranaíba",
	"Carandaí",
	"Carangola",
	"Carapebus",
	"Carapicuíba",
	"Caratinga",
	"Carbonita",
	"Cardoso",
	"Cardoso Moreira",
	"Careaçu",
	"Cariacica",
	"Carlos Chagas",
	"Carmésia",
	"Carmo",
	"Carmo da Cachoeira",
	"Carmo da Mata",
	"Carmo de Minas",
	"Carmo do Cajuru",
	"Carmo do Paranaíba",
	"Carmo do Rio Claro",
	"Carmópolis de Minas",
	"Carneirinho",
	"Carrancas",
	"Carvalhópolis",
	"Carvalhos",
	"Casa Branca",
	"Casa Grande",
	"Cascalho Rico",
	"Casimiro de Abreu",
	"Cássia",
	"Cássia dos Coqueiros",
	"Castelo",
	"Castilho",
	"Cataguases",
	"Catanduva",
	"Catas Altas",
	"Catas Altas da Noruega",
	"Catiguá",
	"Catuji",
	"Catuti",
	"Caxambu",
	"Cedral",
	"Cedro do Abaeté",
	"Central de Minas",
	"Centralina",
	"Cerqueira César",
	"Cerquilho",
	"Cesário Lange",
	"Chácara",
	"Chalé",
	"Chapada do Norte",
	"Chapada Gaúcha",
	"Charqueada",
	"Chavantes",
	"Chiador",
	"Cipotânea",
	"Claraval",
	"Claro dos Poções",
	"Cláudio",
	"Clementina",
	"Coimbra",
	"Colatina",
	"Colina",
	"Colômbia",
	"Coluna",
	"Comendador Gomes",
	"Comendador Levy Gasparian",
	"Comercinho",
	"Conceição da Aparecida",
	"Conceição da Barra",
	"Conceição da Barra de Minas",
	"Conceição das Alagoas",
	"Conceição das Pedras",
	"Conceição de Ipanema",
	"Conceição de Macabu",
	"Conceição do Castelo",
	"Conceição do Mato Dentro",
	"Conceição do Pará",
	"Conceição do Rio Verde",
	"Conceição dos Ouros",
	"Conchal",
	"Conchas",
	"Cônego Marinho",
	"Confins",
	"Congonhal",
	"Congonhas",
	"Congonhas do Norte",
	"Conquista",
	"Conselheiro Lafaiete",
	"Conselheiro Pena",
	"Consolação",
	"Contagem",
	"Coqueiral",
	"Coração de Jesus",
	"Cordeiro",
	"Cordeirópolis",
	"Cordisburgo",
	"Cordislândia",
	"Corinto",
	"Coroaci",
	"Coroados",
	"Coromandel",
	"Coronel Fabriciano",
	"Coronel Macedo",
	"Coronel Murta",
	"Coronel Pacheco",
	"Coronel Xavier Chaves",
	"Córrego Danta",
	"Córrego do Bom Jesus",
	"Córrego Fundo",
	"Córrego Novo",
	"Corumbataí",
	"Cosmópolis",
	"Cosmorama",
	"Cotia",
	"Couto de Magalhães de Minas",
	"Cravinhos",
	"Crisólita",
	"Cristais",
	"Cristais Paulista",
	"Cristália",
	"Cristiano Otoni",
	"Cristina",
	"Crucilândia",
	"Cruzália",
	"Cruzeiro",
	"Cruzeiro da Fortaleza",
	"Cruzília",
	"Cubatão",
	"Cunha",
	"Cuparaque",
	"Curral de Dentro",
	"Curvelo",
	"Datas",
	"Delfim Moreira",
	"Delfinópolis",
	"Delta",
	"Descalvado",
	"Descoberto",
	"Desterro de Entre Rios",
	"Desterro do Melo",
	"Diadema",
	"Diamantina",
	"Diogo de Vasconcelos",
	"Dionísio",
	"Dirce Reis",
	"Divinésia",
	"Divino",
	"Divino das Laranjeiras",
	"Divino de São Lourenço",
	"Divinolândia",
	"Divinolândia de Minas",
	"Divinópolis",
	"Divisa Alegre",
	"Divisa Nova",
	"Divisópolis",
	"Dobrada",
	"Dois Córregos",
	"Dolcinópolis",
	"Dom Bosco",
	"Dom Cavati",
	"Dom Joaquim",
	"Dom Silvério",
	"Dom Viçoso",
	"Domingos Martins",
	"Dona Euzébia",
	"Dores de Campos",
	"Dores de Guanhães",
	"Dores do Indaiá",
	"Dores do Rio Preto",
	"Dores do Turvo",
	"Doresópolis",
	"Dourado",
	"Douradoquara",
	"Dracena",
	"Duartina",
	"Duas Barras",
	"Dumont",
	"Duque de Caxias",
	"Durandé",
	"Echaporã",
	"Ecoporanga",
	"Eldorado",
	"Elias Fausto",
	"Elisiário",
	"Elói Mendes",
	"Embaúba",
	"Embu das Artes",
	"Embu-Guaçu",
	"Emilianópolis",
	"Engenheiro Caldas",
	"Engenheiro Coelho",
	"Engenheiro Navarro",
	"Engenheiro Paulo de Frontin",
	"Entre Folhas",
	"Entre Rios de Minas",
	"Ervália",
	"Esmeraldas",
	"Espera Feliz",
	"Espinosa",
	"Espírito Santo do Dourado",
	"Espírito Santo do Pinhal",
	"Espírito Santo do Turvo",
	"Estiva",
	"Estiva Gerbi",
	"Estrela d'Oeste",
	"Estrela Dalva",
	"Estrela do Indaiá",
	"Estrela do Norte",
	"Estrela do Sul",
	"Euclides da Cunha Paulista",
	"Eugenópolis",
	"Ewbank da Câmara",
	"Extrema",
	"Fama",
	"Faria Lemos",
	"Fartura",
	"Felício dos Santos",
	"Felisburgo",
	"Felixlândia",
	"Fernandes Tourinho",
	"Fernando Prestes",
	"Fernandópolis",
	"Fernão",
	"Ferraz de Vasconcelos",
	"Ferros",
	"Fervedouro",
	"Flora Rica",
	"Floreal",
	"Florestal",
	"Flórida Paulista",
	"Florínea",
	"Formiga",
	"Formoso",
	"Fortaleza de Minas",
	"Fortuna de Minas",
	"Franca",
	"Francisco Badaró",
	"Francisco Dumont",
	"Francisco Morato",
	"Francisco Sá",
	"Franciscópolis",
	"Franco da Rocha",
	"Frei Gaspar",
	"Frei Inocêncio",
	"Frei Lagonegro",
	"Fronteira",
	"Fronteira dos Vales",
	"Fruta de Leite",
	"Frutal",
	"Fundão",
	"Funilândia",
	"Gabriel Monteiro",
	"Gália",
	"Galiléia",
	"Gameleiras",
	"Garça",
	"Gastão Vidigal",
	"Gavião Peixoto",
	"General Salgado",
	"Getulina",
	"Glaucilândia",
	"Glicério",
	"Goiabeira",
	"Goianá",
	"Gonçalves",
	"Gonzaga",
	"Gouveia",
	"Governador Lindenberg",
	"Governador Valadares",
	"Grão Mogol",
	"Grupiara",
	"Guaçuí",
	"Guaiçara",
	"Guaimbê",
	"Guanhães",
	"Guapé",
	"Guapiaçu",
	"Guapiara",
	"Guapimirim",
	"Guará",
	"Guaraçaí",
	"Guaraciama",
	"Guaranésia",
	"Guarani",
	"Guarani d'Oeste",
	"Guarantã",
	"Guarapari",
	"Guarará",
	"Guararapes",
	"Guararema",
	"Guaratinguetá",
	"Guarda-Mor",
	"Guareí",
	"Guariba",
	"Guarujá",
	"Guarulhos",
	"Guatapará",
	"Guaxupé",
	"Guidoval",
	"Guimarânia",
	"Guiricema",
	"Gurinhatã",
	"Guzolândia",
	"Heliodora",
	"Herculândia",
	"Holambra",
	"Hortolândia",
	"Iacanga",
	"Iacri",
	"Iapu",
	"Iaras",
	"Ibaté",
	"Ibatiba",
	"Ibertioga",
	"Ibiá",
	"Ibiaí",
	"Ibirá",
	"Ibiracatu",
	"Ibiraci",
	"Ibiraçu",
	"Ibirarema",
	"Ibirité",
	"Ibitinga",
	"Ibitirama",
	"Ibitiúra de Minas",
	"Ibituruna",
	"Ibiúna",
	"Icaraí de Minas",
	"Icém",
	"Iconha",
	"Iepê",
	"Igaraçu do Tietê",
	"Igarapava",
	"Igarapé",
	"Igaratá",
	"Igaratinga",
	"Iguaba Grande",
	"Iguape",
	"Iguatama",
	"Ijaci",
	"Ilha Comprida",
	"Ilha Solteira",
	"Ilhabela",
	"Ilicínea",
	"Imbé de Minas",
	"Inconfidentes",
	"Indaiabira",
	"Indaiatuba",
	"Indiana",
	"Indiaporã",
	"Ingaí",
	"Inhapim",
	"Inhaúma",
	"Inimutaba",
	"Inúbia Paulista",
	"Ipaba",
	"Ipanema",
	"Ipatinga",
	"Ipaussu",
	"Iperó",
	"Ipeúna",
	"Ipiaçu",
	"Ipiguá",
	"Iporanga",
	"Ipuã",
	"Ipuiúna",
	"Iracemápolis",
	"Iraí de Minas",
	"Irapuã",
	"Irapuru",
	"Irupi",
	"Itaberá",
	"Itabira",
	"Itabirinha",
	"Itabirito",
	"Itaboraí",
	"Itacambira",
	"Itacarambi",
	"Itaguaçu",
	"Itaguaí",
	"Itaguara",
	"Itaí",
	"Itaipé",
	"Itajobi",
	"Itaju",
	"Itajubá",
	"Italva",
	"Itamarandiba",
	"Itamarati de Minas",
	"Itambacuri",
	"Itambé do Mato Dentro",
	"Itamogi",
	"Itamonte",
	"Itanhaém",
	"Itanhandu",
	"Itanhomi",
	"Itaobim",
	"Itaoca",
	"Itaocara",
	"Itapagipe",
	"Itapecerica",
	"Itapecerica da Serra",
	"Itapemirim",
	"Itaperuna",
	"Itapetininga",
	"Itapeva",
	"Itapevi",
	"Itapira",
	"Itapirapuã Paulista",
	"Itápolis",
	"Itaporanga",
	"Itapuí",
	"Itapura",
	"Itaquaquecetuba",
	"Itarana",
	"Itararé",
	"Itariri",
	"Itatiaia",
	"Itatiaiuçu",
	"Itatiba",
	"Itatinga",
	"Itaú de Minas",
	"Itaúna",
	"Itaverava",
	"Itinga",
	"Itirapina",
	"Itirapuã",
	"Itobi",
	"Itu",
	"Itueta",
	"Ituiutaba",
	"Itumirim",
	"Itupeva",
	"Iturama",
	"Itutinga",
	"Ituverava",
	"Iúna",
	"Jaborandi",
	"Jaboticabal",
	"Jaboticatubas",
	"Jacareí",
	"Jaci",
	"Jacinto",
	"Jacuí",
	"Jacupiranga",
	"Jaguaraçu",
	"Jaguaré",
	"Jaguariúna",
	"Jaíba",
	"Jales",
	"Jambeiro",
	"Jampruca",
	"Janaúba",
	"Jandira",
	"Januária",
	"Japaraíba",
	"Japeri",
	"Japonvar",
	"Jarinu",
	"Jaú",
	"Jeceaba",
	"Jenipapo de Minas",
	"Jequeri",
	"Jequitaí",
	"Jequitibá",
	"Jequitinhonha",
	"Jeriquara",
	"Jerônimo Monteiro",
	"Jesuânia",
	"Joaíma",
	"Joanésia",
	"Joanópolis",
	"João Monlevade",
	"João Neiva",
	"João Pinheiro",
	"João Ramalho",
	"Joaquim Felício",
	"Jordânia",
	"José Bonifácio",
	"José Gonçalves de Minas",
	"José Raydan",
	"Josenópolis",
	"Juatuba",
	"Juiz de Fora",
	"Júlio Mesquita",
	"Jumirim",
	"Jundiaí",
	"Junqueirópolis",
	"Juquiá",
	"Juquitiba",
	"Juramento",
	"Juruaia",
	"Juvenília",
	"Ladainha",
	"Lagamar",
	"Lagoa da Prata",
	"Lagoa dos Patos",
	"Lagoa Dourada",
	"Lagoa Formosa",
	"Lagoa Grande",
	"Lagoa Santa",
	"Lagoinha",
	"Laje do Muriaé",
	"Lajinha",
	"Lambari",
	"Lamim",
	"Laranja da Terra",
	"Laranjal Paulista",
	"Lassance",
	"Lavínia",
	"Lavras",
	"Lavrinhas",
	"Leandro Ferreira",
	"Leme",
	"Leme do Prado",
	"Lençóis Paulista",
	"Leopoldina",
	"Liberdade",
	"Lima Duarte",
	"Limeira",
	"Limeira do Oeste",
	"Lindóia",
	"Linhares",
	"Lins",
	"Lontra",
	"Lorena",
	"Lourdes",
	"Louveira",
	"Lucélia",
	"Lucianópolis",
	"Luís Antônio",
	"Luisburgo",
	"Luislândia",
	"Luiziânia",
	"Luminárias",
	"Lupércio",
	"Lutécia",
	"Luz",
	"Macaé",
	"Macatuba",
	"Macaubal",
	"Macedônia",
	"Machacalis",
	"Machado",
	"Macuco",
	"Madre de Deus de Minas",
	"Magda",
	"Magé",
	"Mairinque",
	"Mairiporã",
	"Malacacheta",
	"Mamonas",
	"Manduri",
	"Manga",
	"Mangaratiba",
	"Manhuaçu",
	"Manhumirim",
	"Mantena",
	"Mantenópolis",
	"Mar de Espanha",
	"Marabá Paulista",
	"Maracaí",
	"Marapoama",
	"Marataízes",
	"Maravilhas",
	"Marechal Floriano",
	"Maria da Fé",
	"Mariana",
	"Mariápolis",
	"Maricá",
	"Marilac",
	"Marilândia",
	"Marília",
	"Marinópolis",
	"Mário Campos",
	"Maripá de Minas",
	"Marliéria",
	"Marmelópolis",
	"Martinho Campos",
	"Martinópolis",
	"Martins Soares",
	"Mata Verde",
	"Matão",
	"Materlândia",
	"Mateus Leme",
	"Mathias Lobato",
	"Matias Barbosa",
	"Matias Cardoso",
	"Matipó",
	"Mato Verde",
	"Matozinhos",
	"Matutina",
	"Mauá",
	"Medeiros",
	"Medina",
	"Mendes",
	"Mendes Pimentel",
	"Mendonça",
	"Mercês",
	"Meridiano",
	"Mesópolis",
	"Mesquita",
	"Miguel Pereira",
	"Miguelópolis",
	"Mimoso do Sul",
	"Minas Novas",
	"Minduri",
	"Mineiros do Tietê",
	"Mira Estrela",
	"Mirabela",
	"Miracatu",
	"Miracema",
	"Miradouro",
	"Miraí",
	"Mirandópolis",
	"Mirante do Paranapanema",
	"Mirassol",
	"Mirassolândia",
	"Miravânia",
	"Mococa",
	"Moeda",
	"Moema",
	"Mogi das Cruzes",
	"Mogi Guaçu",
	"Mogi Mirim",
	"Mombuca",
	"Monções",
	"Mongaguá",
	"Monjolos",
	"Monsenhor Paulo",
	"Montalvânia",
	"Montanha",
	"Monte Alegre de Minas",
	"Monte Alegre do Sul",
	"Monte Alto",
	"Monte Aprazível",
	"Monte Azul",
	"Monte Azul Paulista",
	"Monte Belo",
	"Monte Carmelo",
	"Monte Formoso",
	"Monte Mor",
	"Monte Santo de Minas",
	"Monte Sião",
	"Monteiro Lobato",
	"Montes Claros",
	"Montezuma",
	"Morada Nova de Minas",
	"Morro Agudo",
	"Morro da Garça",
	"Morro do Pilar",
	"Morungaba",
	"Motuca",
	"Mucurici",
	"Munhoz",
	"Muniz Freire",
	"Muqui",
	"Muriaé",
	"Murutinga do Sul",
	"Mutum",
	"Muzambinho",
	"Nacip Raydan",
	"Nantes",
	"Nanuque",
	"Naque",
	"Narandiba",
	"Natalândia",
	"Natércia",
	"Natividade",
	"Natividade da Serra",
	"Nazaré Paulista",
	"Nazareno",
	"Nepomuceno",
	"Neves Paulista",
	"Nhandeara",
	"Nilópolis",
	"Ninheira",
	"Nipoã",
	"Niterói",
	"Nova Aliança",
	"Nova Belém",
	"Nova Campina",
	"Nova Canaã Paulista",
	"Nova Castilho",
	"Nova Era",
	"Nova Europa",
	"Nova Friburgo",
	"Nova Granada",
	"Nova Guataporanga",
	"Nova Iguaçu",
	"Nova Independência",
	"Nova Lima",
	"Nova Luzitânia",
	"Nova Módica",
	"Nova Odessa",
	"Nova Ponte",
	"Nova Porteirinha",
	"Nova Resende",
	"Nova Serrana",
	"Nova União",
	"Nova Venécia",
	"Novais",
	"Novo Cruzeiro",
	"Novo Oriente de Minas",
	"Novorizonte",
	"Nuporanga",
	"Ocauçu",
	"Olaria",
	"Óleo",
	"Olhos-d'Água",
	"Olímpia",
	"Olímpio Noronha",
	"Oliveira",
	"Oliveira Fortes",
	"Onça de Pitangui",
	"Onda Verde",
	"Oratórios",
	"Oriente",
	"Orindiúva",
	"Orizânia",
	"Orlândia",
	"Osasco",
	"Oscar Bressane",
	"Osvaldo Cruz",
	"Ourinhos",
	"Ouro Branco",
	"Ouro Fino",
	"Ouro Preto",
	"Ouro Verde de Minas",
	"Ouroeste",
	"Pacaembu",
	"Padre Carvalho",
	"Padre Paraíso",
	"Pai Pedro",
	"Paineiras",
	"Pains",
	"Paiva",
	"Palestina",
	"Palma",
	"Palmares Paulista",
	"Palmeira d'Oeste",
	"Palmópolis",
	"Pancas",
	"Panorama",
	"Papagaios",
	"Pará de Minas",
	"Paracambi",
	"Paracatu",
	"Paraguaçu",
	"Paraguaçu Paulista",
	"Paraíba do Sul",
	"Paraibuna",
	"Paraisópolis",
	"Paranapanema",
	"Paranapuã",
	"Paraopeba",
	"Parapuã",
	"Paraty",
	"Pardinho",
	"Pariquera-Açu",
	"Parisi",
	"Passa Quatro",
	"Passa Tempo",
	"Passa Vinte",
	"Passabém",
	"Passos",
	"Patis",
	"Patos de Minas",
	"Patrocínio",
	"Patrocínio do Muriaé",
	"Patrocínio Paulista",
	"Paty do Alferes",
	"Paula Cândido",
	"Paulicéia",
	"Paulínia",
	"Paulistânia",
	"Paulistas",
	"Paulo de Faria",
	"Pavão",
	"Peçanha",
	"Pederneiras",
	"Pedra Azul",
	"Pedra Bela",
	"Pedra Bonita",
	"Pedra do Anta",
	"Pedra do Indaiá",
	"Pedra Dourada",
	"Pedralva",
	"Pedranópolis",
	"Pedras de Maria da Cruz",
	"Pedregulho",
	"Pedreira",
	"Pedrinhas Paulista",
	"Pedrinópolis",
	"Pedro Canário",
	"Pedro de Toledo",
	"Pedro Leopoldo",
	"Pedro Teixeira",
	"Penápolis",
	"Pequeri",
	"Pequi",
	"Perdigão",
	"Perdizes",
	"Perdões",
	"Pereira Barreto",
	"Pereiras",
	"Periquito",
	"Peruíbe",
	"Pescador",
	"Petrópolis",
	"Piacatu",
	"Piau",
	"Piedade",
	"Piedade de Caratinga",
	"Piedade de Ponte Nova",
	"Piedade do Rio Grande",
	"Piedade dos Gerais",
	"Pilar do Sul",
	"Pimenta",
	"Pindamonhangaba",
	"Pindorama",
	"Pingo-d'Água",
	"Pinheiral",
	"Pinheiros",
	"Pintópolis",
	"Piquerobi",
	"Piquete",
	"Piracaia",
	"Piracema",
	"Piracicaba",
	"Piraí",
	"Piraju",
	"Pirajuba",
	"Pirajuí",
	"Piranga",
	"Pirangi",
	"Piranguçu",
	"Piranguinho",
	"Pirapetinga",
	"Pirapora",
	"Pirapora do Bom Jesus",
	"Pirapozinho",
	"Pirassununga",
	"Piratininga",
	"Piraúba",
	"Pitangui",
	"Piúma",
	"Piumhi",
	"Planura",
	"Platina",
	"Poá",
	"Poço Fundo",
	"Poços de Caldas",
	"Pocrane",
	"Poloni",
	"Pompéia",
	"Pompéu",
	"Pongaí",
	"Pontal",
	"Pontalinda",
	"Ponte Nova",
	"Pontes Gestal",
	"Ponto Belo",
	"Ponto Chique",
	"Ponto dos Volantes",
	"Populina",
	"Porangaba",
	"Porciúncula",
	"Porteirinha",
	"Porto Feliz",
	"Porto Ferreira",
	"Porto Firme",
	"Porto Real",
	"Poté",
	"Potim",
	"Potirendaba",
	"Pouso Alegre",
	"Pouso Alto",
	"Pracinha",
	"Pradópolis",
	"Prados",
	"Prata",
	"Pratânia",
	"Pratápolis",
	"Pratinha",
	"Presidente Alves",
	"Presidente Bernardes",
	"Presidente Epitácio",
	"Presidente Juscelino",
	"Presidente Kennedy",
	"Presidente Kubitschek",
	"Presidente Olegário",
	"Presidente Prudente",
	"Presidente Venceslau",
	"Promissão",
	"Prudente de Morais",
	"Quadra",
	"Quartel Geral",
	"Quatá",
	"Quatis",
	"Queimados",
	"Queiroz",
	"Queluz",
	"Queluzito",
	"Quintana",
	"Quissamã",
	"Rafard",
	"Rancharia",
	"Raposos",
	"Raul Soares",
	"Recreio",
	"Redenção da Serra",
	"Reduto",
	"Regente Feijó",
	"Reginópolis",
	"Registro",
	"Resende",
	"Resende Costa",
	"Resplendor",
	"Ressaquinha",
	"Restinga",
	"Riachinho",
	"Riacho dos Machados",
	"Ribeira",
	"Ribeirão Bonito",
	"Ribeirão Branco",
	"Ribeirão Corrente",
	"Ribeirão das Neves",
	"Ribeirão do Sul",
	"Ribeirão dos Índios",
	"Ribeirão Grande",
	"Ribeirão Pires",
	"Ribeirão Preto",
	"Ribeirão Vermelho",
	"Rifaina",
	"Rincão",
	"Rinópolis",
	"Rio Acima",
	"Rio Bananal",
	"Rio Bonito",
	"Rio Casca",
	"Rio Claro",
	"Rio das Flores",
	"Rio das Ostras",
	"Rio das Pedras",
	"Rio de Janeiro",
	"Rio do Prado",
	"Rio Doce",
	"Rio Espera",
	"Rio Grande da Serra",
	"Rio Manso",
	"Rio Novo",
	"Rio Novo do Sul",
	"Rio Paranaíba",
	"Rio Pardo de Minas",
	"Rio Piracicaba",
	"Rio Pomba",
	"Rio Preto",
	"Rio Vermelho",
	"Riolândia",
	"Ritápolis",
	"Riversul",
	"Rochedo de Minas",
	"Rodeiro",
	"Romaria",
	"Rosana",
	"Rosário da Limeira",
	"Roseira",
	"Rubelita",
	"Rubiácea",
	"Rubim",
	"Rubinéia",
	"Sabará",
	"Sabino",
	"Sabinópolis",
	"Sacramento",
	"Sagres",
	"Sales",
	"Sales Oliveira",
	"Salesópolis",
	"Salinas",
	"Salmourão",
	"Salto",
	"Salto da Divisa",
	"Salto de Pirapora",
	"Salto Grande",
	"Sandovalina",
	"Santa Adélia",
	"Santa Albertina",
	"Santa Bárbara",
	"Santa Bárbara d'Oeste",
	"Santa Bárbara do Leste",
	"Santa Bárbara do Monte Verde",
	"Santa Bárbara do Tugúrio",
	"Santa Branca",
	"Santa Clara d'Oeste",
	"Santa Cruz da Conceição",
	"Santa Cruz da Esperança",
	"Santa Cruz das Palmeiras",
	"Santa Cruz de Minas",
	"Santa Cruz de Salinas",
	"Santa Cruz do Escalvado",
	"Santa Cruz do Rio Pardo",
	"Santa Efigênia de Minas",
	"Santa Ernestina",
	"Santa Fé de Minas",
	"Santa Fé do Sul",
	"Santa Gertrudes",
	"Santa Helena de Minas",
	"Santa Isabel",
	"Santa Juliana",
	"Santa Leopoldina",
	"Santa Luzia",
	"Santa Margarida",
	"Santa Maria da Serra",
	"Santa Maria de Itabira",
	"Santa Maria de Jetibá",
	"Santa Maria do Salto",
	"Santa Maria do Suaçuí",
	"Santa Maria Madalena",
	"Santa Mercedes",
	"Santa Rita d'Oeste",
	"Santa Rita de Caldas",
	"Santa Rita de Ibitipoca",
	"Santa Rita de Jacutinga",
	"Santa Rita de Minas",
	"Santa Rita do Itueto",
	"Santa Rita do Passa Quatro",
	"Santa Rita do Sapucaí",
	"Santa Rosa da Serra",
	"Santa Rosa de Viterbo",
	"Santa Salete",
	"Santa Teresa",
	"Santa Vitória",
	"Santana da Ponte Pensa",
	"Santana da Vargem",
	"Santana de Cataguases",
	"Santana de Parnaíba",
	"Santana de Pirapama",
	"Santana do Deserto",
	"Santana do Garambéu",
	"Santana do Jacaré",
	"Santana do Manhuaçu",
	"Santana do Paraíso",
	"Santana do Riacho",
	"Santana dos Montes",
	"Santo Anastácio",
	"Santo André",
	"Santo Antônio da Alegria",
	"Santo Antônio de Pádua",
	"Santo Antônio de Posse",
	"Santo Antônio do Amparo",
	"Santo Antônio do Aracanguá",
	"Santo Antônio do Aventureiro",
	"Santo Antônio do Grama",
	"Santo Antônio do Itambé",
	"Santo Antônio do Jacinto",
	"Santo Antônio do Jardim",
	"Santo Antônio do Monte",
	"Santo Antônio do Pinhal",
	"Santo Antônio do Retiro",
	"Santo Antônio do Rio Abaixo",
	"Santo Expedito",
	"Santo Hipólito",
	"Santópolis do Aguapeí",
	"Santos",
	"Santos Dumont",
	"São Bento Abade",
	"São Bento do Sapucaí",
	"São Bernardo do Campo",
	"São Brás do Suaçuí",
	"São Caetano do Sul",
	"São Domingos das Dores",
	"São Domingos do Norte",
	"São Domingos do Prata",
	"São Félix de Minas",
	"São Fidélis",
	"São Francisco",
	"São Francisco de Itabapoana",
	"São Francisco de Sales",
	"São Francisco do Glória",
	"São Gabriel da Palha",
	"São Geraldo",
	"São Geraldo da Piedade",
	"São Geraldo do Baixio",
	"São Gonçalo",
	"São Gonçalo do Abaeté",
	"São Gonçalo do Pará",
	"São Gonçalo do Rio Abaixo",
	"São Gonçalo do Rio Preto",
	"São Gonçalo do Sapucaí",
	"São Gotardo",
	"São João Batista do Glória",
	"São João da Barra",
	"São João da Boa Vista",
	"São João da Lagoa",
	"São João da Mata",
	"São João da Ponte",
	"São João das Duas Pontes",
	"São João das Missões",
	"São João de Iracema",
	"São João de Meriti",
	"São João del Rei",
	"São João do Manhuaçu",
	"São João do Manteninha",
	"São João do Oriente",
	"São João do Pacuí",
	"São João do Paraíso",
	"São João do Pau d'Alho",
	"São João Evangelista",
	"São João Nepomuceno",
	"São Joaquim da Barra",
	"São Joaquim de Bicas",
	"São José da Barra",
	"São José da Bela Vista",
	"São José da Lapa",
	"São José da Safira",
	"São José da Varginha",
	"São José de Ubá",
	"São José do Alegre",
	"São José do Barreiro",
	"São José do Calçado",
	"São José do Divino",
	"São José do Goiabal",
	"São José do Jacuri",
	"São José do Mantimento",
	"São José do Rio Pardo",
	"São José do Rio Preto",
	"São José do Vale do Rio Preto",
	"São José dos Campos",
	"São Lourenço",
	"São Lourenço da Serra",
	"São Luiz do Paraitinga",
	"São Manuel",
	"São Mateus",
	"São Miguel Arcanjo",
	"São Miguel do Anta",
	"São Paulo",
	"São Pedro",
	"São Pedro da Aldeia",
	"São Pedro da União",
	"São Pedro do Suaçuí",
	"São Pedro do Turvo",
	"São Pedro dos Ferros",
	"São Romão",
	"São Roque",
	"São Roque de Minas",
	"São Roque do Canaã",
	"São Sebastião",
	"São Sebastião da Bela Vista",
	"São Sebastião da Grama",
	"São Sebastião da Vargem Alegre",
	"São Sebastião do Alto",
	"São Sebastião do Anta",
	"São Sebastião do Maranhão",
	"São Sebastião do Oeste",
	"São Sebastião do Paraíso",
	"São Sebastião do Rio Preto",
	"São Sebastião do Rio Verde",
	"São Simão",
	"São Tiago",
	"São Tomás de Aquino",
	"São Tomé das Letras",
	"São Vicente",
	"São Vicente de Minas",
	"Sapucaí-Mirim",
	"Sapucaia",
	"Saquarema",
	"Sarapuí",
	"Sardoá",
	"Sarutaiá",
	"Sarzedo",
	"Sebastianópolis do Sul",
	"Sem-Peixe",
	"Senador Amaral",
	"Senador Cortes",
	"Senador Firmino",
	"Senador José Bento",
	"Senador Modestino Gonçalves",
	"Senhora de Oliveira",
	"Senhora do Porto",
	"Senhora dos Remédios",
	"Sericita",
	"Seritinga",
	"Seropédica",
	"Serra",
	"Serra Azul",
	"Serra Azul de Minas",
	"Serra da Saudade",
	"Serra do Salitre",
	"Serra dos Aimorés",
	"Serra Negra",
	"Serrana",
	"Serrania",
	"Serranópolis de Minas",
	"Serranos",
	"Serro",
	"Sertãozinho",
	"Sete Barras",
	"Sete Lagoas",
	"Setubinha",
	"Severínia",
	"Silva Jardim",
	"Silveirânia",
	"Silveiras",
	"Silvianópolis",
	"Simão Pereira",
	"Simonésia",
	"Sobrália",
	"Socorro",
	"Soledade de Minas",
	"Sooretama",
	"Sorocaba",
	"Sud Mennucci",
	"Sumaré",
	"Sumidouro",
	"Suzanápolis",
	"Suzano",
	"Tabapuã",
	"Tabatinga",
	"Taboão da Serra",
	"Tabuleiro",
	"Taciba",
	"Taguaí",
	"Taiaçu",
	"Taiobeiras",
	"Taiúva",
	"Tambaú",
	"Tanabi",
	"Tanguá",
	"Taparuba",
	"Tapiraí",
	"Tapiratiba",
	"Taquaraçu de Minas",
	"Taquaral",
	"Taquaritinga",
	"Taquarituba",
	"Taquarivaí",
	"Tarabai",
	"Tarumã",
	"Tarumirim",
	"Tatuí",
	"Taubaté",
	"Teixeiras",
	"Tejupá",
	"Teodoro Sampaio",
	"Teófilo Otoni",
	"Teresópolis",
	"Tietê",
	"Timburi",
	"Timóteo",
	"Tiradentes",
	"Tiros",
	"Tocantins",
	"Tocos do Moji",
	"Tombos",
	"Torre de Pedra",
	"Torrinha",
	"Trabiju",
	"Trajano de Moraes",
	"Tremembé",
	"Três Corações",
	"Três Fronteiras",
	"Três Marias",
	"Três Pontas",
	"Três Rios",
	"Tuiuti",
	"Tumiritinga",
	"Tupã",
	"Tupaciguara",
	"Tupi Paulista",
	"Turiúba",
	"Turmalina",
	"Turvolândia",
	"Ubá",
	"Ubaí",
	"Ubaporanga",
	"Ubarana",
	"Ubatuba",
	"Uberaba",
	"Uberlândia",
	"Ubirajara",
	"Uchoa",
	"Umburatiba",
	"Unaí",
	"União de Minas",
	"União Paulista",
	"Urânia",
	"Uru",
	"Uruana de Minas",
	"Urucânia",
	"Urucuia",
	"Urupês",
	"Valença",
	"Valentim Gentil",
	"Valinhos",
	"Valparaíso",
	"Vargem Alegre",
	"Vargem Alta",
	"Vargem Grande do Rio Pardo",
	"Vargem Grande do Sul",
	"Vargem Grande Paulista",
	"Varginha",
	"Varjão de Minas",
	"Varre-Sai",
	"Várzea da Palma",
	"Várzea Paulista",
	"Varzelândia",
	"Vassouras",
	"Vazante",
	"Venda Nova do Imigrante",
	"Verdelândia",
	"Veredinha",
	"Veríssimo",
	"Vermelho Novo",
	"Vespasiano",
	"Viana",
	"Viçosa",
	"Vieiras",
	"Vila Pavão",
	"Vila Valério",
	"Vila Velha",
	"Vinhedo",
	"Viradouro",
	"Virgem da Lapa",
	"Virgínia",
	"Virginópolis",
	"Virgolândia",
	"Visconde do Rio Branco",
	"Vista Alegre do Alto",
	"Vitória",
	"Vitória Brasil",
	"Volta Grande",
	"Volta Redonda",
	"Votorantim",
	"Votuporanga",
	"Zacarias",
	"Abaiara",
	"Abaíra",
	"Abaré",
	"Abreu e Lima",
	"Açailândia",
	"Acajutiba",
	"Acarape",
	"Acaraú",
	"Acari",
	"Acauã",
	"Acopiara",
	"Adustina",
	"Afogados da Ingazeira",
	"Afonso Bezerra",
	"Afonso Cunha",
	"Afrânio",
	"Agrestina",
	"Agricolândia",
	"Água Branca",
	"Água Doce do Maranhão",
	"Água Fria",
	"Água Nova",
	"Água Preta",
	"Águas Belas",
	"Aguiar",
	"Aiquara",
	"Aiuaba",
	"Alagoa Grande",
	"Alagoa Nova",
	"Alagoinha",
	"Alagoinha do Piauí",
	"Alagoinhas",
	"Alcântara",
	"Alcântaras",
	"Alcantil",
	"Alcobaça",
	"Aldeias Altas",
	"Alegrete do Piauí",
	"Alexandria",
	"Algodão de Jandaíra",
	"Alhandra",
	"Aliança",
	"Almadina",
	"Almino Afonso",
	"Altamira do Maranhão",
	"Altaneira",
	"Altinho",
	"Alto Alegre do Maranhão",
	"Alto Alegre do Pindaré",
	"Alto do Rodrigues",
	"Alto Longá",
	"Alto Parnaíba",
	"Alto Santo",
	"Altos",
	"Alvorada do Gurguéia",
	"Amapá do Maranhão",
	"Amaraji",
	"Amarante",
	"Amarante do Maranhão",
	"Amargosa",
	"Amélia Rodrigues",
	"América Dourada",
	"Amontada",
	"Amparo do São Francisco",
	"Anadia",
	"Anagé",
	"Anajatuba",
	"Anapurus",
	"Andaraí",
	"Andorinha",
	"Angelim",
	"Angical",
	"Angical do Piauí",
	"Angicos",
	"Anguera",
	"Anísio de Abreu",
	"Antas",
	"Antonina do Norte",
	"Antônio Almeida",
	"Antônio Cardoso",
	"Antônio Gonçalves",
	"Antônio Martins",
	"Apicum-Açu",
	"Apodi",
	"Aporá",
	"Apuarema",
	"Apuiarés",
	"Aquidabã",
	"Aquiraz",
	"Araçagi",
	"Aracaju",
	"Araçás",
	"Aracati",
	"Aracatu",
	"Araci",
	"Aracoiaba",
	"Araçoiaba",
	"Araguanã",
	"Araioses",
	"Aramari",
	"Arame",
	"Arapiraca",
	"Arara",
	"Ararendá",
	"Arari",
	"Araripe",
	"Araripina",
	"Arataca",
	"Aratuba",
	"Aratuípe",
	"Arauá",
	"Arcoverde",
	"Areia",
	"Areia Branca",
	"Areia de Baraúnas",
	"Areial",
	"Arez",
	"Arneiroz",
	"Aroazes",
	"Aroeiras",
	"Aroeiras do Itaim",
	"Arraial",
	"Assaré",
	"Assú",
	"Assunção",
	"Assunção do Piauí",
	"Aurelino Leal",
	"Avelino Lopes",
	"Axixá",
	"Bacabal",
	"Bacabeira",
	"Bacuri",
	"Bacurituba",
	"Baía da Traição",
	"Baía Formosa",
	"Baianópolis",
	"Baixa Grande",
	"Baixa Grande do Ribeiro",
	"Baixio",
	"Balsas",
	"Banabuiú",
	"Bananeiras",
	"Banzaê",
	"Barão de Grajaú",
	"Baraúna",
	"Barbalha",
	"Barcelona",
	"Barra",
	"Barra D'Alcântara",
	"Barra da Estiva",
	"Barra de Guabiraba",
	"Barra de Santa Rosa",
	"Barra de Santana",
	"Barra de Santo Antônio",
	"Barra de São Miguel",
	"Barra do Choça",
	"Barra do Corda",
	"Barra do Mendes",
	"Barra do Rocha",
	"Barra dos Coqueiros",
	"Barras",
	"Barreira",
	"Barreiras",
	"Barreiras do Piauí",
	"Barreirinhas",
	"Barreiros",
	"Barro",
	"Barro Alto",
	"Barro Duro",
	"Barro Preto",
	"Barrocas",
	"Barroquinha",
	"Batalha",
	"Baturité",
	"Bayeux",
	"Beberibe",
	"Bela Cruz",
	"Bela Vista do Maranhão",
	"Bela Vista do Piauí",
	"Belágua",
	"Belém",
	"Belém de Maria",
	"Belém do Brejo do Cruz",
	"Belém do Piauí",
	"Belém do São Francisco",
	"Belo Campo",
	"Belo Jardim",
	"Belo Monte",
	"Beneditinos",
	"Benedito Leite",
	"Bento Fernandes",
	"Bequimão",
	"Bernardino Batista",
	"Bernardo do Mearim",
	"Bertolínia",
	"Betânia",
	"Betânia do Piauí",
	"Bezerros",
	"Biritinga",
	"Boa Hora",
	"Boa Nova",
	"Boa Ventura",
	"Boa Viagem",
	"Boa Vista",
	"Boa Vista do Gurupi",
	"Boa Vista do Tupim",
	"Boca da Mata",
	"Bodó",
	"Bodocó",
	"Bom Conselho",
	"Bom Jesus da Lapa",
	"Bom Jesus da Serra",
	"Bom Jesus das Selvas",
	"Bom Lugar",
	"Bom Princípio do Piauí",
	"Bonfim do Piauí",
	"Boninal",
	"Bonito",
	"Bonito de Santa Fé",
	"Boqueirão",
	"Boqueirão do Piauí",
	"Boquim",
	"Boquira",
	"Botuporã",
	"Branquinha",
	"Brasileira",
	"Brejão",
	"Brejinho",
	"Brejo",
	"Brejo da Madre de Deus",
	"Brejo de Areia",
	"Brejo do Cruz",
	"Brejo do Piauí",
	"Brejo dos Santos",
	"Brejo Grande",
	"Brejo Santo",
	"Brejões",
	"Brejolândia",
	"Brotas de Macaúbas",
	"Brumado",
	"Buenos Aires",
	"Buerarema",
	"Buíque",
	"Buriti",
	"Buriti Bravo",
	"Buriti dos Lopes",
	"Buriti dos Montes",
	"Buriticupu",
	"Buritirama",
	"Buritirana",
	"Caaporã",
	"Caatiba",
	"Cabaceiras",
	"Cabaceiras do Paraguaçu",
	"Cabeceiras do Piauí",
	"Cabedelo",
	"Cabo de Santo Agostinho",
	"Cabrobó",
	"Cachoeira",
	"Cachoeira dos Índios",
	"Cachoeira Grande",
	"Cacimba de Areia",
	"Cacimba de Dentro",
	"Cacimbas",
	"Cacimbinhas",
	"Caculé",
	"Caém",
	"Caetanos",
	"Caetés",
	"Caetité",
	"Cafarnaum",
	"Caiçara do Norte",
	"Caiçara do Rio do Vento",
	"Caicó",
	"Cairu",
	"Cajapió",
	"Cajari",
	"Cajazeiras",
	"Cajazeiras do Piauí",
	"Cajazeirinhas",
	"Cajueiro",
	"Cajueiro da Praia",
	"Calçado",
	"Caldas Brandão",
	"Caldeirão Grande",
	"Caldeirão Grande do Piauí",
	"Calumbi",
	"Camacan",
	"Camaçari",
	"Camalaú",
	"Camamu",
	"Camaragibe",
	"Camocim",
	"Camocim de São Félix",
	"Campestre do Maranhão",
	"Campina Grande",
	"Campinas do Piauí",
	"Campo Alegre de Lourdes",
	"Campo Alegre do Fidalgo",
	"Campo do Brito",
	"Campo Formoso",
	"Campo Grande",
	"Campo Grande do Piauí",
	"Campo Largo do Piauí",
	"Campo Maior",
	"Campo Redondo",
	"Campos Sales",
	"Camutanga",
	"Canapi",
	"Canarana",
	"Canavieira",
	"Canavieiras",
	"Candeal",
	"Candiba",
	"Cândido Mendes",
	"Cândido Sales",
	"Canguaretama",
	"Canhoba",
	"Canhotinho",
	"Canindé",
	"Canindé de São Francisco",
	"Cansanção",
	"Cantanhede",
	"Canto do Buriti",
	"Canudos",
	"Capela",
	"Capela do Alto Alegre",
	"Capim",
	"Capim Grosso",
	"Capinzal do Norte",
	"Capistrano",
	"Capitão de Campos",
	"Capitão Gervásio Oliveira",
	"Capoeiras",
	"Caracol",
	"Caraíbas",
	"Caraúbas",
	"Caraúbas do Piauí",
	"Caravelas",
	"Cardeal da Silva",
	"Caridade",
	"Caridade do Piauí",
	"Carinhanha",
	"Carira",
	"Cariré",
	"Caririaçu",
	"Cariús",
	"Carmópolis",
	"Carnaíba",
	"Carnaúba dos Dantas",
	"Carnaubais",
	"Carnaubal",
	"Carnaubeira da Penha",
	"Carneiros",
	"Carolina",
	"Carpina",
	"Carrapateira",
	"Caruaru",
	"Carutapera",
	"Casa Nova",
	"Casinhas",
	"Casserengue",
	"Castelo do Piauí",
	"Castro Alves",
	"Catarina",
	"Catende",
	"Catingueira",
	"Catolândia",
	"Catolé do Rocha",
	"Catu",
	"Catunda",
	"Caturama",
	"Caturité",
	"Caucaia",
	"Caxias",
	"Caxingó",
	"Ceará-Mirim",
	"Cedro",
	"Cedro de São João",
	"Central",
	"Central do Maranhão",
	"Centro do Guilherme",
	"Centro Novo do Maranhão",
	"Cerro Corá",
	"Chã de Alegria",
	"Chã Grande",
	"Chã Preta",
	"Chapadinha",
	"Chaval",
	"Choró",
	"Chorozinho",
	"Chorrochó",
	"Cícero Dantas",
	"Cidelândia",
	"Cipó",
	"Coaraci",
	"Cocal",
	"Cocal de Telha",
	"Cocal dos Alves",
	"Cocos",
	"Codó",
	"Coelho Neto",
	"Coité do Nóia",
	"Coivaras",
	"Colônia do Gurguéia",
	"Colônia do Piauí",
	"Colônia Leopoldina",
	"Conceição",
	"Conceição da Feira",
	"Conceição do Almeida",
	"Conceição do Canindé",
	"Conceição do Coité",
	"Conceição do Jacuípe",
	"Conceição do Lago-Açu",
	"Condado",
	"Conde",
	"Condeúba",
	"Congo",
	"Contendas do Sincorá",
	"Coqueiro Seco",
	"Coração de Maria",
	"Cordeiros",
	"Coreaú",
	"Coremas",
	"Coribe",
	"Coroatá",
	"Coronel Ezequiel",
	"Coronel João Pessoa",
	"Coronel João Sá",
	"Coronel José Dias",
	"Corrente",
	"Correntes",
	"Correntina",
	"Cortês",
	"Coruripe",
	"Cotegipe",
	"Coxixola",
	"Craíbas",
	"Crateús",
	"Crato",
	"Cravolândia",
	"Crisópolis",
	"Cristalândia do Piauí",
	"Cristinápolis",
	"Cristino Castro",
	"Cristópolis",
	"Croatá",
	"Cruz",
	"Cruz das Almas",
	"Cruz do Espírito Santo",
	"Cruzeta",
	"Cubati",
	"Cuité",
	"Cuité de Mamanguape",
	"Cuitegi",
	"Cumaru",
	"Cumbe",
	"Cupira",
	"Curaçá",
	"Curimatá",
	"Currais",
	"Currais Novos",
	"Curral de Cima",
	"Curral Novo do Piauí",
	"Curral Velho",
	"Curralinhos",
	"Cururupu",
	"Custódia",
	"Damião",
	"Dário Meira",
	"Davinópolis",
	"Delmiro Gouveia",
	"Demerval Lobão",
	"Deputado Irapuan Pinheiro",
	"Desterro",
	"Diamante",
	"Dias d'Ávila",
	"Dirceu Arcoverde",
	"Divina Pastora",
	"Dois Riachos",
	"Dom Basílio",
	"Dom Expedito Lopes",
	"Dom Inocêncio",
	"Dom Macedo Costa",
	"Dom Pedro",
	"Domingos Mourão",
	"Dona Inês",
	"Dormentes",
	"Doutor Severiano",
	"Duas Estradas",
	"Duque Bacelar",
	"Elesbão Veloso",
	"Eliseu Martins",
	"Elísio Medrado",
	"Emas",
	"Encanto",
	"Encruzilhada",
	"Equador",
	"Ereré",
	"Érico Cardoso",
	"Escada",
	"Esperança",
	"Esperantina",
	"Esperantinópolis",
	"Espírito Santo",
	"Esplanada",
	"Estância",
	"Estreito",
	"Estrela de Alagoas",
	"Euclides da Cunha",
	"Eunápolis",
	"Eusébio",
	"Extremoz",
	"Exu",
	"Fagundes",
	"Farias Brito",
	"Fartura do Piauí",
	"Fátima",
	"Feira da Mata",
	"Feira de Santana",
	"Feira Grande",
	"Feira Nova",
	"Feira Nova do Maranhão",
	"Felipe Guerra",
	"Feliz Deserto",
	"Fernando de Noronha",
	"Fernando Falcão",
	"Fernando Pedroza",
	"Ferreiros",
	"Filadélfia",
	"Firmino Alves",
	"Flexeiras",
	"Florânia",
	"Flores",
	"Flores do Piauí",
	"Floresta Azul",
	"Floresta do Piauí",
	"Floriano",
	"Formosa da Serra Negra",
	"Formosa do Rio Preto",
	"Forquilha",
	"Fortaleza",
	"Fortaleza dos Nogueiras",
	"Fortim",
	"Fortuna",
	"Francinópolis",
	"Francisco Ayres",
	"Francisco Dantas",
	"Francisco Macedo",
	"Francisco Santos",
	"Frecheirinha",
	"Frei Martinho",
	"Frei Miguelinho",
	"Frei Paulo",
	"Fronteiras",
	"Frutuoso Gomes",
	"Gado Bravo",
	"Galinhos",
	"Gameleira",
	"Gandu",
	"Garanhuns",
	"Gararu",
	"Gavião",
	"Geminiano",
	"General Maynard",
	"General Sampaio",
	"Gentio do Ouro",
	"Gilbués",
	"Girau do Ponciano",
	"Glória",
	"Glória do Goitá",
	"Godofredo Viana",
	"Goiana",
	"Goianinha",
	"Gonçalves Dias",
	"Gongogi",
	"Governador Archer",
	"Governador Dix-Sept Rosado",
	"Governador Edison Lobão",
	"Governador Eugênio Barros",
	"Governador Luiz Rocha",
	"Governador Mangabeira",
	"Governador Newton Bello",
	"Governador Nunes Freire",
	"Graça",
	"Graça Aranha",
	"Graccho Cardoso",
	"Grajaú",
	"Granito",
	"Granja",
	"Granjeiro",
	"Gravatá",
	"Groaíras",
	"Grossos",
	"Guadalupe",
	"Guaiúba",
	"Guajeru",
	"Guamaré",
	"Guanambi",
	"Guarabira",
	"Guaraciaba do Norte",
	"Guaramiranga",
	"Guaratinga",
	"Guaribas",
	"Guimarães",
	"Gurinhém",
	"Gurjão",
	"Heliópolis",
	"Hidrolândia",
	"Horizonte",
	"Hugo Napoleão",
	"Humberto de Campos",
	"Iaçu",
	"Iati",
	"Ibaretama",
	"Ibateguara",
	"Ibiapina",
	"Ibiara",
	"Ibiassucê",
	"Ibicaraí",
	"Ibicoara",
	"Ibicuí",
	"Ibicuitinga",
	"Ibimirim",
	"Ibipeba",
	"Ibipitanga",
	"Ibiquera",
	"Ibirajuba",
	"Ibirapitanga",
	"Ibirapuã",
	"Ibirataia",
	"Ibitiara",
	"Ibititá",
	"Ibotirama",
	"Icapuí",
	"Icatu",
	"Ichu",
	"Icó",
	"Ielmo Marinho",
	"Igaci",
	"Igaporã",
	"Igaracy",
	"Igarapé do Meio",
	"Igarapé Grande",
	"Igarassu",
	"Igrapiúna",
	"Igreja Nova",
	"Iguaí",
	"Iguaracy",
	"Ilha das Flores",
	"Ilha de Itamaracá",
	"Ilha Grande",
	"Ilhéus",
	"Imaculada",
	"Imperatriz",
	"Indiaroba",
	"Ingá",
	"Ingazeira",
	"Inhambupe",
	"Inhapi",
	"Inhuma",
	"Ipanguaçu",
	"Ipaporanga",
	"Ipaumirim",
	"Ipecaetá",
	"Ipiaú",
	"Ipirá",
	"Ipiranga do Piauí",
	"Ipojuca",
	"Ipu",
	"Ipubi",
	"Ipueira",
	"Ipueiras",
	"Ipupiara",
	"Iracema",
	"Irajuba",
	"Iramaia",
	"Iraquara",
	"Irará",
	"Irauçuba",
	"Irecê",
	"Isaías Coelho",
	"Itabaiana",
	"Itabaianinha",
	"Itabela",
	"Itaberaba",
	"Itabi",
	"Itabuna",
	"Itacaré",
	"Itacuruba",
	"Itaeté",
	"Itagi",
	"Itagibá",
	"Itagimirim",
	"Itaguaçu da Bahia",
	"Itaíba",
	"Itaiçaba",
	"Itainópolis",
	"Itaipava do Grajaú",
	"Itaitinga",
	"Itajá",
	"Itaju do Colônia",
	"Itajuípe",
	"Itamaraju",
	"Itamari",
	"Itanagra",
	"Itanhém",
	"Itapajé",
	"Itaparica",
	"Itapé",
	"Itapebi",
	"Itapecuru Mirim",
	"Itapetim",
	"Itapetinga",
	"Itapicuru",
	"Itapipoca",
	"Itapissuma",
	"Itapitanga",
	"Itapiúna",
	"Itaporanga d'Ajuda",
	"Itapororoca",
	"Itaquara",
	"Itaquitinga",
	"Itarantim",
	"Itarema",
	"Itatim",
	"Itatira",
	"Itatuba",
	"Itaú",
	"Itaueira",
	"Itinga do Maranhão",
	"Itiruçu",
	"Itiúba",
	"Itororó",
	"Ituaçu",
	"Ituberá",
	"Iuiu",
	"Jaboatão dos Guararapes",
	"Jaçanã",
	"Jacaraci",
	"Jacaraú",
	"Jacaré dos Homens",
	"Jacobina",
	"Jacobina do Piauí",
	"Jacuípe",
	"Jaguaquara",
	"Jaguarari",
	"Jaguaretama",
	"Jaguaribara",
	"Jaguaribe",
	"Jaguaripe",
	"Jaguaruana",
	"Jaicós",
	"Jandaíra",
	"Janduís",
	"Januário Cicco",
	"Japaratinga",
	"Japaratuba",
	"Japi",
	"Japoatã",
	"Jaqueira",
	"Jaramataia",
	"Jardim",
	"Jardim de Angicos",
	"Jardim de Piranhas",
	"Jardim do Mulato",
	"Jardim do Seridó",
	"Jataúba",
	"Jati",
	"Jatobá",
	"Jatobá do Piauí",
	"Jenipapo dos Vieiras",
	"Jequiá da Praia",
	"Jequié",
	"Jeremoabo",
	"Jericó",
	"Jerumenha",
	"Jijoca de Jericoacoara",
	"Jiquiriçá",
	"Jitaúna",
	"João Alfredo",
	"João Câmara",
	"João Costa",
	"João Dias",
	"João Dourado",
	"João Lisboa",
	"João Pessoa",
	"Joaquim Gomes",
	"Joaquim Nabuco",
	"Joaquim Pires",
	"Joca Claudino",
	"Joca Marques",
	"José da Penha",
	"José de Freitas",
	"Joselândia",
	"Juarez Távora",
	"Juazeirinho",
	"Juazeiro",
	"Juazeiro do Norte",
	"Juazeiro do Piauí",
	"Jucás",
	"Jucati",
	"Jucuruçu",
	"Jucurutu",
	"Júlio Borges",
	"Junco do Maranhão",
	"Junco do Seridó",
	"Jundiá",
	"Junqueiro",
	"Jupi",
	"Jurema",
	"Juripiranga",
	"Juru",
	"Jussari",
	"Jussiape",
	"Lafaiete Coutinho",
	"Lagarto",
	"Lago da Pedra",
	"Lago do Junco",
	"Lago dos Rodrigues",
	"Lago Verde",
	"Lagoa",
	"Lagoa Alegre",
	"Lagoa d'Anta",
	"Lagoa da Canoa",
	"Lagoa de Dentro",
	"Lagoa de Itaenga",
	"Lagoa de Pedras",
	"Lagoa de São Francisco",
	"Lagoa de Velhos",
	"Lagoa do Barro do Piauí",
	"Lagoa do Carro",
	"Lagoa do Mato",
	"Lagoa do Ouro",
	"Lagoa do Piauí",
	"Lagoa do Sítio",
	"Lagoa dos Gatos",
	"Lagoa Grande do Maranhão",
	"Lagoa Nova",
	"Lagoa Real",
	"Lagoa Salgada",
	"Lagoa Seca",
	"Lagoinha do Piauí",
	"Laje",
	"Lajeado Novo",
	"Lajedão",
	"Lajedinho",
	"Lajedo",
	"Lajedo do Tabocal",
	"Lajes",
	"Lajes Pintadas",
	"Lamarão",
	"Landri Sales",
	"Lapão",
	"Laranjeiras",
	"Lastro",
	"Lauro de Freitas",
	"Lavras da Mangabeira",
	"Lençóis",
	"Licínio de Almeida",
	"Lima Campos",
	"Limoeiro",
	"Limoeiro de Anadia",
	"Limoeiro do Norte",
	"Livramento",
	"Livramento de Nossa Senhora",
	"Logradouro",
	"Loreto",
	"Lucena",
	"Lucrécia",
	"Luís Correia",
	"Luís Domingues",
	"Luís Eduardo Magalhães",
	"Luís Gomes",
	"Luzilândia",
	"Macaíba",
	"Macajuba",
	"Macambira",
	"Macaparana",
	"Macarani",
	"Macau",
	"Macaúbas",
	"Maceió",
	"Machados",
	"Macururé",
	"Madalena",
	"Madeiro",
	"Madre de Deus",
	"Mãe d'Água",
	"Maetinga",
	"Magalhães de Almeida",
	"Maiquinique",
	"Mairi",
	"Major Isidoro",
	"Major Sales",
	"Malhada",
	"Malhada de Pedras",
	"Malhada dos Bois",
	"Malhador",
	"Malta",
	"Mamanguape",
	"Manaíra",
	"Manari",
	"Manoel Emídio",
	"Manoel Vitorino",
	"Mansidão",
	"Mar Vermelho",
	"Maracaçumé",
	"Maracanaú",
	"Maracás",
	"Maragogi",
	"Maragogipe",
	"Maraial",
	"Marajá do Sena",
	"Maranguape",
	"Maranhãozinho",
	"Maraú",
	"Marcação",
	"Marcelino Vieira",
	"Marcionílio Souza",
	"Marco",
	"Marcolândia",
	"Marcos Parente",
	"Marechal Deodoro",
	"Mari",
	"Maribondo",
	"Marizópolis",
	"Martinópole",
	"Martins",
	"Maruim",
	"Mascote",
	"Massapê",
	"Massapê do Piauí",
	"Mata de São João",
	"Mata Grande",
	"Mata Roma",
	"Mataraca",
	"Matias Olímpio",
	"Matina",
	"Matinha",
	"Matinhas",
	"Mato Grosso",
	"Matões",
	"Matões do Norte",
	"Matriz de Camaragibe",
	"Maturéia",
	"Mauriti",
	"Maxaranguape",
	"Medeiros Neto",
	"Meruoca",
	"Messias",
	"Messias Targino",
	"Miguel Alves",
	"Miguel Calmon",
	"Miguel Leão",
	"Milagres",
	"Milagres do Maranhão",
	"Milhã",
	"Milton Brandão",
	"Minador do Negrão",
	"Miraíma",
	"Miranda do Norte",
	"Mirandiba",
	"Mirangaba",
	"Mirante",
	"Mirinzal",
	"Missão Velha",
	"Mogeiro",
	"Moita Bonita",
	"Mombaça",
	"Monção",
	"Monsenhor Gil",
	"Monsenhor Hipólito",
	"Monsenhor Tabosa",
	"Montadas",
	"Montanhas",
	"Monte Alegre",
	"Monte Alegre de Sergipe",
	"Monte Alegre do Piauí",
	"Monte das Gameleiras",
	"Monte Horebe",
	"Monte Santo",
	"Monteiro",
	"Monteirópolis",
	"Montes Altos",
	"Morada Nova",
	"Moraújo",
	"Moreilândia",
	"Moreno",
	"Morpará",
	"Morrinhos",
	"Morro Cabeça no Tempo",
	"Morro do Chapéu",
	"Morro do Chapéu do Piauí",
	"Morros",
	"Mortugaba",
	"Mossoró",
	"Mucambo",
	"Mucugê",
	"Mucuri",
	"Mulungu",
	"Mulungu do Morro",
	"Mundo Novo",
	"Muniz Ferreira",
	"Muquém do São Francisco",
	"Muribeca",
	"Murici",
	"Murici dos Portelas",
	"Muritiba",
	"Mutuípe",
	"Natal",
	"Natuba",
	"Nazaré",
	"Nazaré da Mata",
	"Nazaré do Piauí",
	"Nazarezinho",
	"Nazária",
	"Neópolis",
	"Nilo Peçanha",
	"Nina Rodrigues",
	"Nísia Floresta",
	"Nordestina",
	"Nossa Senhora Aparecida",
	"Nossa Senhora da Glória",
	"Nossa Senhora das Dores",
	"Nossa Senhora de Lourdes",
	"Nossa Senhora de Nazaré",
	"Nossa Senhora do Socorro",
	"Nossa Senhora dos Remédios",
	"Nova Canaã",
	"Nova Colinas",
	"Nova Cruz",
	"Nova Floresta",
	"Nova Ibiá",
	"Nova Iorque",
	"Nova Itarana",
	"Nova Olinda",
	"Nova Olinda do Maranhão",
	"Nova Palmeira",
	"Nova Redenção",
	"Nova Russas",
	"Nova Soure",
	"Nova Viçosa",
	"Novo Lino",
	"Novo Oriente",
	"Novo Oriente do Piauí",
	"Novo Santo Antônio",
	"Novo Triunfo",
	"Ocara",
	"Oeiras",
	"Olho d'Água",
	"Olho d'Água das Cunhãs",
	"Olho d'Água das Flores",
	"Olho d'Água do Borges",
	"Olho d'Água do Casado",
	"Olho D'Água do Piauí",
	"Olho d'Água Grande",
	"Olinda",
	"Olinda Nova do Maranhão",
	"Olindina",
	"Olivedos",
	"Oliveira dos Brejinhos",
	"Olivença",
	"Orobó",
	"Orocó",
	"Orós",
	"Ouriçangas",
	"Ouricuri",
	"Ouro Velho",
	"Ourolândia",
	"Pacajus",
	"Pacatuba",
	"Paço do Lumiar",
	"Pacoti",
	"Pacujá",
	"Padre Marcos",
	"Paes Landim",
	"Pajeú do Piauí",
	"Palhano",
	"Palmácia",
	"Palmares",
	"Palmas de Monte Alto",
	"Palmeira do Piauí",
	"Palmeira dos Índios",
	"Palmeirais",
	"Palmeirândia",
	"Palmeiras",
	"Palmeirina",
	"Panelas",
	"Pão de Açúcar",
	"Paquetá",
	"Paracuru",
	"Paraibano",
	"Paraipaba",
	"Parambu",
	"Paramirim",
	"Paramoti",
	"Paraná",
	"Paranatama",
	"Parari",
	"Paratinga",
	"Paraú",
	"Parazinho",
	"Parelhas",
	"Pariconha",
	"Paripiranga",
	"Paripueira",
	"Parnaguá",
	"Parnaíba",
	"Parnamirim",
	"Parnarama",
	"Passa e Fica",
	"Passagem",
	"Passagem Franca",
	"Passagem Franca do Piauí",
	"Passira",
	"Passo de Camaragibe",
	"Pastos Bons",
	"Patos",
	"Patos do Piauí",
	"Patu",
	"Pau Brasil",
	"Pau D'Arco do Piauí",
	"Pau dos Ferros",
	"Paudalho",
	"Paulino Neves",
	"Paulista",
	"Paulistana",
	"Paulo Afonso",
	"Paulo Jacinto",
	"Paulo Ramos",
	"Pavussu",
	"Pé de Serra",
	"Pedra",
	"Pedra Branca",
	"Pedra Grande",
	"Pedra Lavrada",
	"Pedra Mole",
	"Pedra Preta",
	"Pedrão",
	"Pedras de Fogo",
	"Pedreiras",
	"Pedrinhas",
	"Pedro Alexandre",
	"Pedro Avelino",
	"Pedro do Rosário",
	"Pedro II",
	"Pedro Laurentino",
	"Pedro Régis",
	"Pedro Velho",
	"Penaforte",
	"Penalva",
	"Pendências",
	"Penedo",
	"Pentecoste",
	"Pereiro",
	"Peri Mirim",
	"Peritoró",
	"Pesqueira",
	"Petrolina",
	"Piaçabuçu",
	"Piancó",
	"Piatã",
	"Picos",
	"Picuí",
	"Pilão Arcado",
	"Pilar",
	"Pilões",
	"Pilõezinhos",
	"Pimenteiras",
	"Pindaí",
	"Pindaré-Mirim",
	"Pindoba",
	"Pindobaçu",
	"Pindoretama",
	"Pinheiro",
	"Pintadas",
	"Pio IX",
	"Pio XII",
	"Piquet Carneiro",
	"Piracuruca",
	"Piraí do Norte",
	"Pirambu",
	"Piranhas",
	"Pirapemas",
	"Pires Ferreira",
	"Piripá",
	"Piripiri",
	"Piritiba",
	"Pirpirituba",
	"Pitimbu",
	"Planaltino",
	"Poção",
	"Poção de Pedras",
	"Pocinhos",
	"Poço Branco",
	"Poço Dantas",
	"Poço das Trincheiras",
	"Poço de José de Moura",
	"Poço Redondo",
	"Poço Verde",
	"Poções",
	"Pojuca",
	"Pombal",
	"Pombos",
	"Ponto Novo",
	"Poranga",
	"Portalegre",
	"Porteiras",
	"Porto",
	"Porto Alegre do Piauí",
	"Porto Calvo",
	"Porto da Folha",
	"Porto de Pedras",
	"Porto do Mangue",
	"Porto Franco",
	"Porto Real do Colégio",
	"Porto Rico do Maranhão",
	"Porto Seguro",
	"Potengi",
	"Potiraguá",
	"Potiretama",
	"Prado",
	"Prata do Piauí",
	"Presidente Dutra",
	"Presidente Jânio Quadros",
	"Presidente Médici",
	"Presidente Sarney",
	"Presidente Tancredo Neves",
	"Presidente Vargas",
	"Primavera",
	"Primeira Cruz",
	"Princesa Isabel",
	"Propriá",
	"Pureza",
	"Puxinanã",
	"Quebrangulo",
	"Queimada Nova",
	"Queimadas",
	"Quijingue",
	"Quipapá",
	"Quiterianópolis",
	"Quixaba",
	"Quixabeira",
	"Quixadá",
	"Quixelô",
	"Quixeramobim",
	"Quixeré",
	"Rafael Fernandes",
	"Rafael Godeiro",
	"Rafael Jambeiro",
	"Raposa",
	"Recife",
	"Redenção",
	"Redenção do Gurguéia",
	"Regeneração",
	"Remanso",
	"Remígio",
	"Reriutaba",
	"Retirolândia",
	"Riachão",
	"Riachão das Neves",
	"Riachão do Bacamarte",
	"Riachão do Dantas",
	"Riachão do Jacuípe",
	"Riachão do Poço",
	"Riacho da Cruz",
	"Riacho das Almas",
	"Riacho de Santana",
	"Riacho de Santo Antônio",
	"Riacho dos Cavalos",
	"Riacho Frio",
	"Riachuelo",
	"Ribamar Fiquene",
	"Ribeira do Amparo",
	"Ribeira do Piauí",
	"Ribeira do Pombal",
	"Ribeirão",
	"Ribeirão do Largo",
	"Ribeiro Gonçalves",
	"Ribeirópolis",
	"Rio de Contas",
	"Rio do Antônio",
	"Rio do Fogo",
	"Rio do Pires",
	"Rio Formoso",
	"Rio Grande do Piauí",
	"Rio Largo",
	"Rio Real",
	"Rio Tinto",
	"Rodelas",
	"Rodolfo Fernandes",
	"Rosário",
	"Rosário do Catete",
	"Roteiro",
	"Russas",
	"Ruy Barbosa",
	"Saboeiro",
	"Sairé",
	"Salgadinho",
	"Salgado",
	"Salgado de São Félix",
	"Salgueiro",
	"Salinas da Margarida",
	"Salitre",
	"Saloá",
	"Salvador",
	"Sambaíba",
	"Sanharó",
	"Santa Brígida",
	"Santa Cruz",
	"Santa Cruz Cabrália",
	"Santa Cruz da Baixa Verde",
	"Santa Cruz da Vitória",
	"Santa Cruz do Capibaribe",
	"Santa Cruz do Piauí",
	"Santa Cruz dos Milagres",
	"Santa Filomena",
	"Santa Filomena do Maranhão",
	"Santa Luz",
	"Santa Luzia do Itanhy",
	"Santa Luzia do Norte",
	"Santa Luzia do Paruá",
	"Santa Maria da Boa Vista",
	"Santa Maria da Vitória",
	"Santa Maria do Cambucá",
	"Santa Quitéria",
	"Santa Quitéria do Maranhão",
	"Santa Rita",
	"Santa Rita de Cássia",
	"Santa Rosa do Piauí",
	"Santa Teresinha",
	"Santaluz",
	"Santana",
	"Santana de Mangueira",
	"Santana do Acaraú",
	"Santana do Cariri",
	"Santana do Ipanema",
	"Santana do Maranhão",
	"Santana do Matos",
	"Santana do Mundaú",
	"Santana do Piauí",
	"Santana do São Francisco",
	"Santana do Seridó",
	"Santana dos Garrotes",
	"Santanópolis",
	"Santo Amaro",
	"Santo Amaro das Brotas",
	"Santo Amaro do Maranhão",
	"Santo Antônio",
	"Santo Antônio de Jesus",
	"Santo Antônio de Lisboa",
	"Santo Antônio dos Lopes",
	"Santo Antônio dos Milagres",
	"Santo Estêvão",
	"Santo Inácio do Piauí",
	"São Benedito",
	"São Benedito do Rio Preto",
	"São Benedito do Sul",
	"São Bentinho",
	"São Bento",
	"São Bento do Norte",
	"São Bento do Trairí",
	"São Bento do Una",
	"São Bernardo",
	"São Brás",
	"São Braz do Piauí",
	"São Caitano",
	"São Cristóvão",
	"São Desidério",
	"São Domingos do Azeitão",
	"São Domingos do Cariri",
	"São Domingos do Maranhão",
	"São Felipe",
	"São Félix",
	"São Félix de Balsas",
	"São Félix do Coribe",
	"São Félix do Piauí",
	"São Fernando",
	"São Francisco de Assis do Piauí",
	"São Francisco do Brejão",
	"São Francisco do Conde",
	"São Francisco do Maranhão",
	"São Francisco do Oeste",
	"São Francisco do Piauí",
	"São Gonçalo do Amarante",
	"São Gonçalo do Gurguéia",
	"São Gonçalo do Piauí",
	"São Gonçalo dos Campos",
	"São João da Canabrava",
	"São João da Fronteira",
	"São João da Serra",
	"São João da Varjota",
	"São João do Arraial",
	"São João do Cariri",
	"São João do Carú",
	"São João do Jaguaribe",
	"São João do Piauí",
	"São João do Rio do Peixe",
	"São João do Sabugi",
	"São João do Soter",
	"São João do Tigre",
	"São João dos Patos",
	"São Joaquim do Monte",
	"São José da Coroa Grande",
	"São José da Lagoa Tapada",
	"São José da Laje",
	"São José da Tapera",
	"São José da Vitória",
	"São José de Caiana",
	"São José de Espinharas",
	"São José de Mipibu",
	"São José de Piranhas",
	"São José de Princesa",
	"São José de Ribamar",
	"São José do Belmonte",
	"São José do Bonfim",
	"São José do Brejo do Cruz",
	"São José do Campestre",
	"São José do Egito",
	"São José do Jacuípe",
	"São José do Peixe",
	"São José do Piauí",
	"São José do Sabugi",
	"São José do Seridó",
	"São José dos Basílios",
	"São José dos Cordeiros",
	"São José dos Ramos",
	"São Julião",
	"São Lourenço da Mata",
	"São Lourenço do Piauí",
	"São Luís",
	"São Luís do Curu",
	"São Luis do Piauí",
	"São Luís do Quitunde",
	"São Luís Gonzaga do Maranhão",
	"São Mamede",
	"São Mateus do Maranhão",
	"São Miguel",
	"São Miguel da Baixa Grande",
	"São Miguel das Matas",
	"São Miguel de Taipu",
	"São Miguel do Aleixo",
	"São Miguel do Fidalgo",
	"São Miguel do Gostoso",
	"São Miguel do Tapuio",
	"São Miguel dos Campos",
	"São Miguel dos Milagres",
	"São Paulo do Potengi",
	"São Pedro da Água Branca",
	"São Pedro do Piauí",
	"São Pedro dos Crentes",
	"São Rafael",
	"São Raimundo das Mangabeiras",
	"São Raimundo do Doca Bezerra",
	"São Raimundo Nonato",
	"São Roberto",
	"São Sebastião de Lagoa de Roça",
	"São Sebastião do Passé",
	"São Sebastião do Umbuzeiro",
	"São Vicente do Seridó",
	"São Vicente Ferrer",
	"São Vicente Férrer",
	"Sapé",
	"Sapeaçu",
	"Sátiro Dias",
	"Satuba",
	"Satubinha",
	"Saubara",
	"Saúde",
	"Seabra",
	"Sebastião Barros",
	"Sebastião Laranjeiras",
	"Sebastião Leal",
	"Senador Alexandre Costa",
	"Senador Elói de Souza",
	"Senador Georgino Avelino",
	"Senador La Rocque",
	"Senador Pompeu",
	"Senador Rui Palmeira",
	"Senador Sá",
	"Senhor do Bonfim",
	"Sento Sé",
	"Serra Branca",
	"Serra Caiada",
	"Serra da Raiz",
	"Serra de São Bento",
	"Serra do Mel",
	"Serra do Ramalho",
	"Serra Dourada",
	"Serra Grande",
	"Serra Negra do Norte",
	"Serra Preta",
	"Serra Redonda",
	"Serra Talhada",
	"Serrano do Maranhão",
	"Serraria",
	"Serrinha",
	"Serrinha dos Pintos",
	"Serrita",
	"Serrolândia",
	"Sertânia",
	"Severiano Melo",
	"Sigefredo Pacheco",
	"Simão Dias",
	"Simões",
	"Simões Filho",
	"Simplício Mendes",
	"Sirinhaém",
	"Siriri",
	"Sítio do Mato",
	"Sítio do Quinto",
	"Sítio Novo",
	"Sobrado",
	"Sobral",
	"Socorro do Piauí",
	"Solânea",
	"Solidão",
	"Solonópole",
	"Sossêgo",
	"Sousa",
	"Souto Soares",
	"Sucupira do Norte",
	"Sucupira do Riachão",
	"Sumé",
	"Surubim",
	"Sussuapara",
	"Tabira",
	"Tabocas do Brejo Velho",
	"Taboleiro Grande",
	"Tabuleiro do Norte",
	"Tacaimbó",
	"Tacaratu",
	"Tacima",
	"Taipu",
	"Tamandaré",
	"Tamboril",
	"Tamboril do Piauí",
	"Tanhaçu",
	"Tanque d'Arca",
	"Tanque do Piauí",
	"Tanque Novo",
	"Tanquinho",
	"Taperoá",
	"Tapiramutá",
	"Taquarana",
	"Taquaritinga do Norte",
	"Tarrafas",
	"Tasso Fragoso",
	"Tauá",
	"Teixeira",
	"Teixeira de Freitas",
	"Tejuçuoca",
	"Telha",
	"Tenente Ananias",
	"Tenente Laurentino Cruz",
	"Tenório",
	"Teofilândia",
	"Teolândia",
	"Teotônio Vilela",
	"Teresina",
	"Terezinha",
	"Terra Nova",
	"Tianguá",
	"Tibau",
	"Tibau do Sul",
	"Timbaúba",
	"Timbaúba dos Batistas",
	"Timbiras",
	"Timon",
	"Tobias Barreto",
	"Tomar do Geru",
	"Toritama",
	"Touros",
	"Tracunhaém",
	"Traipu",
	"Trairi",
	"Tremedal",
	"Trindade",
	"Triunfo Potiguar",
	"Trizidela do Vale",
	"Tucano",
	"Tufilândia",
	"Tuntum",
	"Tupanatinga",
	"Tuparetama",
	"Turiaçu",
	"Turilândia",
	"Tururu",
	"Tutóia",
	"Uauá",
	"Ubaíra",
	"Ubaitaba",
	"Ubajara",
	"Ubatã",
	"Uibaí",
	"Uiraúna",
	"Umari",
	"Umarizal",
	"Umbaúba",
	"Umburanas",
	"Umbuzeiro",
	"Umirim",
	"Una",
	"União",
	"União dos Palmares",
	"Upanema",
	"Urandi",
	"Urbano Santos",
	"Uruburetama",
	"Uruçuca",
	"Uruçuí",
	"Uruoca",
	"Utinga",
	"Valença do Piauí",
	"Valente",
	"Vargem Grande",
	"Varjota",
	"Várzea",
	"Várzea Alegre",
	"Várzea Branca",
	"Várzea da Roça",
	"Várzea do Poço",
	"Várzea Grande",
	"Várzea Nova",
	"Varzedo",
	"Venha-Ver",
	"Venturosa",
	"Vera Mendes",
	"Verdejante",
	"Vereda",
	"Vertente do Lério",
	"Vertentes",
	"Vicência",
	"Viçosa do Ceará",
	"Vieirópolis",
	"Vila Flor",
	"Vila Nova do Piauí",
	"Vila Nova dos Martírios",
	"Vista Serrana",
	"Vitória da Conquista",
	"Vitória de Santo Antão",
	"Vitória do Mearim",
	"Vitorino Freire",
	"Wagner",
	"Wall Ferraz",
	"Wanderley",
	"Wenceslau Guimarães",
	"Xexéu",
	"Xique-Xique",
	"Zabelê",
	"Zé Doca",
	"Abaetetuba",
	"Abel Figueiredo",
	"Abreulândia",
	"Acará",
	"Acrelândia",
	"Afuá",
	"Água Azul do Norte",
	"Aguiarnópolis",
	"Alenquer",
	"Aliança do Tocantins",
	"Almas",
	"Almeirim",
	"Alta Floresta D'Oeste",
	"Altamira",
	"Alto Alegre dos Parecis",
	"Alvarães",
	"Alvorada D'Oeste",
	"Amajari",
	"Amapá",
	"Amaturá",
	"Anajás",
	"Anamã",
	"Ananás",
	"Ananindeua",
	"Anapu",
	"Angico",
	"Anori",
	"Aparecida do Rio Negro",
	"Apuí",
	"Aragominas",
	"Araguacema",
	"Araguaçu",
	"Araguaína",
	"Araguatins",
	"Arapoema",
	"Ariquemes",
	"Arraias",
	"Assis Brasil",
	"Atalaia do Norte",
	"Augustinópolis",
	"Augusto Corrêa",
	"Aurora do Pará",
	"Aurora do Tocantins",
	"Autazes",
	"Aveiro",
	"Axixá do Tocantins",
	"Babaçulândia",
	"Bagre",
	"Baião",
	"Bandeirantes do Tocantins",
	"Bannach",
	"Barcarena",
	"Barcelos",
	"Barra do Ouro",
	"Barreirinha",
	"Barrolândia",
	"Belterra",
	"Benevides",
	"Benjamin Constant",
	"Bernardo Sayão",
	"Beruri",
	"Boa Vista do Ramos",
	"Boca do Acre",
	"Bom Jesus do Tocantins",
	"Borba",
	"Bragança",
	"Brasil Novo",
	"Brasilândia do Tocantins",
	"Brasiléia",
	"Brejinho de Nazaré",
	"Brejo Grande do Araguaia",
	"Breu Branco",
	"Breves",
	"Bujari",
	"Bujaru",
	"Buriti do Tocantins",
	"Caapiranga",
	"Cabixi",
	"Cacaulândia",
	"Cachoeira do Arari",
	"Cachoeira do Piriá",
	"Cacoal",
	"Calçoene",
	"Cametá",
	"Campo Novo de Rondônia",
	"Campos Lindos",
	"Canaã dos Carajás",
	"Candeias do Jamari",
	"Cantá",
	"Canutama",
	"Capitão Poço",
	"Capixaba",
	"Caracaraí",
	"Carauari",
	"Careiro",
	"Careiro da Várzea",
	"Cariri do Tocantins",
	"Carmolândia",
	"Caroebe",
	"Carrasco Bonito",
	"Caseara",
	"Castanhal",
	"Castanheiras",
	"Cerejeiras",
	"Chapada da Natividade",
	"Chapada de Areia",
	"Chaves",
	"Chupinguaia",
	"Coari",
	"Codajás",
	"Colares",
	"Colinas do Tocantins",
	"Colméia",
	"Colorado do Oeste",
	"Combinado",
	"Conceição do Araguaia",
	"Conceição do Tocantins",
	"Concórdia do Pará",
	"Corumbiara",
	"Costa Marques",
	"Couto Magalhães",
	"Cristalândia",
	"Crixás do Tocantins",
	"Cujubim",
	"Cumaru do Norte",
	"Curionópolis",
	"Curralinho",
	"Curuá",
	"Curuçá",
	"Cutias",
	"Darcinópolis",
	"Dianópolis",
	"Divinópolis do Tocantins",
	"Dois Irmãos do Tocantins",
	"Dom Eliseu",
	"Dueré",
	"Eirunepé",
	"Eldorado do Carajás",
	"Envira",
	"Epitaciolândia",
	"Espigão D'Oeste",
	"Faro",
	"Feijó",
	"Ferreira Gomes",
	"Figueirópolis",
	"Floresta do Araguaia",
	"Fonte Boa",
	"Formoso do Araguaia",
	"Garrafão do Norte",
	"Goianésia do Pará",
	"Goianorte",
	"Goiatins",
	"Governador Jorge Teixeira",
	"Guajará",
	"Guajará-Mirim",
	"Guaraí",
	"Gurupá",
	"Gurupi",
	"Igarapé-Açu",
	"Igarapé-Miri",
	"Inhangapi",
	"Ipixuna",
	"Ipixuna do Pará",
	"Iranduba",
	"Irituia",
	"Itacajá",
	"Itacoatiara",
	"Itaguatins",
	"Itaituba",
	"Itamarati",
	"Itapiratins",
	"Itaporã do Tocantins",
	"Itapuã do Oeste",
	"Itaubal",
	"Itupiranga",
	"Jacareacanga",
	"Jacundá",
	"Jaru",
	"Jaú do Tocantins",
	"Ji-Paraná",
	"Jordão",
	"Juarina",
	"Juruá",
	"Juruti",
	"Jutaí",
	"Lábrea",
	"Lagoa da Confusão",
	"Lagoa do Tocantins",
	"Laranjal do Jari",
	"Lavandeira",
	"Limoeiro do Ajuru",
	"Lizarda",
	"Luzinópolis",
	"Macapá",
	"Machadinho D'Oeste",
	"Mãe do Rio",
	"Magalhães Barata",
	"Manacapuru",
	"Manaquiri",
	"Manaus",
	"Mâncio Lima",
	"Manicoré",
	"Manoel Urbano",
	"Maraã",
	"Marabá",
	"Maracanã",
	"Marapanim",
	"Marechal Thaumaturgo",
	"Marianópolis do Tocantins",
	"Marituba",
	"Mateiros",
	"Maués",
	"Maurilândia do Tocantins",
	"Mazagão",
	"Medicilândia",
	"Melgaço",
	"Ministro Andreazza",
	"Miracema do Tocantins",
	"Miranorte",
	"Mirante da Serra",
	"Mocajuba",
	"Moju",
	"Mojuí dos Campos",
	"Monte do Carmo",
	"Monte Negro",
	"Monte Santo do Tocantins",
	"Muaná",
	"Mucajaí",
	"Muricilândia",
	"Nhamundá",
	"Normandia",
	"Nova Brasilândia D'Oeste",
	"Nova Esperança do Piriá",
	"Nova Ipixuna",
	"Nova Mamoré",
	"Nova Olinda do Norte",
	"Nova Rosalândia",
	"Nova Timboteua",
	"Novo Acordo",
	"Novo Airão",
	"Novo Alegre",
	"Novo Aripuanã",
	"Novo Horizonte do Oeste",
	"Novo Jardim",
	"Novo Progresso",
	"Novo Repartimento",
	"Óbidos",
	"Oeiras do Pará",
	"Oiapoque",
	"Oliveira de Fátima",
	"Oriximiná",
	"Ourém",
	"Ourilândia do Norte",
	"Ouro Preto do Oeste",
	"Pacajá",
	"Pacaraima",
	"Palestina do Pará",
	"Palmeirante",
	"Palmeiras do Tocantins",
	"Palmeirópolis",
	"Paragominas",
	"Paraíso do Tocantins",
	"Paranã",
	"Parauapebas",
	"Parecis",
	"Parintins",
	"Pau D'Arco",
	"Pauini",
	"Pedra Branca do Amapari",
	"Pedro Afonso",
	"Peixe",
	"Peixe-Boi",
	"Pequizeiro",
	"Piçarra",
	"Pimenta Bueno",
	"Pimenteiras do Oeste",
	"Pindorama do Tocantins",
	"Piraquê",
	"Pium",
	"Placas",
	"Plácido de Castro",
	"Ponta de Pedras",
	"Ponte Alta do Bom Jesus",
	"Ponte Alta do Tocantins",
	"Portel",
	"Porto Acre",
	"Porto Alegre do Tocantins",
	"Porto de Moz",
	"Porto Grande",
	"Porto Nacional",
	"Porto Velho",
	"Porto Walter",
	"Pracuúba",
	"Praia Norte",
	"Prainha",
	"Presidente Figueiredo",
	"Primavera de Rondônia",
	"Pugmil",
	"Quatipuru",
	"Recursolândia",
	"Rio Branco",
	"Rio Crespo",
	"Rio da Conceição",
	"Rio dos Bois",
	"Rio Maria",
	"Rio Preto da Eva",
	"Rio Sono",
	"Rodrigues Alves",
	"Rolim de Moura",
	"Rondon do Pará",
	"Rorainópolis",
	"Rurópolis",
	"Salinópolis",
	"Salvaterra",
	"Sampaio",
	"Sandolândia",
	"Santa Bárbara do Pará",
	"Santa Cruz do Arari",
	"Santa Fé do Araguaia",
	"Santa Isabel do Rio Negro",
	"Santa Izabel do Pará",
	"Santa Luzia D'Oeste",
	"Santa Luzia do Pará",
	"Santa Maria das Barreiras",
	"Santa Maria do Pará",
	"Santa Maria do Tocantins",
	"Santa Rita do Tocantins",
	"Santa Rosa do Purus",
	"Santa Rosa do Tocantins",
	"Santa Tereza do Tocantins",
	"Santa Terezinha do Tocantins",
	"Santana do Araguaia",
	"Santarém",
	"Santarém Novo",
	"Santo Antônio do Içá",
	"Santo Antônio do Tauá",
	"São Bento do Tocantins",
	"São Caetano de Odivelas",
	"São Domingos do Araguaia",
	"São Domingos do Capim",
	"São Felipe D'Oeste",
	"São Félix do Tocantins",
	"São Félix do Xingu",
	"São Francisco do Guaporé",
	"São Francisco do Pará",
	"São Gabriel da Cachoeira",
	"São Geraldo do Araguaia",
	"São João da Baliza",
	"São João da Ponta",
	"São João de Pirabas",
	"São João do Araguaia",
	"São Luiz do Anauá",
	"São Miguel do Guamá",
	"São Miguel do Guaporé",
	"São Miguel do Tocantins",
	"São Paulo de Olivença",
	"São Salvador do Tocantins",
	"São Sebastião da Boa Vista",
	"São Sebastião do Tocantins",
	"São Sebastião do Uatumã",
	"São Valério",
	"Sena Madureira",
	"Senador Guiomard",
	"Senador José Porfírio",
	"Seringueiras",
	"Serra do Navio",
	"Silvanópolis",
	"Silves",
	"Sítio Novo do Tocantins",
	"Soure",
	"Sucupira",
	"Tabocão",
	"Taguatinga",
	"Tailândia",
	"Taipas do Tocantins",
	"Talismã",
	"Tapauá",
	"Tarauacá",
	"Tartarugalzinho",
	"Tefé",
	"Teixeirópolis",
	"Terra Alta",
	"Terra Santa",
	"Theobroma",
	"Tocantínia",
	"Tocantinópolis",
	"Tomé-Açu",
	"Tonantins",
	"Tracuateua",
	"Trairão",
	"Tucumã",
	"Tucuruí",
	"Tupirama",
	"Tupiratins",
	"Uarini",
	"Uiramutã",
	"Ulianópolis",
	"Uruará",
	"Urucará",
	"Urucurituba",
	"Urupá",
	"Vale do Anari",
	"Vale do Paraíso",
	"Vigia",
	"Vilhena",
	"Viseu",
	"Vitória do Jari",
	"Vitória do Xingu",
	"Wanderlândia",
	"Xambioá",
	"Xapuri",
	"Xinguara",
	"Abadia de Goiás",
	"Abadiânia",
	"Acorizal",
	"Acreúna",
	"Adelândia",
	"Água Clara",
	"Água Fria de Goiás",
	"Água Limpa",
	"Águas Lindas de Goiás",
	"Alcinópolis",
	"Alexânia",
	"Aloândia",
	"Alta Floresta",
	"Alto Araguaia",
	"Alto Boa Vista",
	"Alto Garças",
	"Alto Horizonte",
	"Alto Paraguai",
	"Alto Paraíso de Goiás",
	"Alto Taquari",
	"Alvorada do Norte",
	"Amambai",
	"Amaralina",
	"Americano do Brasil",
	"Amorinópolis",
	"Anápolis",
	"Anastácio",
	"Anaurilândia",
	"Angélica",
	"Anhanguera",
	"Anicuns",
	"Antônio João",
	"Aparecida de Goiânia",
	"Aparecida do Rio Doce",
	"Aparecida do Taboado",
	"Apiacás",
	"Aporé",
	"Aquidauana",
	"Araçu",
	"Aragarças",
	"Aragoiânia",
	"Araguaiana",
	"Araguainha",
	"Araguapaz",
	"Aral Moreira",
	"Araputanga",
	"Arenápolis",
	"Arenópolis",
	"Aripuanã",
	"Aruanã",
	"Aurilândia",
	"Avelinópolis",
	"Baliza",
	"Barão de Melgaço",
	"Barra do Bugres",
	"Barra do Garças",
	"Bataguassu",
	"Batayporã",
	"Bela Vista",
	"Bela Vista de Goiás",
	"Boa Esperança do Norte",
	"Bodoquena",
	"Bom Jardim de Goiás",
	"Bom Jesus de Goiás",
	"Bom Jesus do Araguaia",
	"Bonfinópolis",
	"Bonópolis",
	"Brasilândia",
	"Brasília",
	"Brasnorte",
	"Brazabrantes",
	"Britânia",
	"Buriti Alegre",
	"Buriti de Goiás",
	"Buritinópolis",
	"Caarapó",
	"Cabeceiras",
	"Cáceres",
	"Cachoeira Alta",
	"Cachoeira de Goiás",
	"Caçu",
	"Caiapônia",
	"Caldas Novas",
	"Caldazinha",
	"Camapuã",
	"Campestre de Goiás",
	"Campinaçu",
	"Campinápolis",
	"Campinorte",
	"Campo Alegre de Goiás",
	"Campo Limpo de Goiás",
	"Campo Novo do Parecis",
	"Campo Verde",
	"Campos Belos",
	"Campos de Júlio",
	"Campos Verdes",
	"Canabrava do Norte",
	"Carlinda",
	"Carmo do Rio Verde",
	"Cassilândia",
	"Castanheira",
	"Castelândia",
	"Catalão",
	"Caturaí",
	"Cavalcante",
	"Ceres",
	"Cezarina",
	"Chapada dos Guimarães",
	"Chapadão do Céu",
	"Chapadão do Sul",
	"Cidade Ocidental",
	"Cláudia",
	"Cocalinho",
	"Cocalzinho de Goiás",
	"Colíder",
	"Colinas do Sul",
	"Colniza",
	"Comodoro",
	"Confresa",
	"Conquista D'Oeste",
	"Corguinho",
	"Coronel Sapucaia",
	"Córrego do Ouro",
	"Corumbá",
	"Corumbá de Goiás",
	"Corumbaíba",
	"Costa Rica",
	"Cotriguaçu",
	"Coxim",
	"Cristalina",
	"Cristianópolis",
	"Crixás",
	"Cromínia",
	"Cuiabá",
	"Cumari",
	"Curvelândia",
	"Damianópolis",
	"Damolândia",
	"Denise",
	"Deodápolis",
	"Diamantino",
	"Diorama",
	"Divinópolis de Goiás",
	"Dois Irmãos do Buriti",
	"Dom Aquino",
	"Dourados",
	"Doverlândia",
	"Edealina",
	"Edéia",
	"Faina",
	"Fátima do Sul",
	"Fazenda Nova",
	"Feliz Natal",
	"Figueirão",
	"Figueirópolis D'Oeste",
	"Firminópolis",
	"Flores de Goiás",
	"Formosa",
	"Gameleira de Goiás",
	"Gaúcha do Norte",
	"Glória D'Oeste",
	"Glória de Dourados",
	"Goianápolis",
	"Goiandira",
	"Goianésia",
	"Goiânia",
	"Goianira",
	"Goiás",
	"Goiatuba",
	"Gouvelândia",
	"Guapó",
	"Guaraíta",
	"Guarani de Goiás",
	"Guarantã do Norte",
	"Guarinos",
	"Guia Lopes da Laguna",
	"Guiratinga",
	"Heitoraí",
	"Hidrolina",
	"Iaciara",
	"Iguatemi",
	"Inaciolândia",
	"Indiara",
	"Indiavaí",
	"Inhumas",
	"Inocência",
	"Ipameri",
	"Ipiranga de Goiás",
	"Ipiranga do Norte",
	"Iporá",
	"Israelândia",
	"Itaberaí",
	"Itaguari",
	"Itaguaru",
	"Itanhangá",
	"Itapaci",
	"Itapirapuã",
	"Itaporã",
	"Itapuranga",
	"Itaquiraí",
	"Itarumã",
	"Itaúba",
	"Itauçu",
	"Itiquira",
	"Itumbiara",
	"Ivinhema",
	"Ivolândia",
	"Jaciara",
	"Jandaia",
	"Jangada",
	"Japorã",
	"Jaraguá",
	"Jaraguari",
	"Jataí",
	"Jateí",
	"Jaupaci",
	"Jauru",
	"Jesúpolis",
	"Joviânia",
	"Juara",
	"Juína",
	"Juruena",
	"Juscimeira",
	"Juti",
	"Ladário",
	"Laguna Carapã",
	"Lambari D'Oeste",
	"Leopoldo de Bulhões",
	"Lucas do Rio Verde",
	"Luciara",
	"Luziânia",
	"Mairipotaba",
	"Mambaí",
	"Mara Rosa",
	"Maracaju",
	"Marcelândia",
	"Marzagão",
	"Matrinchã",
	"Matupá",
	"Maurilândia",
	"Mimoso de Goiás",
	"Minaçu",
	"Mineiros",
	"Miranda",
	"Mirassol d'Oeste",
	"Moiporá",
	"Monte Alegre de Goiás",
	"Montes Claros de Goiás",
	"Montividiu",
	"Montividiu do Norte",
	"Morro Agudo de Goiás",
	"Mossâmedes",
	"Mozarlândia",
	"Mutunópolis",
	"Naviraí",
	"Nazário",
	"Nerópolis",
	"Nioaque",
	"Niquelândia",
	"Nobres",
	"Nortelândia",
	"Nossa Senhora do Livramento",
	"Nova Alvorada do Sul",
	"Nova América",
	"Nova Andradina",
	"Nova Bandeirantes",
	"Nova Brasilândia",
	"Nova Canaã do Norte",
	"Nova Crixás",
	"Nova Glória",
	"Nova Guarita",
	"Nova Iguaçu de Goiás",
	"Nova Lacerda",
	"Nova Marilândia",
	"Nova Maringá",
	"Nova Monte Verde",
	"Nova Mutum",
	"Nova Nazaré",
	"Nova Roma",
	"Nova Santa Helena",
	"Nova Ubiratã",
	"Nova Xavantina",
	"Novo Brasil",
	"Novo Gama",
	"Novo Horizonte do Norte",
	"Novo Horizonte do Sul",
	"Novo Mundo",
	"Novo Planalto",
	"Novo São Joaquim",
	"Orizona",
	"Ouro Verde de Goiás",
	"Ouvidor",
	"Padre Bernardo",
	"Palestina de Goiás",
	"Palmeiras de Goiás",
	"Palmelo",
	"Palminópolis",
	"Panamá",
	"Paraíso das Águas",
	"Paranaíba",
	"Paranaiguara",
	"Paranaíta",
	"Paranatinga",
	"Paranhos",
	"Paraúna",
	"Pedro Gomes",
	"Peixoto de Azevedo",
	"Perolândia",
	"Petrolina de Goiás",
	"Pilar de Goiás",
	"Piracanjuba",
	"Pirenópolis",
	"Pires do Rio",
	"Planaltina",
	"Planalto da Serra",
	"Poconé",
	"Ponta Porã",
	"Pontal do Araguaia",
	"Pontalina",
	"Ponte Branca",
	"Pontes e Lacerda",
	"Porangatu",
	"Porteirão",
	"Portelândia",
	"Porto Alegre do Norte",
	"Porto dos Gaúchos",
	"Porto Esperidião",
	"Porto Estrela",
	"Porto Murtinho",
	"Posse",
	"Poxoréu",
	"Primavera do Leste",
	"Professor Jamil",
	"Querência",
	"Quirinópolis",
	"Reserva do Cabaçal",
	"Rialma",
	"Rianápolis",
	"Ribas do Rio Pardo",
	"Ribeirão Cascalheira",
	"Ribeirãozinho",
	"Rio Brilhante",
	"Rio Quente",
	"Rio Verde",
	"Rio Verde de Mato Grosso",
	"Rochedo",
	"Rondolândia",
	"Rondonópolis",
	"Rosário Oeste",
	"Rubiataba",
	"Salto do Céu",
	"Sanclerlândia",
	"Santa Bárbara de Goiás",
	"Santa Carmem",
	"Santa Cruz de Goiás",
	"Santa Cruz do Xingu",
	"Santa Fé de Goiás",
	"Santa Helena de Goiás",
	"Santa Rita do Araguaia",
	"Santa Rita do Novo Destino",
	"Santa Rita do Pardo",
	"Santa Rita do Trivelato",
	"Santa Rosa de Goiás",
	"Santa Tereza de Goiás",
	"Santa Terezinha de Goiás",
	"Santo Afonso",
	"Santo Antônio da Barra",
	"Santo Antônio de Goiás",
	"Santo Antônio de Leverger",
	"Santo Antônio do Descoberto",
	"Santo Antônio do Leste",
	"São Félix do Araguaia",
	"São Francisco de Goiás",
	"São Gabriel do Oeste",
	"São João d'Aliança",
	"São João da Paraúna",
	"São José do Povo",
	"São José do Rio Claro",
	"São José do Xingu",
	"São José dos Quatro Marcos",
	"São Luís de Montes Belos",
	"São Luiz do Norte",
	"São Miguel do Araguaia",
	"São Miguel do Passa Quatro",
	"São Patrício",
	"São Pedro da Cipa",
	"Sapezal",
	"Selvíria",
	"Senador Canedo",
	"Serra Nova Dourada",
	"Serranópolis",
	"Sete Quedas",
	"Sidrolândia",
	"Silvânia",
	"Simolândia",
	"Sinop",
	"Sítio d'Abadia",
	"Sonora",
	"Sorriso",
	"Tabaporã",
	"Tacuru",
	"Tangará da Serra",
	"Tapurah",
	"Taquaral de Goiás",
	"Taquarussu",
	"Terenos",
	"Teresina de Goiás",
	"Terezópolis de Goiás",
	"Terra Nova do Norte",
	"Tesouro",
	"Torixoréu",
	"Três Lagoas",
	"Três Ranchos",
	"Trombas",
	"Turvânia",
	"Turvelândia",
	"Uirapuru",
	"União do Sul",
	"Uruaçu",
	"Uruana",
	"Urutaí",
	"Vale de São Domingos",
	"Valparaíso de Goiás",
	"Varjão",
	"Vera",
	"Vianópolis",
	"Vicentina",
	"Vicentinópolis",
	"Vila Bela da Santíssima Trindade",
	"Vila Boa",
	"Vila Propício",
	"Vila Rica"
}
