return {
	"Alameda Adolfo Konder",
	"Alameda das Hortênsias",
	"Alameda dos Imigrantes",
	"Avenida Atlântica",
	"Avenida Beira-Mar Norte",
	"Avenida Beira-Rio",
	"Avenida Belizário Ramos",
	"Avenida Brasil",
	"Avenida Centenário",
	"Avenida Central",
	"Avenida Colombo Machado Salles",
	"Avenida das Rendeiras",
	"Avenida do Estado",
	"Avenida Fernando Machado",
	"Avenida Getúlio Vargas",
	"Avenida Governador Celso Ramos",
	"Avenida Governador Irineu Bornhausen",
	"Avenida Hercílio Luz",
	"Avenida Ivo Silveira",
	"Avenida Jorge Lacerda",
	"Avenida Juscelino Kubitschek",
	"Avenida Madre Benvenuta",
	"Avenida Marcos Konder",
	"Avenida Mauro Ramos",
	"Avenida Nereu Ramos",
	"Avenida Osmar Cunha",
	"Avenida Osvaldo Reis",
	"Avenida Othon Gama D'Eça",
	"Avenida Paulo Fontes",
	"Avenida Pequeno Príncipe",
	"Avenida Presidente Castelo Branco",
	"Avenida Rio Branco",
	"Avenida Rubens de Arruda Ramos",
	"Avenida Santos Dumont",
	"Avenida São Pedro",
	"Avenida Sete de Setembro",
	"Avenida Trompowsky",
	"Avenida Universitária",
	"Caminho dos Açores",
	"Estrada Geral da Costa",
	"Estrada Geral da Lagoa",
	"Estrada Geral do Morro",
	"Estrada Geral do Ribeirão",
	"Estrada Geral do Rio Bonito",
	"Estrada Geral do Sertão",
	"Estrada Geral dos Colonos",
	"Estrada Geral Linha Bonita",
	"Estrada Geral Linha Colombo",
	"Estrada Geral Linha São Pedro",
	"Estrada Geral Linha Tirolesa",
	"Praça Quinze de Novembro",
	"Rua Abdon Batista",
	"Rua Adolfo Konder",
	"Rua Alberto Stein",
	"Rua Almirante Alvim",
	"Rua Almirante Lamego",
	"Rua Alves de Brito",
	"Rua Amadeu da Luz",
	"Rua Amazonas",
	"Rua Anita Garibaldi",
	"Rua Antônio da Veiga",
	"Rua Antônio Dib Mussi",
	"Rua Antônio Heil",
	"Rua Araújo Figueiredo",
	"Rua Arcipreste Paiva",
	"Rua Aubé",
	"Rua Blumenau",
	"Rua Bocaiúva",
	"Rua Bruno Hering",
	"Rua Brusque",
	"Rua Bulcão Viana",
	"Rua Camboriú",
	"Rua Capitão Romualdo de Barros",
	"Rua Clevelândia",
	"Rua Cônego Aníbal Maria di Francia",
	"Rua Conselheiro Mafra",
	"Rua Coronel Córdova",
	"Rua Coronel Feddersen",
	"Rua Coronel Pedro Benedet",
	"Rua Coronel Procópio Gomes",
	"Rua Correia Pinto",
	"Rua Crispim Mira",
	"Rua Cruz e Sousa",
	"Rua Curt Hering",
	"Rua da Praia",
	"Rua das Araucárias",
	"Rua das Gaivotas",
	"Rua das Palmeiras",
	"Rua das Rendeiras",
	"Rua Delfino Conti",
	"Rua Delminda Silveira",
	"Rua Deodoro",
	"Rua Desembargador Vítor Lima",
	"Rua do Comércio",
	"Rua do Engenho",
	"Rua do Porto",
	"Rua do Príncipe",
	"Rua Dom Jaime Câmara",
	"Rua Dona Francisca",
	"Rua dos Açorianos",
	"Rua dos Colonos",
	"Rua dos Imigrantes",
	"Rua dos Navegantes",
	"Rua dos Pescadores",
	"Rua dos Tropeiros",
	"Rua Doutor João Colin",
	"Rua Doutor Pedro Zimmermann",
	"Rua Duarte Schutel",
	"Rua Emílio Blum",
	"Rua Engenheiro Niemeyer",
	"Rua Engenheiro Paul Werner",
	"Rua Esteves Júnior",
	"Rua Expedicionário Gumercindo da Silva",
	"Rua Expedicionário Holz",
	"Rua Felipe Schmidt",
	"Rua Fernando Machado",
	"Rua Ferreira Lima",
	"Rua Florianópolis",
	"Rua Frei Caneca",
	"Rua Frei Rogério",
	"Rua Fúlvio Aducci",
	"Rua General Bittencourt",
	"Rua Giuseppe Garibaldi",
	"Rua Graciosa",
	"Rua Gustavo Richard",
	"Rua Henrique Lage",
	"Rua Henrique Valgas",
	"Rua Hercílio Luz",
	"Rua Hermann Hering",
	"Rua Hermann Huscher",
	"Rua Hoepcke",
	"Rua Imigrante Meller",
	"Rua Inambu",
	"Rua Iririú",
	"Rua Itaiópolis",
	"Rua Itajaí",
	"Rua Jaraguá",
	"Rua Jerônimo Coelho",
	"Rua João Gualberto Soares",
	"Rua João Pinto",
	"Rua João Pio Duarte Silva",
	"Rua Joe Collaço",
	"Rua Joinville",
	"Rua Lacerda Coutinho",
	"Rua Laurindo Januário da Silveira",
	"Rua Lauro Linhares",
	"Rua Lauro Müller",
	"Rua Marcos Rovaris",
	"Rua Marechal Bormann",
	"Rua Marechal Deodoro",
	"Rua Marechal Floriano Peixoto",
	"Rua Max Colin",
	"Rua Ministro Calógeras",
	"Rua Monsenhor Gercino",
	"Rua Nereu Ramos",
	"Rua Nove de Março",
	"Rua Nunes Machado",
	"Rua Orestes Guimarães",
	"Rua Otto Boehm",
	"Rua Ottokar Doerffel",
	"Rua Padre Kolb",
	"Rua Padre Roma",
	"Rua Pastor Oswaldo Hesse",
	"Rua Paulo Zimmermann",
	"Rua Pedro Ferreira",
	"Rua Pedro Ivo",
	"Rua Pomerânia",
	"Rua Pomerode",
	"Rua Prefeito Dib Cherem",
	"Rua Presidente Coutinho",
	"Rua Quinze de Novembro",
	"Rua Rafael Bandeira",
	"Rua Raulino Horn",
	"Rua Reinoldo Rau",
	"Rua Rui Barbosa",
	"Rua Saldanha Marinho",
	"Rua Samuel Heusi",
	"Rua Santa Catarina",
	"Rua Santos Saraiva",
	"Rua São Paulo",
	"Rua Sete de Setembro",
	"Rua Tenente Silveira",
	"Rua Theodoro Holtrup",
	"Rua Tijucas",
	"Rua Timbó",
	"Rua Tiradentes",
	"Rua Trajano",
	"Rua Victor Konder",
	"Rua Victor Meirelles",
	"Rua Vidal Ramos",
	"Rua Visconde de Ouro Preto",
	"Rua Visconde de Taunay",
	"Rua Voluntário Carpes",
	"Rua Walter Marquardt",
	"Servidão da Prainha",
	"Servidão das Bromélias",
	"Servidão do Pontal",
	"Servidão dos Pescadores",
	"Travessa do Comércio",
	"Travessa Ratcliff"
}
